/* AI PPT 第三批：把浏览器逐页质检、自动返修和导出前拦截接到既有工作台。 */
(function(root){
  "use strict";
  const get=id=>document.getElementById(id),state=()=>root.PptWorkspace&&root.PptWorkspace.state;let sourcePackOpen=true;
  function notify(message){const el=get("pptMessage");if(el){el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),5000);}}
  function saveBlob(blob,filename){if(!blob||!blob.size)throw new Error("导出文件为空");if(typeof navigator.msSaveOrOpenBlob==="function"){navigator.msSaveOrOpenBlob(blob,filename);return;}const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;a.style.display="none";a.rel="noopener";document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(url);},30000);}
  function plan(){const s=state();return s&&s.current&&s.current.data;}
  function sync(){const p=plan();if(!p)return null;const value=(id,fallback="")=>get(id)?get(id).value:fallback;p.title=value("pptTitle",p.title).trim();p.audience=value("pptAudience",p.audience).trim();p.purpose=value("pptPurpose",p.purpose).trim();p.templateId=value("pptTemplate",p.templateId);p.exportMode=value("pptExportMode",p.exportMode||"preview");p.sourceText=value("pptSource",p.sourceText);const s=p.slides&&p.slides[state().selected];if(s&&get("pptSlideTitle")){s.layoutId=value("pptLayout",s.layoutId);s.title=value("pptSlideTitle",s.title).trim();s.subtitle=value("pptSlideSubtitle",s.subtitle).trim();s.bullets=value("pptSlideBullets","").split("\n").map(x=>x.trim()).filter(Boolean).slice(0,8);s.sources=value("pptSlideSources","").split("\n").map(x=>x.trim()).filter(Boolean).slice(0,30);s.notes=value("pptSlideNotes",s.notes).trim();s.locked=!!(get("pptSlideLocked")&&get("pptSlideLocked").checked);try{s.content=JSON.parse(value("pptSlideContent","{}")||"{}");}catch(e){}}
    p.updatedAt=Date.now();return p;
  }
  function renderAgain(){if(root.renderSheet)root.renderSheet();}
  function preview(slide,p,index){const presets=root.PptCore.TEMPLATE_PRESETS||[],t=presets.find(x=>x.id===p.templateId)||presets[0]||{},d=p.designSpec||{},style='--ppt-accent:#'+(d.accent||t.accent||"2387C7")+';--ppt-secondary:#'+(d.secondary||t.secondary||t.accent||"70C5DE")+';--ppt-bg:#'+(d.background||t.background||"FFFFFF")+';--ppt-text:#'+(d.text||t.text||"173F63"),scene=root.PptDesignIR&&root.PptDesignIR.buildScene?root.PptDesignIR.buildScene(slide,p,index):null;if(scene)return '<div class="ppt-canvas ir-v1 pc-layout-'+(slide.layoutId||"bullets")+'" style="'+style+'">'+root.PptDesignIR.renderHtml(scene)+'</div>';return '<div class="ppt-canvas pc-layout-'+(slide.layoutId||"bullets")+'" style="'+style+'">'+root.PptComponents.renderHtml(slide)+'<footer>AI办公助手 · AI PPT <span>'+(slide.sources||[]).length+'项来源</span><b>'+(index+1)+' / '+p.slides.length+'</b></footer></div>';}
  async function inspectRendered(p){const host=document.createElement("div");host.style.cssText="position:fixed;left:-100000px;top:0;width:960px;visibility:hidden;pointer-events:none;z-index:-1";host.innerHTML=(p.slides||[]).map((s,i)=>'<div data-qc-page="'+(i+1)+'">'+preview(s,p,i)+'</div>').join("");document.body.appendChild(host);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const issues=[];host.querySelectorAll("[data-qc-page] .ppt-canvas").forEach((canvas,i)=>issues.push(...root.PptQC.inspectDom(canvas,i+1)));host.remove();return issues;}
  async function run(silent=false){let p=sync();if(!p||!root.PptQC)return null;const fixed=root.PptQC.repair(p);p=fixed.plan;let dom=await inspectRendered(p),rounds=1;if(dom.length){p=root.PptQC.repairDom(p,dom);dom=await inspectRendered(p);rounds=2;}p=root.PptQC.attachDomReport(p,dom);p.visualQa.changedPages=fixed.changedPages;p.visualQa.repairRounds=rounds;state().current.data=p;state().selected=Math.min(state().selected,p.slides.length-1);renderAgain();if(!silent)notify("视觉QA完成："+p.visualQa.score+"分，自动调整"+fixed.changedPages.length+"页，剩余"+p.visualQa.errors+"项需复核");return p.visualQa;}
  async function exportDeck(){const report=await run(true),p=plan(),base=root.PptCore.validateDeckPlan(p);if(!base.ok){notify("无法导出："+base.errors.join("；"));return;}const visualAlerts=(report&&report.issues||[]).filter(x=>x.page>0&&!(p.slides[x.page-1]||{}).locked).length;const button=get("pptExport");if(button){button.disabled=true;button.textContent="正在质检并生成…";}try{const exportPlan=JSON.parse(JSON.stringify(p));exportPlan.nativeTemplate=exportPlan.templateId==="business-blue-160"&&exportPlan.exportMode==="native";const response=await fetch("/api/ppt-export",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},root.authHeaders?root.authHeaders():{}),body:JSON.stringify({plan:exportPlan})});if(!response.ok){const data=await response.json();throw new Error(data.error||"导出失败");}const serverWarnings=Number(response.headers.get("X-PPT-QA-Warnings")||0),warnings=Math.max(serverWarnings,visualAlerts),native=response.headers.get("X-PPT-Native")==="true",blob=await response.blob();saveBlob(blob,(p.title||"项目汇报")+".pptx");notify("PowerPoint 已生成并通过结构质检"+(warnings?"（视觉QA保留"+warnings+"项提醒，不影响导出）":"")+(native?"；已采用真实商务蓝模板母页":"；已按当前预览版式所见即所得导出"));}catch(e){notify(e.message);}finally{const latest=get("pptExport");if(latest){latest.disabled=false;latest.textContent="导出 PowerPoint";}}}
  function show(){const p=sync();if(!p)return;const base=root.PptCore.validateDeckPlan(p),visual=root.PptQC.inspect(p),issues=[...base.errors.map(message=>({severity:"error",page:0,message})),...base.warnings.map(message=>({severity:"warning",page:0,message})),...visual.issues],wrap=document.createElement("div");wrap.className="ppt-modal";const rows=issues.map(x=>'<div class="ppt-qa '+(x.severity==="error"?'err':'warn')+'">'+(x.page?'第'+x.page+'页：':'')+x.message+(x.page&&p.slides[x.page-1]&&p.slides[x.page-1].locked?'（人工锁定，未自动修改）':'')+'</div>').join("");wrap.innerHTML='<div class="ppt-dialog"><div class="ppt-dialog-head"><b>PPT质量检查 · '+visual.score+'分</b><button>×</button></div><p>检查结构、来源、内容容量、颜色对比度和浏览器逐页渲染边界；人工锁定页只提示，不自动改写。</p><button class="btn primary" id="pptQaRepair">视觉QA并自动返修</button>'+(rows||'<div class="ppt-qa ok">全部检查通过</div>')+'</div>';document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.querySelector('.ppt-dialog-head button').onclick=close;wrap.onclick=e=>{if(e.target===wrap)close();};wrap.querySelector('#pptQaRepair').onclick=async()=>{close();await run(false);};}
  function install(){const sourcePack=document.querySelector("details.ppt-source");if(sourcePack&&!sourcePack.dataset.keepOpen){sourcePack.dataset.keepOpen="1";sourcePack.open=sourcePackOpen;}const actions=document.querySelector(".ppt-top-actions"),exportButton=get("pptExport"),qaButton=get("pptQaDetail");if(actions&&state()&&state().current&&!get("pptVisualQa")){const b=document.createElement("button");b.className="btn";b.id="pptVisualQa";b.textContent="视觉QA并自动返修";actions.insertBefore(b,exportButton);b.onclick=()=>run(false);}if(exportButton&&!exportButton.dataset.qcV3){exportButton.dataset.qcV3="1";exportButton.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();exportDeck();},true);}if(qaButton&&!qaButton.dataset.qcV3){qaButton.dataset.qcV3="1";qaButton.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();show();},true);}}
  document.addEventListener("toggle",event=>{if(event.target&&event.target.matches&&event.target.matches("details.ppt-source"))sourcePackOpen=event.target.open;},true);
  const original=root.bindPptWorkspace;root.bindPptWorkspace=function(){if(original)original();install();};
  const observer=new MutationObserver(()=>install());observer.observe(document.documentElement,{childList:true,subtree:true});
  root.PptQCUI={run,show,exportDeck,install};
})(window);
