/* 投资全周期项目驾驶舱：统一管理项目索引、Project Brain、阶段、恢复入口和元数据。 */
(function(root){
  "use strict";
  const PM_STATUS={draft:"草稿",collecting:"资料准备",calculated:"测算完成",generating:"生成中",review:"复核签发",signed:"已签发",paused:"暂缓"};
  const PM_TYPE={rent:"出租类",sale:"出售类",gaibao:"非居改保","保障性租赁住房":"出租类","配售型保障性住房":"出售类"};
  const esc=value=>String(value==null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const when=value=>{const d=new Date(Number(value)||value);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("zh-CN")+" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0");};
  function displayType(value){return PM_TYPE[value]||value||"类型待确认";}
  function health(p){
    const issues=[];
    if(!p.location)issues.push("位置待补");
    if(!p.calcVersions)issues.push("未形成测算快照");
    if(p.stale)issues.push(p.stale+"节待同步");
    if(!p.materials)issues.push("尚无项目资料");
    return issues.slice(0,3);
  }
  function matches(p,q){q=String(q||"").trim().toLowerCase();if(!q)return true;return [p.name,p.location,p.owner,p.type,p.stage].concat(p.tags||[]).join(" ").toLowerCase().includes(q);}
  function projectCard(p,active){
    const hs=health(p);
    return '<button type="button" class="pm-project '+(active?'active':'')+'" data-pm-select="'+esc(p.id)+'">'
      +'<span class="pm-card-top"><b>'+esc(p.name||"未命名项目")+'</b><i class="pm-status s-'+esc(p.status)+'">'+esc(PM_STATUS[p.status]||p.stage||"进行中")+'</i></span>'
      +'<span class="pm-card-meta">'+esc(displayType(p.type))+' · '+esc(p.location||"位置待补")+'</span>'
      +'<span class="pm-progress"><em style="width:'+Math.max(2,Math.min(100,Number(p.progress)||0))+'%"></em></span>'
      +'<span class="pm-card-foot"><small>'+esc(p.stage||"草稿")+' '+(p.progress||0)+'%</small><small>'+esc(when(p.updated_at))+'</small></span>'
      +(hs.length?'<span class="pm-warnings">'+hs.map(x=>'<i>'+esc(x)+'</i>').join('')+'</span>':'')+'</button>';
  }
  function brainHtml(brain,error){
    if(error)return '<div class="pm-brain"><div class="pm-brain-head"><b>Investment OS · 项目大脑</b><span>加载失败</span></div><div class="pm-brain-loading">'+esc(error)+'</div></div>';
    if(!brain)return '<div class="pm-brain"><div class="pm-brain-head"><b>Investment OS · 项目大脑</b><span>正在统一项目上下文…</span></div><div class="pm-brain-loading">正在汇总事实、指标、成果、决策与生命周期</div></div>';
    const s=brain.summary||{},life=brain.lifecycle||{},facts=(brain.facts||[]).slice(0,6),decisions=(brain.decisions||[]).slice(0,5),typeName={FACT:"事实",ASSUMPTION:"假设",CALCULATION:"计算",AI_JUDGEMENT:"AI判断"};
    return '<div class="pm-brain"><div class="pm-brain-head"><b>Investment OS · 项目大脑</b><span>当前阶段：'+esc(life.label||"待确认")+' · 旧项目零迁移兼容</span></div>'
      +'<div class="pm-lifecycle">'+(life.stages||[]).map((x,i)=>'<button class="pm-stage '+(x.key===life.current?'active':'')+'" data-pm-stage="'+esc(x.key)+'"><b>'+(i+1)+'. '+esc(x.label)+'</b>'+esc((x.deliverables||[]).slice(0,1).join(''))+'</button>').join('')+'</div>'
      +'<div class="pm-brain-kpis"><div><b>'+Number(s.confirmedFacts||0)+'/'+Number(s.facts||0)+'</b><span>已确认事实</span></div><div><b>'+Number(s.metrics||0)+'</b><span>结构化指标</span></div><div><b>'+Number(s.artifacts||0)+'</b><span>项目成果</span></div><div><b>'+Number(s.decisions||0)+'</b><span>决策事项</span></div><div><b>'+Number(s.changes||0)+'</b><span>影响变更集</span></div></div>'
      +'<div class="pm-brain-grid"><section class="pm-brain-box"><h4>统一项目事实（事实 / 假设 / 计算 / AI判断）</h4>'+(facts.length?facts.map(x=>'<div class="pm-fact-row"><span>'+esc(x.label||x.factKey)+'</span><i>'+esc(typeName[x.factType]||x.factType)+' · '+esc(x.status==="confirmed"?"已确认":"待确认")+'</i></div>').join(''):'<div class="pm-brain-loading">尚无结构化事实，现有项目内容会按访问逐步建立索引。</div>')+'</section>'
      +'<section class="pm-brain-box"><h4>决策台账</h4>'+(decisions.length?decisions.map(x=>'<div class="pm-decision-row"><b>'+esc(x.topic)+'</b><span>'+esc(x.status||"candidate")+'</span></div>').join(''):'<div class="pm-brain-loading">尚无决策事项；可从测算、审查或会议结论创建。</div>')+'<div class="pm-brain-form"><input id="pmDecisionTopic" placeholder="新增决策议题"><select id="pmDecisionOwner"><option value="">负责人待定</option><option>投资部</option><option>项目负责人</option></select><button class="ub-btn" data-pm-decision="1">新增候选</button></div></section></div></div>';
  }
  function opsHtml(ops,error){
    if(error)return '<div class="pm-ops"><div class="pm-ops-title"><b>行动 · 情景 · 生产验收</b><span class="bad">加载失败</span></div><p>'+esc(error)+'</p></div>';
    if(!ops)return '<div class="pm-ops"><div class="pm-ops-title"><b>行动 · 情景 · 生产验收</b><span>正在加载…</span></div></div>';
    const meetings=ops.meetings||[],tasks=ops.tasks||[],risks=ops.risks||[],scenarios=ops.scenarios||[],packages=ops.packages||[],evaluations=ops.evaluations||[],optimizations=ops.optimizations||[],candidate=meetings.find(x=>x.status==="candidate"),cmp=(root.InvestmentOps&&root.InvestmentOps.compareScenarios(scenarios))||{columns:[]};
    const rows=(items,kind)=>items.slice(0,6).map(x=>'<div class="pm-action-row"><span><b>'+esc(x.title)+'</b><small>'+esc(kind==="task"?(x.owner||"负责人待定")+(x.dueDate?' · '+x.dueDate:''):(x.level||"normal")+'级风险')+'</small></span><button class="ub-btn ghost" data-pm-item="'+kind+'" data-id="'+esc(x.id)+'" data-status="'+(kind==="task"?'done':'mitigated')+'">'+(kind==="task"?'完成':'已缓释')+'</button></div>').join('');
    return '<div class="pm-ops"><div class="pm-ops-title"><b>Investment OS · 阶段4—6执行台</b><span>会议行动化 / Scenario Lab / 生产验收</span></div>'
      +'<details class="pm-ops-block" open><summary><b>① 会议 → 决策 / 任务 / 风险</b><i>待办 '+tasks.filter(x=>x.status==="open").length+' · 风险 '+risks.filter(x=>x.status==="open").length+'</i></summary><div class="pm-ops-body"><div class="pm-meeting-form"><input id="pmMeetingTitle" placeholder="会议名称"><textarea id="pmMeetingText" placeholder="粘贴会议纪要；系统先抽取候选，人工确认后才进入正式台账"></textarea><button class="ub-btn" data-pm-extract="1">抽取候选</button></div>'
      +(candidate?'<div class="pm-candidate"><b>待确认：'+esc(candidate.title)+'</b><span>决定 '+Number(candidate.extraction?.summary?.decisions||0)+' · 任务 '+Number(candidate.extraction?.summary?.tasks||0)+' · 风险 '+Number(candidate.extraction?.summary?.risks||0)+'</span><button class="ub-btn" data-pm-confirm-meeting="'+esc(candidate.id)+'">人工确认并入台账</button></div>':'')
      +'<div class="pm-two"><section><h4>任务台账</h4>'+(rows(tasks.filter(x=>x.status!=="done"),"task")||'<p>暂无待办任务</p>')+'</section><section><h4>风险台账</h4>'+(rows(risks.filter(x=>!['mitigated','closed'].includes(x.status)),"risk")||'<p>暂无开放风险</p>')+'</section></div></div></details>'
      +'<details class="pm-ops-block"><summary><b>② Scenario Lab 与投资决策包</b><i>'+scenarios.length+' 个情景 · '+packages.length+' 个决策包</i></summary><div class="pm-ops-body"><div class="pm-inline"><select id="pmScenarioKind"><option value="baseline">基准情景</option><option value="optimistic">乐观情景</option><option value="prudent">审慎情景</option><option value="custom">自定义情景</option></select><input id="pmScenarioName" placeholder="情景名称（可选）"><button class="ub-btn" data-pm-scenario="1">从当前白箱快照保存</button></div>'
      +(scenarios.length?'<div class="pm-scenario-grid">'+scenarios.map(s=>'<div class="pm-scenario"><b>'+esc(s.name)+'</b><span>'+esc(s.kind)+' · '+esc(s.calcSnapshotId)+'</span>'+Object.entries(s.metrics||{}).slice(0,4).map(([k,v])=>'<small>'+esc(k)+' '+esc(v)+'</small>').join('')+'</div>').join('')+'</div><div class="pm-compare">'+cmp.columns.filter(c=>c.values.some(v=>v!==null)).slice(0,6).map(c=>'<div><b>'+esc(c.label)+'</b>'+c.values.map(v=>'<span>'+esc(v==null?'—':v)+' '+esc(c.unit)+'</span>').join('')+'</div>').join('')+'</div><div class="pm-inline"><select id="pmPackageScenario">'+scenarios.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+'</option>').join('')+'</select><button class="ub-btn" data-pm-package="1">审计并形成投资决策包</button></div>':'<p class="pm-hint">先完成财务测算并形成快照，再保存基准/乐观/审慎情景；关键数字只读取白箱引擎。</p>')
      +(packages.length?'<div class="pm-package-list">'+packages.slice(0,5).map(x=>'<span class="'+(x.status==="ready"?'ok':'bad')+'"><b>'+esc(x.title)+'</b> '+(x.status==="ready"?'可提交':'阻断 '+Number(x.audit?.blockers?.length||0)+'项')+'</span>').join('')+'</div>':'')+'</div></details>'
      +'<details class="pm-ops-block"><summary><b>③ 真实项目验证与生产化</b><i>'+evaluations.length+' 条验收 · '+optimizations.length+' 条优化</i></summary><div class="pm-ops-body"><div class="pm-gates">'+((ops.production&&ops.production.checks)||[]).map(x=>'<span class="'+(x.ok?'ok':'bad')+'">'+(x.ok?'✓ ':'○ ')+esc(x.label)+'</span>').join('')+'</div><div class="pm-two"><section><h4>黄金项目 / SLO验收</h4><div class="pm-inline"><button class="ub-btn" data-pm-golden="1">记录当前黄金项目评测</button><button class="ub-btn ghost" data-pm-slo="1">记录50人SLO实测</button></div>'+evaluations.slice(0,5).map(x=>'<div class="pm-eval"><b>'+esc(x.type)+'</b><span>'+esc(x.status)+'</span></div>').join('')+'</section><section><h4>Optimization Ledger</h4><div class="pm-opt-form"><input id="pmOptTitle" placeholder="优化事项"><input id="pmOptEvidence" placeholder="证据/测试编号"><input id="pmOptBenefit" placeholder="实际收益"><button class="ub-btn" data-pm-opt="1">记录优化</button></div>'+optimizations.slice(0,5).map(x=>'<div class="pm-eval"><b>'+esc(x.title)+'</b><span>'+esc(x.actualBenefit||x.status)+'</span></div>').join('')+'</section></div><p class="pm-hint">这里记录真实结果，不自动伪造5—20个黄金项目或50人压测数据；达到门槛后才允许启动Portfolio Brain。</p></div></details></div>';
  }
  function detail(p,currentId,brain,error,ops,opsError){
    if(!p)return '<div class="pm-detail-empty"><b>选择一个项目</b><span>查看项目进度、成果版本、资料状态和恢复入口。</span></div>';
    const current=p.id===currentId,hs=health(p),acts=(p.activity||[]);
    return '<div class="pm-detail-head"><div><span class="pm-eyebrow">PROJECT WORKSPACE</span><h2>'+esc(p.name||"未命名项目")+'</h2><p>'+esc(displayType(p.type))+' · '+esc(p.location||"位置待补")+' · 负责人 '+esc(p.owner||"待指定")+'</p></div><i class="pm-status s-'+esc(p.status)+'">'+esc(PM_STATUS[p.status]||p.stage)+'</i></div>'
      +'<div class="pm-phase"><div><b>当前阶段：'+esc(p.stage)+'</b><span>'+Number(p.progress||0)+'%</span></div><i><em style="width:'+Number(p.progress||0)+'%"></em></i></div>'
      +'<div class="pm-kpis"><div><b>'+p.generated+'/'+p.sections+'</b><span>已生成小节</span></div><div><b>'+p.materials+'</b><span>项目资料</span></div><div><b>V'+p.calcVersions+'</b><span>测算快照</span></div><div><b>V'+p.reportVersions+'</b><span>报告版本</span></div></div>'
      +brainHtml(brain,error)
      +opsHtml(ops,opsError)
      +'<div class="pm-detail-section"><h3>项目健康状态</h3><div class="pm-health">'+(hs.length?hs.map(x=>'<span class="warn">! '+esc(x)+'</span>').join(''):'<span class="ok">✓ 当前未发现明显保存或同步风险</span>')+(p.locked?'<span>🔒 '+p.locked+'节人工锁定</span>':'')+'</div></div>'
      +'<div class="pm-detail-section"><h3>项目状态与标签</h3><div class="pm-meta-edit"><select id="pmStatus">'+Object.entries(PM_STATUS).map(([k,v])=>'<option value="'+k+'" '+(p.status===k?'selected':'')+'>'+v+'</option>').join('')+'</select><input id="pmTags" value="'+esc((p.tags||[]).join('、'))+'" placeholder="标签，用顿号分隔"><button class="ub-btn" data-pm-meta="'+esc(p.id)+'">保存</button></div></div>'
      +'<div class="pm-detail-section"><h3>最近活动</h3><div class="pm-activity">'+(acts.length?acts.map(a=>'<div><i></i><span><b>'+esc(a.text||"项目更新")+'</b><small>'+esc(when(a.at))+(a.by?' · '+esc(a.by):'')+'</small></span></div>').join(''):'<p>尚无活动记录；后续归档、恢复、复制和状态修改会记录在这里。</p>')+'</div></div>'
      +'<div class="pm-detail-actions"><button class="btn" data-pm-open="'+esc(p.id)+'">'+(current?'返回当前项目':'打开并继续')+'</button><button class="btn ghost" data-pm-copy="'+esc(p.id)+'">复制项目</button>'
      +(p.archived?'<button class="btn ghost" data-pm-archive="'+esc(p.id)+'" data-value="0">恢复项目</button><button class="btn danger-lite" data-pm-purge="'+esc(p.id)+'">彻底删除</button>':'<button class="btn ghost" data-pm-archive="'+esc(p.id)+'" data-value="1">归档项目</button>')+'</div>';
  }
  async function open(options){
    options=options||{};document.getElementById("projPanel")?.remove();
    document.body.insertAdjacentHTML("beforeend",'<div id="projPanel" class="proj-overlay"><section class="proj-panel pm-shell"><header class="pm-head"><div><span>INVESTMENT · LIFECYCLE</span><b>投资全周期项目驾驶舱</b><small>从项目发现、投资决策到投后管理与退出复盘统一管理</small></div><button class="pp-close" id="ppClose" aria-label="关闭">×</button></header><div class="pm-toolbar"><label>⌕<input id="pmSearch" placeholder="搜索项目、区域、负责人或标签"></label><select id="pmSort"><option value="updated">最近更新</option><option value="name">项目名称</option><option value="progress">完成进度</option></select><button class="pm-tab active" data-pm-tab="active">进行中</button><button class="pm-tab" data-pm-tab="archived">归档</button><button class="btn" id="pmNew">＋ 新建项目</button></div><main class="pm-main"><aside id="pmList"><div class="pm-loading">正在读取项目索引…</div></aside><article id="pmDetail"></article></main></section></div>');
    const overlay=document.getElementById("projPanel"),listEl=document.getElementById("pmList"),detailEl=document.getElementById("pmDetail");
    let projects=[],selected=null,tab="active",query="",sort="updated",brainCache={},brainErrors={},brainLoading=new Set(),opsCache={},opsErrors={},opsLoading=new Set();
    const headers=()=>typeof options.headers==="function"?options.headers():{};
    async function api(body){const r=await fetch("/api/projects",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"操作失败");return d;}
    async function brainApi(body){const r=await fetch("/api/projectbrain",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目大脑操作失败");return d;}
    async function opsApi(body){const r=await fetch("/api/investmentops",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Investment OS操作失败");return d;}
    async function loadBrain(id){if(!id||brainLoading.has(id))return;brainLoading.add(id);delete brainErrors[id];try{const r=await fetch("/api/projectbrain?projectId="+encodeURIComponent(id),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目大脑加载失败");brainCache[id]=d.context;}catch(e){brainErrors[id]=e.message;}finally{brainLoading.delete(id);if(selected===id)render();}}
    async function loadOps(id){if(!id||opsLoading.has(id))return;opsLoading.add(id);delete opsErrors[id];try{const r=await fetch("/api/investmentops?projectId="+encodeURIComponent(id),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"执行台加载失败");opsCache[id]=d.ops;}catch(e){opsErrors[id]=e.message;}finally{opsLoading.delete(id);if(selected===id)render();}}
    function visible(){
      const arr=projects.filter(p=>(tab==="archived")===!!p.archived&&matches(p,query));
      return arr.sort(sort==="name"?(a,b)=>String(a.name).localeCompare(String(b.name),"zh-CN"):sort==="progress"?(a,b)=>b.progress-a.progress:(a,b)=>b.updated_at-a.updated_at);
    }
    function render(){const rows=visible();if(!rows.some(p=>p.id===selected))selected=rows[0]?.id||null;listEl.innerHTML='<div class="pm-list-summary"><b>'+rows.length+' 个项目</b><span>'+(tab==="archived"?'可恢复或彻底删除':'点击项目查看工作区')+'</span></div>'+(rows.length?rows.map(p=>projectCard(p,p.id===selected)).join(''):'<div class="pm-detail-empty"><b>这里还没有项目</b><span>'+(tab==="archived"?'归档项目会安全地保存在这里。':'新建项目后，系统会自动保存并记录进度。')+'</span></div>');detailEl.innerHTML=detail(projects.find(p=>p.id===selected),options.currentId&&options.currentId(),brainCache[selected],brainErrors[selected],opsCache[selected],opsErrors[selected]);bind();if(selected&&!brainCache[selected]&&!brainErrors[selected])loadBrain(selected);if(selected&&!opsCache[selected]&&!opsErrors[selected])loadOps(selected);}
    function bind(){
      listEl.querySelectorAll('[data-pm-select]').forEach(b=>b.onclick=()=>{selected=b.dataset.pmSelect;render();});
      detailEl.querySelectorAll('[data-pm-stage]').forEach(b=>b.onclick=async()=>{const current=brainCache[selected]&&brainCache[selected].lifecycle&&brainCache[selected].lifecycle.current;if(b.dataset.pmStage===current)return;const reason=prompt("切换项目阶段的原因（将写入项目时间线）","");if(reason===null)return;try{await brainApi({action:"setStage",projectId:selected,stageKey:b.dataset.pmStage,reason});delete brainCache[selected];await loadBrain(selected);await load();}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-decision]').forEach(b=>b.onclick=async()=>{const topic=document.getElementById("pmDecisionTopic")?.value.trim(),owner=document.getElementById("pmDecisionOwner")?.value||"";if(!topic){alert("请先填写决策议题");return;}try{await brainApi({action:"createDecision",projectId:selected,decision:{topic,owner,stageKey:brainCache[selected]?.lifecycle?.current||"feasibility"}});delete brainCache[selected];await loadBrain(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-extract]').forEach(b=>b.onclick=async()=>{const title=document.getElementById("pmMeetingTitle")?.value.trim(),content=document.getElementById("pmMeetingText")?.value.trim();if(!content){alert("请先粘贴会议纪要");return;}b.disabled=true;try{const d=await opsApi({action:"extractMeeting",projectId:selected,title,content});alert("已形成候选：决定 "+d.extraction.summary.decisions+" 项、任务 "+d.extraction.summary.tasks+" 项、风险 "+d.extraction.summary.risks+" 项。确认前不会写入正式台账。");delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}finally{b.disabled=false;}});
      detailEl.querySelectorAll('[data-pm-confirm-meeting]').forEach(b=>b.onclick=async()=>{if(!confirm("确认后，候选决定、任务和风险将进入正式台账。是否继续？"))return;try{const d=await opsApi({action:"confirmMeeting",projectId:selected,meetingId:b.dataset.pmConfirmMeeting});alert("已入台账：决定 "+d.decisionCount+" 项、任务 "+d.taskCount+" 项、风险 "+d.riskCount+" 项");delete opsCache[selected];delete brainCache[selected];await Promise.all([loadOps(selected),loadBrain(selected)]);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-item]').forEach(b=>b.onclick=async()=>{try{await opsApi({action:"updateItem",projectId:selected,type:b.dataset.pmItem,id:b.dataset.id,status:b.dataset.status});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-scenario]').forEach(b=>b.onclick=async()=>{const kind=document.getElementById("pmScenarioKind")?.value||"baseline",name=document.getElementById("pmScenarioName")?.value.trim();try{await opsApi({action:"saveScenario",projectId:selected,scenario:{kind,name}});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-package]').forEach(b=>b.onclick=async()=>{const scenarioId=document.getElementById("pmPackageScenario")?.value,evidenceIds=(brainCache[selected]?.artifacts||[]).map(x=>x.id).filter(Boolean);try{const d=await opsApi({action:"createDecisionPackage",projectId:selected,scenarioId,evidenceIds,title:"投资决策包"});alert(d.package.audit.passed?"投资决策包已通过提交前审计":"决策包已生成但被阻断：\n- "+d.package.audit.blockers.join("\n- "));delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-golden]').forEach(b=>b.onclick=async()=>{const numericErrors=prompt("关键数字错误数（必须如实填写）","0");if(numericErrors===null)return;const evidenceCoverage=prompt("证据覆盖率（0—100）","80");if(evidenceCoverage===null)return;const manualMinutes=prompt("人工耗时（分钟）","");if(manualMinutes===null)return;try{await opsApi({action:"saveEvaluation",projectId:selected,type:"golden_project",status:Number(numericErrors)===0?"recorded":"failed",result:{numericErrors:Number(numericErrors)||0,evidenceCoverage:Number(evidenceCoverage)||0,manualMinutes:Number(manualMinutes)||0,recordedAt:Date.now()}});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-slo]').forEach(b=>b.onclick=async()=>{const concurrency=prompt("实测并发人数（目标50）","50");if(concurrency===null)return;const p95Ms=prompt("核心路径P95耗时（毫秒）","5000");if(p95Ms===null)return;const successRate=prompt("成功率（0—100）","99");if(successRate===null)return;const recoveryRate=prompt("失败恢复率（0—100）","95");if(recoveryRate===null)return;const result={concurrency:Number(concurrency)||0,p95Ms:Number(p95Ms)||0,successRate:(Number(successRate)||0)/100,recoveryRate:(Number(recoveryRate)||0)/100,passed:Number(concurrency)>=50&&Number(p95Ms)<=5000&&Number(successRate)>=99&&Number(recoveryRate)>=95};try{await opsApi({action:"saveEvaluation",projectId:selected,type:"slo_load",status:result.passed?"passed":"failed",result});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-opt]').forEach(b=>b.onclick=async()=>{const title=document.getElementById("pmOptTitle")?.value.trim(),evidence=document.getElementById("pmOptEvidence")?.value.trim(),actualBenefit=document.getElementById("pmOptBenefit")?.value.trim();if(!title){alert("请填写优化事项");return;}try{await opsApi({action:"saveOptimization",projectId:selected,title,evidence,actualBenefit,status:actualBenefit?"verified":"candidate"});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-open]').forEach(b=>b.onclick=()=>options.openProject&&options.openProject(b.dataset.pmOpen));
      detailEl.querySelectorAll('[data-pm-copy]').forEach(b=>b.onclick=async()=>{const src=projects.find(p=>p.id===b.dataset.pmCopy),name=prompt("副本名称",(src?.name||"未命名项目")+"（副本）");if(!name)return;await api({action:"duplicate",sourceId:b.dataset.pmCopy,id:options.genId(),name});await load();});
      detailEl.querySelectorAll('[data-pm-archive]').forEach(b=>b.onclick=async()=>{const archived=b.dataset.value==="1";if(!confirm(archived?"归档后不会出现在进行中列表，可随时恢复。是否继续？":"恢复该项目到进行中列表？"))return;await api({action:"setArchived",id:b.dataset.pmArchive,archived});if(archived&&options.currentId&&b.dataset.pmArchive===options.currentId())options.newProject&&options.newProject(true);await load();});
      detailEl.querySelectorAll('[data-pm-purge]').forEach(b=>b.onclick=async()=>{const p=projects.find(x=>x.id===b.dataset.pmPurge);if(prompt("彻底删除不可恢复。请输入项目名称确认：")!==(p?.name||""))return;const r=await fetch("/api/projects?id="+encodeURIComponent(b.dataset.pmPurge),{method:"DELETE",headers:headers()});if(!r.ok)throw new Error("删除失败");await load();});
      detailEl.querySelectorAll('[data-pm-meta]').forEach(b=>b.onclick=async()=>{const tags=document.getElementById("pmTags").value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean),status=document.getElementById("pmStatus").value,saved=await api({action:"updateMeta",id:b.dataset.pmMeta,status,tags});if(options.updateCurrentMeta&&b.dataset.pmMeta===options.currentId())options.updateCurrentMeta({status,tags},saved.updatedAt);await load();});
    }
    async function load(){try{const r=await fetch("/api/projects",{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"加载失败");projects=d.list||[];render();}catch(e){listEl.innerHTML='<div class="pm-detail-empty"><b>项目索引加载失败</b><span>'+esc(e.message)+'</span></div>';}}
    overlay.onclick=e=>{if(e.target===overlay)overlay.remove();};document.getElementById("ppClose").onclick=()=>overlay.remove();
    document.getElementById("pmSearch").oninput=e=>{query=e.target.value;render();};document.getElementById("pmSort").onchange=e=>{sort=e.target.value;render();};
    document.querySelectorAll('[data-pm-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.pmTab;document.querySelectorAll('[data-pm-tab]').forEach(x=>x.classList.toggle("active",x===b));render();});
    document.getElementById("pmNew").onclick=()=>{if(confirm("新建项目后，当前项目仍会自动保存。是否继续？")){overlay.remove();options.newProject&&options.newProject();}};
    await load();
  }
  root.ProjectManager={open,health,matches,displayType};
  if(typeof module==="object"&&module.exports)module.exports={health,matches,displayType};
})(typeof window!=="undefined"?window:globalThis);
