/* 投资全周期项目驾驶舱：统一管理项目索引、Project Brain、阶段、恢复入口和元数据。 */
(function(root){
  "use strict";
  const PM_STATUS={draft:"草稿",collecting:"资料准备",calculated:"测算完成",generating:"生成中",review:"复核签发",signed:"已签发",paused:"暂缓"};
  const PM_TYPE={rent:"出租类",sale:"出售类",gaibao:"非居改保","保障性租赁住房":"出租类","配售型保障性住房":"出售类"};
  const esc=value=>String(value==null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const when=value=>{const d=new Date(Number(value)||value);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("zh-CN")+" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0");};
  function displayType(value){return PM_TYPE[value]||value||"类型待确认";}
  function health(p){
    const issues=[];
    if(!p.location)issues.push("位置待补");
    if(!p.calcVersions)issues.push("未形成测算快照");
    if(p.stale)issues.push(p.stale+"节待同步");
    if(!p.materials)issues.push("尚无项目资料");
    return issues.slice(0,3);
  }
  function matches(p,q){q=String(q||"").trim().toLowerCase();if(!q)return true;return [p.name,p.location,p.owner,p.type,p.stage].concat(p.tags||[]).join(" ").toLowerCase().includes(q);}
  function projectCard(p,active,intelligence){
    const hs=health(p),real=intelligence&&intelligence.progress,hasReal=!!(real&&real.configured),progress=hasReal?Number(real.value)||0:0;
    return '<button type="button" class="pm-project '+(active?'active':'')+'" data-pm-select="'+esc(p.id)+'">'
      +'<span class="pm-project-primary"><b>'+esc(p.name||"未命名项目")+'</b><small>'+esc(p.location||"位置待补")+'</small></span>'
      +'<span class="pm-project-type">'+esc(displayType(p.type))+'</span>'
      +'<span class="pm-project-stage"><i class="pm-status s-'+esc(p.status)+'">'+esc(PM_STATUS[p.status]||p.stage||"进行中")+'</i><small>'+esc(p.stage||"草稿")+'</small></span>'
      +'<span class="pm-project-progress"><b>'+(hasReal?progress+'%':'—')+'</b><i class="pm-progress '+(hasReal?'':'pending')+'"><em style="width:'+Math.max(0,Math.min(100,progress))+'%"></em></i></span>'
      +'<span class="pm-project-time">'+esc(when(p.updated_at))+'</span>'
      +(hs.length?'<span class="pm-warnings">'+hs.map(x=>'<i>'+esc(x)+'</i>').join('')+'</span>':'')+'</button>';
  }
  function intelligenceHtml(model,error){
    if(error)return '<div class="pm-intelligence"><div class="pm-intel-head"><b>Project Intelligence · 项目总览</b><span class="bad">加载失败</span></div><p>'+esc(error)+'</p></div>';
    if(!model)return '<div class="pm-intelligence"><div class="pm-intel-head"><b>Project Intelligence · 项目总览</b><span>正在建立统一只读模型…</span></div></div>';
    const progress=model.progress||{},gate=model.gate,k=model.kpis||{},health=model.dataHealth||{},milestones=model.milestones||[],deliverables=model.deliverables||[],canEdit=!!(model.contextContract&&model.contextContract.permissions&&model.contextContract.permissions.edit),fmt=v=>v==null||v===""?'—':esc(v),statusLabel={not_started:'待开始',in_progress:'进行中',blocked:'受阻',done:'已完成',cancelled:'已取消',passed:'已通过',waived:'已豁免'};
    return '<div class="pm-intelligence"><div class="pm-intel-head"><div><b>Project Intelligence · 项目总览</b><small>Read Model V1 · '+esc(model.contextContract?.permissions?.role||'VIEWER')+'</small></div><span>'+(progress.configured?'真实进度 '+Number(progress.value||0)+'%':'尚未配置真实进度')+'</span></div>'
      +'<div class="pm-intel-kpis"><div><b>'+fmt(k.totalInvestment)+'</b><span>总投资（白箱结果）</span></div><div><b>'+fmt(k.irr)+'</b><span>IRR（白箱结果）</span></div><div><b>'+Number(health.score||0)+'</b><span>数据健康分</span></div><div><b>'+Number(k.openRiskCount||0)+'</b><span>开放风险</span></div><div><b>'+Number(k.overdueTaskCount||0)+'</b><span>逾期任务</span></div></div>'
      +'<div class="pm-intel-gate"><span>当前 Gate</span><b>'+esc(gate?.name||'尚未设置')+'</b><i class="'+(gate?.status==='blocked'?'bad':'')+'">'+esc(statusLabel[gate?.status]||'待配置')+'</i>'+(gate?.blockReason?'<small>'+esc(gate.blockReason)+'</small>':'')+'</div>'
      +'<div class="pm-two pm-intel-grid"><section><h4>近期里程碑</h4>'+(milestones.length?milestones.slice(0,6).map(x=>'<div class="pm-intel-row"><span><b>'+esc(x.name)+'</b><small>'+esc(x.owner||'负责人待定')+(x.plannedDate?' · '+esc(x.plannedDate):'')+'</small></span><i>'+Number(x.progress||0)+'% · '+esc(statusLabel[x.status]||x.status)+'</i></div>').join(''):'<p>尚未配置里程碑；生命周期不会再冒充实际完成率。</p>')+'</section><section><h4>阶段成果</h4>'+(deliverables.length?deliverables.slice(0,6).map(x=>'<div class="pm-intel-row"><span><b>'+esc(x.name)+'</b><small>'+(x.required?'必需成果':'参考成果')+(x.dueDate?' · '+esc(x.dueDate):'')+'</small></span><i>'+esc(statusLabel[x.status]||x.status)+'</i></div>').join(''):'<p>尚未配置阶段成果。</p>')+'</section></div>'
      +(canEdit?'<div class="pm-intel-actions"><button class="ub-btn ghost" data-pi-gate="1">＋ 阶段门</button><button class="ub-btn ghost" data-pi-milestone="1">＋ 里程碑</button><button class="ub-btn ghost" data-pi-deliverable="1">＋ 阶段成果</button></div>':'')+'</div>';
  }
  function brainHtml(brain,error){
    if(error)return '<div class="pm-brain"><div class="pm-brain-head"><b>Investment OS · 项目大脑</b><span>加载失败</span></div><div class="pm-brain-loading">'+esc(error)+'</div></div>';
    if(!brain)return '<div class="pm-brain"><div class="pm-brain-head"><b>Investment OS · 项目大脑</b><span>正在统一项目上下文…</span></div><div class="pm-brain-loading">正在汇总事实、指标、成果、决策与生命周期</div></div>';
    const s=brain.summary||{},life=brain.lifecycle||{},facts=(brain.facts||[]).slice(0,6),decisions=(brain.decisions||[]).slice(0,5),typeName={FACT:"事实",ASSUMPTION:"假设",CALCULATION:"计算",AI_JUDGEMENT:"AI判断"};
    return '<div class="pm-brain"><div class="pm-brain-head"><b>Investment OS · 项目大脑</b><span>当前阶段：'+esc(life.label||"待确认")+' · 旧项目零迁移兼容</span></div>'
      +'<div class="pm-lifecycle">'+(life.stages||[]).map((x,i)=>'<button class="pm-stage '+(x.key===life.current?'active':'')+'" data-pm-stage="'+esc(x.key)+'"><b>'+(i+1)+'. '+esc(x.label)+'</b>'+esc((x.deliverables||[]).slice(0,1).join(''))+'</button>').join('')+'</div>'
      +'<div class="pm-brain-kpis"><div><b>'+Number(s.confirmedFacts||0)+'/'+Number(s.facts||0)+'</b><span>已确认事实</span></div><div><b>'+Number(s.metrics||0)+'</b><span>结构化指标</span></div><div><b>'+Number(s.artifacts||0)+'</b><span>项目成果</span></div><div><b>'+Number(s.decisions||0)+'</b><span>决策事项</span></div><div><b>'+Number(s.changes||0)+'</b><span>影响变更集</span></div></div>'
      +'<div class="pm-brain-grid"><section class="pm-brain-box"><h4>统一项目事实（事实 / 假设 / 计算 / AI判断）</h4>'+(facts.length?facts.map(x=>'<div class="pm-fact-row"><span>'+esc(x.label||x.factKey)+'</span><i>'+esc(typeName[x.factType]||x.factType)+' · '+esc(x.status==="confirmed"?"已确认":"待确认")+'</i></div>').join(''):'<div class="pm-brain-loading">尚无结构化事实，现有项目内容会按访问逐步建立索引。</div>')+'</section>'
      +'<section class="pm-brain-box"><h4>决策台账</h4>'+(decisions.length?decisions.map(x=>'<div class="pm-decision-row"><b>'+esc(x.topic)+'</b><span>'+esc(x.status||"candidate")+'</span></div>').join(''):'<div class="pm-brain-loading">尚无决策事项；可从测算、审查或会议结论创建。</div>')+'<div class="pm-brain-form"><input id="pmDecisionTopic" placeholder="新增决策议题"><select id="pmDecisionOwner"><option value="">负责人待定</option><option>投资部</option><option>项目负责人</option></select><button class="ub-btn" data-pm-decision="1">新增候选</button></div></section></div></div>';
  }
  function opsHtml(ops,error){
    if(error)return '<div class="pm-ops"><div class="pm-ops-title"><b>行动 · 情景 · 生产验收</b><span class="bad">加载失败</span></div><p>'+esc(error)+'</p></div>';
    if(!ops)return '<div class="pm-ops"><div class="pm-ops-title"><b>行动 · 情景 · 生产验收</b><span>正在加载…</span></div></div>';
    const meetings=ops.meetings||[],tasks=ops.tasks||[],risks=ops.risks||[],scenarios=ops.scenarios||[],packages=ops.packages||[],evaluations=ops.evaluations||[],optimizations=ops.optimizations||[],candidate=meetings.find(x=>x.status==="candidate"),cmp=(root.InvestmentOps&&root.InvestmentOps.compareScenarios(scenarios))||{columns:[]};
    const rows=(items,kind)=>items.slice(0,6).map(x=>'<div class="pm-action-row"><span><b>'+esc(x.title)+'</b><small>'+esc(kind==="task"?(x.owner||"负责人待定")+(x.dueDate?' · '+x.dueDate:''):(x.level||"normal")+'级风险')+'</small></span><button class="ub-btn ghost" data-pm-item="'+kind+'" data-id="'+esc(x.id)+'" data-status="'+(kind==="task"?'done':'mitigated')+'">'+(kind==="task"?'完成':'已缓释')+'</button></div>').join('');
    return '<div class="pm-ops"><div class="pm-ops-title"><b>Investment OS · 阶段4—6执行台</b><span>会议行动化 / Scenario Lab / 生产验收</span></div>'
      +'<details class="pm-ops-block" open><summary><b>① 会议 → 决策 / 任务 / 风险</b><i>待办 '+tasks.filter(x=>x.status==="open").length+' · 风险 '+risks.filter(x=>x.status==="open").length+'</i></summary><div class="pm-ops-body"><div class="pm-meeting-form"><input id="pmMeetingTitle" placeholder="会议名称"><textarea id="pmMeetingText" placeholder="粘贴会议纪要；系统先抽取候选，人工确认后才进入正式台账"></textarea><button class="ub-btn" data-pm-extract="1">抽取候选</button></div>'
      +(candidate?'<div class="pm-candidate"><b>待确认：'+esc(candidate.title)+'</b><span>决定 '+Number(candidate.extraction?.summary?.decisions||0)+' · 任务 '+Number(candidate.extraction?.summary?.tasks||0)+' · 风险 '+Number(candidate.extraction?.summary?.risks||0)+'</span><button class="ub-btn" data-pm-confirm-meeting="'+esc(candidate.id)+'">人工确认并入台账</button></div>':'')
      +'<div class="pm-two"><section><h4>任务台账</h4>'+(rows(tasks.filter(x=>x.status!=="done"),"task")||'<p>暂无待办任务</p>')+'</section><section><h4>风险台账</h4>'+(rows(risks.filter(x=>!['mitigated','closed'].includes(x.status)),"risk")||'<p>暂无开放风险</p>')+'</section></div></div></details>'
      +'<details class="pm-ops-block"><summary><b>② Scenario Lab 与投资决策包</b><i>'+scenarios.length+' 个情景 · '+packages.length+' 个决策包</i></summary><div class="pm-ops-body"><div class="pm-inline"><select id="pmScenarioKind"><option value="baseline">基准情景</option><option value="optimistic">乐观情景</option><option value="prudent">审慎情景</option><option value="custom">自定义情景</option></select><input id="pmScenarioName" placeholder="情景名称（可选）"><button class="ub-btn" data-pm-scenario="1">从当前白箱快照保存</button></div>'
      +(scenarios.length?'<div class="pm-scenario-grid">'+scenarios.map(s=>'<div class="pm-scenario"><b>'+esc(s.name)+'</b><span>'+esc(s.kind)+' · '+esc(s.calcSnapshotId)+'</span>'+Object.entries(s.metrics||{}).slice(0,4).map(([k,v])=>'<small>'+esc(k)+' '+esc(v)+'</small>').join('')+'</div>').join('')+'</div><div class="pm-compare">'+cmp.columns.filter(c=>c.values.some(v=>v!==null)).slice(0,6).map(c=>'<div><b>'+esc(c.label)+'</b>'+c.values.map(v=>'<span>'+esc(v==null?'—':v)+' '+esc(c.unit)+'</span>').join('')+'</div>').join('')+'</div><div class="pm-inline"><select id="pmPackageScenario">'+scenarios.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+'</option>').join('')+'</select><button class="ub-btn" data-pm-package="1">审计并形成投资决策包</button></div>':'<p class="pm-hint">先完成财务测算并形成快照，再保存基准/乐观/审慎情景；关键数字只读取白箱引擎。</p>')
      +(packages.length?'<div class="pm-package-list">'+packages.slice(0,5).map(x=>'<span class="'+(x.status==="ready"?'ok':'bad')+'"><b>'+esc(x.title)+'</b> '+(x.status==="ready"?'可提交':'阻断 '+Number(x.audit?.blockers?.length||0)+'项')+'</span>').join('')+'</div>':'')+'</div></details>'
      +'<details class="pm-ops-block"><summary><b>③ 真实项目验证与生产化</b><i>'+evaluations.length+' 条验收 · '+optimizations.length+' 条优化</i></summary><div class="pm-ops-body"><div class="pm-gates">'+((ops.production&&ops.production.checks)||[]).map(x=>'<span class="'+(x.ok?'ok':'bad')+'">'+(x.ok?'✓ ':'○ ')+esc(x.label)+'</span>').join('')+'</div><div class="pm-two"><section><h4>黄金项目 / SLO验收</h4><div class="pm-inline"><button class="ub-btn" data-pm-golden="1">记录当前黄金项目评测</button><button class="ub-btn ghost" data-pm-slo="1">记录50人SLO实测</button></div>'+evaluations.slice(0,5).map(x=>'<div class="pm-eval"><b>'+esc(x.type)+'</b><span>'+esc(x.status)+'</span></div>').join('')+'</section><section><h4>Optimization Ledger</h4><div class="pm-opt-form"><input id="pmOptTitle" placeholder="优化事项"><input id="pmOptEvidence" placeholder="证据/测试编号"><input id="pmOptBenefit" placeholder="实际收益"><button class="ub-btn" data-pm-opt="1">记录优化</button></div>'+optimizations.slice(0,5).map(x=>'<div class="pm-eval"><b>'+esc(x.title)+'</b><span>'+esc(x.actualBenefit||x.status)+'</span></div>').join('')+'</section></div><p class="pm-hint">这里记录真实结果，不自动伪造5—20个黄金项目或50人压测数据；达到门槛后才允许启动Portfolio Brain。</p></div></details></div>';
  }
  function detail(p,currentId,brain,error,ops,opsError,intelligence,intelligenceError,view,workspace){
    if(!p)return '<div class="pm-detail-empty"><b>选择一个项目</b><span>查看项目进度、成果版本、资料状态和恢复入口。</span></div>';
    view=view||"overview";const current=p.id===currentId,hs=health(p),acts=(p.activity||[]),nav=root.ProjectWorkspaceUI?root.ProjectWorkspaceUI.nav(p.id,view):"",workspaceHtml=view==="overview"?"":(root.ProjectWorkspaceUI?root.ProjectWorkspaceUI.render(view,workspace):'<div class="pm-detail-empty">工作区模块未加载</div>');
    const head='<div class="pm-detail-head"><div><span class="pm-eyebrow">PROJECT WORKSPACE</span><h2>'+esc(p.name||"未命名项目")+'</h2><p>'+esc(displayType(p.type))+' · '+esc(p.location||"位置待补")+' · 负责人 '+esc(p.owner||"待指定")+'</p></div><i class="pm-status s-'+esc(p.status)+'">'+esc(PM_STATUS[p.status]||p.stage)+'</i></div>'+nav;
    if(view!=="overview")return head+workspaceHtml;
    return head
      +'<div class="pm-phase"><div><b>生命周期：'+esc(intelligence?.stage?.label||p.stage)+'</b><span>'+(intelligence?.progress?.configured?'项目真实进度 '+Number(intelligence.progress.value||0)+'%':'项目真实进度待配置')+'</span></div><i><em style="width:'+(intelligence?.progress?.configured?Number(intelligence.progress.value||0):0)+'%"></em></i></div>'
      +'<div class="pm-kpis"><div><b>'+p.generated+'/'+p.sections+'</b><span>已生成小节</span></div><div><b>'+p.materials+'</b><span>项目资料</span></div><div><b>V'+p.calcVersions+'</b><span>测算快照</span></div><div><b>V'+p.reportVersions+'</b><span>报告版本</span></div></div>'
      +intelligenceHtml(intelligence,intelligenceError)
      +brainHtml(brain,error)
      +opsHtml(ops,opsError)
      +'<div class="pm-detail-section"><h3>项目健康状态</h3><div class="pm-health">'+(hs.length?hs.map(x=>'<span class="warn">! '+esc(x)+'</span>').join(''):'<span class="ok">✓ 当前未发现明显保存或同步风险</span>')+(p.locked?'<span>🔒 '+p.locked+'节人工锁定</span>':'')+'</div></div>'
      +'<div class="pm-detail-section"><h3>项目状态与标签</h3><div class="pm-meta-edit"><select id="pmStatus">'+Object.entries(PM_STATUS).map(([k,v])=>'<option value="'+k+'" '+(p.status===k?'selected':'')+'>'+v+'</option>').join('')+'</select><input id="pmTags" value="'+esc((p.tags||[]).join('、'))+'" placeholder="标签，用顿号分隔"><button class="ub-btn" data-pm-meta="'+esc(p.id)+'">保存</button></div></div>'
      +'<div class="pm-detail-section"><h3>最近活动</h3><div class="pm-activity">'+(acts.length?acts.map(a=>'<div><i></i><span><b>'+esc(a.text||"项目更新")+'</b><small>'+esc(when(a.at))+(a.by?' · '+esc(a.by):'')+'</small></span></div>').join(''):'<p>尚无活动记录；后续归档、恢复、复制和状态修改会记录在这里。</p>')+'</div></div>'
      +'<div class="pm-detail-actions"><button class="btn" data-pm-open="'+esc(p.id)+'">'+(current?'返回当前项目':'打开并继续')+'</button><button class="btn ghost" data-pm-copy="'+esc(p.id)+'">复制项目</button>'
      +(p.archived?'<button class="btn ghost" data-pm-archive="'+esc(p.id)+'" data-value="0">恢复项目</button><button class="btn danger-lite" data-pm-purge="'+esc(p.id)+'">彻底删除</button>':'<button class="btn ghost" data-pm-archive="'+esc(p.id)+'" data-value="1">归档项目</button>')+'</div>';
  }
  async function open(options){
    options=options||{};document.getElementById("projPanel")?.remove();const initialRoute=root.ProjectWorkspaceUI&&root.ProjectWorkspaceUI.parseRoute(location.hash),returnHash=initialRoute?"":location.hash;
    document.body.insertAdjacentHTML("beforeend",'<div id="projPanel" class="proj-overlay"><section class="proj-panel pm-shell"><header class="pm-head"><div class="pm-head-brand"><span>SHENZHEN · INVESTMENT OS</span><b>投资全周期项目工作台</b><small>项目发现、测算、可研、审查、决策与投后管理统一入口</small></div><nav class="pm-head-nav" aria-label="项目主导航"><button class="active" type="button" data-pm-head-view="overview">项目库</button><button type="button" data-pm-head-view="data">数据中心</button><button type="button" data-pm-head-view="decisions">决策中心</button><button type="button" data-pm-head-view="files">成果档案</button></nav><button class="pp-close" id="ppClose" aria-label="关闭">×</button></header><div class="pm-toolbar"><label>⌕<input id="pmSearch" placeholder="搜索项目名称、区域、负责人或标签"></label><select id="pmSort"><option value="updated">按最近更新</option><option value="name">按项目名称</option><option value="progress">按完成进度</option></select><button class="pm-tab active" data-pm-tab="active">进行中</button><button class="pm-tab" data-pm-tab="archived">已归档</button><button class="btn" id="pmNew">＋ 新建项目</button></div><main class="pm-main"><aside id="pmList"><div class="pm-loading">正在读取项目索引…</div></aside><article id="pmDetail"></article></main></section></div>');
    const overlay=document.getElementById("projPanel"),listEl=document.getElementById("pmList"),detailEl=document.getElementById("pmDetail");
    let projects=[],selected=initialRoute&&initialRoute.projectId||null,view=initialRoute&&initialRoute.view||"overview",tab="active",query="",sort="updated",brainCache={},brainErrors={},brainLoading=new Set(),opsCache={},opsErrors={},opsLoading=new Set(),intelligenceCache={},intelligenceErrors={},intelligenceLoading=new Set(),workspaceCache={},workspaceErrors={},workspaceLoading=new Set();
    const headers=()=>typeof options.headers==="function"?options.headers():{};
    async function api(body){const r=await fetch("/api/projects",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"操作失败");return d;}
    async function brainApi(body){const r=await fetch("/api/projectbrain",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目大脑操作失败");return d;}
    async function opsApi(body){const r=await fetch("/api/investmentops",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Investment OS操作失败");return d;}
    async function intelligenceApi(body){const r=await fetch("/api/projectintelligence",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目智能模型操作失败");return d;}
    async function workspaceApi(body){const r=await fetch("/api/projectworkspace",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目工作区操作失败");return d;}
    async function loadBrain(id){if(!id||brainLoading.has(id))return;brainLoading.add(id);delete brainErrors[id];try{const r=await fetch("/api/projectbrain?projectId="+encodeURIComponent(id),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目大脑加载失败");brainCache[id]=d.context;}catch(e){brainErrors[id]=e.message;}finally{brainLoading.delete(id);if(selected===id)render();}}
    async function loadOps(id){if(!id||opsLoading.has(id))return;opsLoading.add(id);delete opsErrors[id];try{const r=await fetch("/api/investmentops?projectId="+encodeURIComponent(id),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"执行台加载失败");opsCache[id]=d.ops;}catch(e){opsErrors[id]=e.message;}finally{opsLoading.delete(id);if(selected===id)render();}}
    async function loadIntelligence(id){if(!id||intelligenceLoading.has(id))return;intelligenceLoading.add(id);delete intelligenceErrors[id];try{const r=await fetch("/api/projectintelligence?projectId="+encodeURIComponent(id),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目智能总览加载失败");intelligenceCache[id]=d.readModel;}catch(e){intelligenceErrors[id]=e.message;}finally{intelligenceLoading.delete(id);if(selected===id)render();}}
    async function loadWorkspace(id,requestedView){if(!id||requestedView==="overview")return;const key=id+":"+requestedView;if(workspaceLoading.has(key))return;workspaceLoading.add(key);delete workspaceErrors[key];try{const r=await fetch("/api/projectworkspace?projectId="+encodeURIComponent(id)+"&view="+encodeURIComponent(requestedView),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目工作区加载失败");workspaceCache[key]=d;}catch(e){workspaceErrors[key]=e.message;}finally{workspaceLoading.delete(key);if(selected===id&&view===requestedView)render();}}
    function setRoute(id,nextView,replace){if(!id||!root.ProjectWorkspaceUI)return;const hash=root.ProjectWorkspaceUI.route(id,nextView);if(location.hash===hash)return;if(replace)history.replaceState(null,"",hash);else history.pushState(null,"",hash);}
    function visible(){
      const arr=projects.filter(p=>(tab==="archived")===!!p.archived&&matches(p,query));
      return arr.sort(sort==="name"?(a,b)=>String(a.name).localeCompare(String(b.name),"zh-CN"):sort==="progress"?(a,b)=>b.progress-a.progress:(a,b)=>b.updated_at-a.updated_at);
    }
    function render(){const rows=visible();if(!rows.some(p=>p.id===selected)){selected=rows[0]?.id||null;if(selected)setRoute(selected,view,true);}listEl.innerHTML='<div class="pm-list-summary"><b>'+rows.length+' 个项目</b><span>'+(tab==="archived"?'可恢复或彻底删除':'选择项目进入工作区')+'</span></div><div class="pm-list-columns"><span>项目 / 区域</span><span>类型</span><span>阶段</span><span>进度</span><span>更新时间</span></div>'+(rows.length?rows.map(p=>projectCard(p,p.id===selected,intelligenceCache[p.id])).join(''):'<div class="pm-detail-empty"><b>这里还没有项目</b><span>'+(tab==="archived"?'归档项目会安全地保存在这里。':'新建项目后，系统会自动保存并记录进度。')+'</span></div>');const key=selected+":"+view,workspace=workspaceCache[key]||workspaceErrors[key]&&{error:workspaceErrors[key]};detailEl.innerHTML=detail(projects.find(p=>p.id===selected),options.currentId&&options.currentId(),brainCache[selected],brainErrors[selected],opsCache[selected],opsErrors[selected],intelligenceCache[selected],intelligenceErrors[selected],view,workspace);overlay.querySelectorAll('[data-pm-head-view]').forEach(b=>b.classList.toggle('active',b.dataset.pmHeadView===view));bind();if(view==="overview"){if(selected&&!brainCache[selected]&&!brainErrors[selected])loadBrain(selected);if(selected&&!opsCache[selected]&&!opsErrors[selected])loadOps(selected);if(selected&&!intelligenceCache[selected]&&!intelligenceErrors[selected])loadIntelligence(selected);}else if(selected&&!workspaceCache[key]&&!workspaceErrors[key])loadWorkspace(selected,view);}
    function bind(){
      listEl.querySelectorAll('[data-pm-select]').forEach(b=>b.onclick=()=>{selected=b.dataset.pmSelect;setRoute(selected,view);render();});
      detailEl.querySelectorAll('[data-pw-view]').forEach(b=>b.onclick=()=>{view=b.dataset.pwView;setRoute(selected,view);render();});
      detailEl.querySelectorAll('[data-pw-retry]').forEach(b=>b.onclick=()=>{const key=selected+":"+view;delete workspaceErrors[key];delete workspaceCache[key];loadWorkspace(selected,view);render();});
      detailEl.querySelectorAll('[data-pw-file-save]').forEach(b=>b.onclick=async()=>{const name=document.getElementById("pwFileName")?.value.trim(),category=document.getElementById("pwFileCategory")?.value.trim()||"other",storageRef=document.getElementById("pwFileRef")?.value.trim()||"";if(!name){alert("请填写文件名");return;}try{await workspaceApi({action:"registerFile",projectId:selected,file:{name,category,storageRef,fileType:(name.split('.').pop()||'').toLowerCase()}});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-extract-save]').forEach(b=>b.onclick=async()=>{const fileId=b.dataset.pwExtractSave,key=detailEl.querySelector('[data-pw-extract-key="'+CSS.escape(fileId)+'"]')?.value.trim(),label=detailEl.querySelector('[data-pw-extract-label="'+CSS.escape(fileId)+'"]')?.value.trim(),raw=detailEl.querySelector('[data-pw-extract-value="'+CSS.escape(fileId)+'"]')?.value.trim();if(!key){alert("请填写结构化字段键");return;}let value=raw;try{value=JSON.parse(raw);}catch(_){}try{await workspaceApi({action:"saveExtraction",projectId:selected,extraction:{fileId,type:"fact",key,label,value,confidence:.7}});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-extract-review]').forEach(b=>b.onclick=async()=>{const tip=b.dataset.decision==="approve"?"审核通过后会沉淀为正式项目数据。":"驳回后该提取项不会进入正式项目数据。";if(!confirm(tip+"是否继续？"))return;try{await workspaceApi({action:"reviewExtraction",projectId:selected,id:b.dataset.pwExtractReview,decision:b.dataset.decision});delete workspaceCache[selected+":"+view];delete workspaceCache[selected+":data"];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-member-save]').forEach(b=>b.onclick=async()=>{const userId=Number(document.getElementById("pwMemberId")?.value),role=document.getElementById("pwMemberRole")?.value;if(!userId){alert("请填写有效用户ID");return;}try{await workspaceApi({action:"updateMember",projectId:selected,userId,role});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-member-remove]').forEach(b=>b.onclick=async()=>{if(!confirm("移除后该成员将无法访问此项目，是否继续？"))return;try{await workspaceApi({action:"removeMember",projectId:selected,userId:Number(b.dataset.pwMemberRemove)});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-profile-save]').forEach(b=>b.onclick=async()=>{try{await workspaceApi({action:"updateProfile",projectId:selected,profile:{organizationId:document.getElementById("pwOrgId")?.value.trim(),departmentId:document.getElementById("pwDeptId")?.value.trim(),visibility:document.getElementById("pwVisibility")?.value,confidentialityLevel:document.getElementById("pwConf")?.value}});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-stage]').forEach(b=>b.onclick=async()=>{const current=brainCache[selected]&&brainCache[selected].lifecycle&&brainCache[selected].lifecycle.current;if(b.dataset.pmStage===current)return;const reason=prompt("切换项目阶段的原因（将写入项目时间线）","");if(reason===null)return;try{await brainApi({action:"setStage",projectId:selected,stageKey:b.dataset.pmStage,reason});delete brainCache[selected];await loadBrain(selected);await load();}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-decision]').forEach(b=>b.onclick=async()=>{const topic=document.getElementById("pmDecisionTopic")?.value.trim(),owner=document.getElementById("pmDecisionOwner")?.value||"";if(!topic){alert("请先填写决策议题");return;}try{await brainApi({action:"createDecision",projectId:selected,decision:{topic,owner,stageKey:brainCache[selected]?.lifecycle?.current||"feasibility"}});delete brainCache[selected];await loadBrain(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-extract]').forEach(b=>b.onclick=async()=>{const title=document.getElementById("pmMeetingTitle")?.value.trim(),content=document.getElementById("pmMeetingText")?.value.trim();if(!content){alert("请先粘贴会议纪要");return;}b.disabled=true;try{const d=await opsApi({action:"extractMeeting",projectId:selected,title,content});alert("已形成候选：决定 "+d.extraction.summary.decisions+" 项、任务 "+d.extraction.summary.tasks+" 项、风险 "+d.extraction.summary.risks+" 项。确认前不会写入正式台账。");delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}finally{b.disabled=false;}});
      detailEl.querySelectorAll('[data-pm-confirm-meeting]').forEach(b=>b.onclick=async()=>{if(!confirm("确认后，候选决定、任务和风险将进入正式台账。是否继续？"))return;try{const d=await opsApi({action:"confirmMeeting",projectId:selected,meetingId:b.dataset.pmConfirmMeeting});alert("已入台账：决定 "+d.decisionCount+" 项、任务 "+d.taskCount+" 项、风险 "+d.riskCount+" 项");delete opsCache[selected];delete brainCache[selected];await Promise.all([loadOps(selected),loadBrain(selected)]);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-item]').forEach(b=>b.onclick=async()=>{try{await opsApi({action:"updateItem",projectId:selected,type:b.dataset.pmItem,id:b.dataset.id,status:b.dataset.status});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pi-gate]').forEach(b=>b.onclick=async()=>{const name=prompt("阶段门名称，例如：可研审查","");if(!name)return;const plannedDate=prompt("计划日期（YYYY-MM-DD，可留空）","");if(plannedDate===null)return;try{await intelligenceApi({action:"saveGate",projectId:selected,gate:{name,status:"in_progress",plannedDate}});delete intelligenceCache[selected];await loadIntelligence(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pi-milestone]').forEach(b=>b.onclick=async()=>{const name=prompt("里程碑名称，例如：可研初稿","");if(!name)return;const progress=prompt("当前真实完成度（0—100）","0");if(progress===null)return;const owner=prompt("负责人（可留空）","");if(owner===null)return;try{await intelligenceApi({action:"saveMilestone",projectId:selected,milestone:{name,status:Number(progress)>=100?"done":"in_progress",progress:Number(progress)||0,owner}});delete intelligenceCache[selected];await loadIntelligence(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pi-deliverable]').forEach(b=>b.onclick=async()=>{const name=prompt("阶段成果名称，例如：可研报告","");if(!name)return;const dueDate=prompt("计划完成日期（YYYY-MM-DD，可留空）","");if(dueDate===null)return;try{await intelligenceApi({action:"saveDeliverable",projectId:selected,deliverable:{name,status:"not_started",required:true,dueDate}});delete intelligenceCache[selected];await loadIntelligence(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-scenario]').forEach(b=>b.onclick=async()=>{const kind=document.getElementById("pmScenarioKind")?.value||"baseline",name=document.getElementById("pmScenarioName")?.value.trim();try{await opsApi({action:"saveScenario",projectId:selected,scenario:{kind,name}});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-package]').forEach(b=>b.onclick=async()=>{const scenarioId=document.getElementById("pmPackageScenario")?.value,evidenceIds=(brainCache[selected]?.artifacts||[]).map(x=>x.id).filter(Boolean);try{const d=await opsApi({action:"createDecisionPackage",projectId:selected,scenarioId,evidenceIds,title:"投资决策包"});alert(d.package.audit.passed?"投资决策包已通过提交前审计":"决策包已生成但被阻断：\n- "+d.package.audit.blockers.join("\n- "));delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-golden]').forEach(b=>b.onclick=async()=>{const numericErrors=prompt("关键数字错误数（必须如实填写）","0");if(numericErrors===null)return;const evidenceCoverage=prompt("证据覆盖率（0—100）","80");if(evidenceCoverage===null)return;const manualMinutes=prompt("人工耗时（分钟）","");if(manualMinutes===null)return;try{await opsApi({action:"saveEvaluation",projectId:selected,type:"golden_project",status:Number(numericErrors)===0?"recorded":"failed",result:{numericErrors:Number(numericErrors)||0,evidenceCoverage:Number(evidenceCoverage)||0,manualMinutes:Number(manualMinutes)||0,recordedAt:Date.now()}});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-slo]').forEach(b=>b.onclick=async()=>{const concurrency=prompt("实测并发人数（目标50）","50");if(concurrency===null)return;const p95Ms=prompt("核心路径P95耗时（毫秒）","5000");if(p95Ms===null)return;const successRate=prompt("成功率（0—100）","99");if(successRate===null)return;const recoveryRate=prompt("失败恢复率（0—100）","95");if(recoveryRate===null)return;const result={concurrency:Number(concurrency)||0,p95Ms:Number(p95Ms)||0,successRate:(Number(successRate)||0)/100,recoveryRate:(Number(recoveryRate)||0)/100,passed:Number(concurrency)>=50&&Number(p95Ms)<=5000&&Number(successRate)>=99&&Number(recoveryRate)>=95};try{await opsApi({action:"saveEvaluation",projectId:selected,type:"slo_load",status:result.passed?"passed":"failed",result});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-opt]').forEach(b=>b.onclick=async()=>{const title=document.getElementById("pmOptTitle")?.value.trim(),evidence=document.getElementById("pmOptEvidence")?.value.trim(),actualBenefit=document.getElementById("pmOptBenefit")?.value.trim();if(!title){alert("请填写优化事项");return;}try{await opsApi({action:"saveOptimization",projectId:selected,title,evidence,actualBenefit,status:actualBenefit?"verified":"candidate"});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-open]').forEach(b=>b.onclick=()=>options.openProject&&options.openProject(b.dataset.pmOpen));
      detailEl.querySelectorAll('[data-pm-copy]').forEach(b=>b.onclick=async()=>{const src=projects.find(p=>p.id===b.dataset.pmCopy),name=prompt("副本名称",(src?.name||"未命名项目")+"（副本）");if(!name)return;await api({action:"duplicate",sourceId:b.dataset.pmCopy,id:options.genId(),name});await load();});
      detailEl.querySelectorAll('[data-pm-archive]').forEach(b=>b.onclick=async()=>{const archived=b.dataset.value==="1";if(!confirm(archived?"归档后不会出现在进行中列表，可随时恢复。是否继续？":"恢复该项目到进行中列表？"))return;await api({action:"setArchived",id:b.dataset.pmArchive,archived});if(archived&&options.currentId&&b.dataset.pmArchive===options.currentId())options.newProject&&options.newProject(true);await load();});
      detailEl.querySelectorAll('[data-pm-purge]').forEach(b=>b.onclick=async()=>{const p=projects.find(x=>x.id===b.dataset.pmPurge);if(prompt("彻底删除不可恢复。请输入项目名称确认：")!==(p?.name||""))return;const r=await fetch("/api/projects?id="+encodeURIComponent(b.dataset.pmPurge),{method:"DELETE",headers:headers()});if(!r.ok)throw new Error("删除失败");await load();});
      detailEl.querySelectorAll('[data-pm-meta]').forEach(b=>b.onclick=async()=>{const tags=document.getElementById("pmTags").value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean),status=document.getElementById("pmStatus").value,saved=await api({action:"updateMeta",id:b.dataset.pmMeta,status,tags});if(options.updateCurrentMeta&&b.dataset.pmMeta===options.currentId())options.updateCurrentMeta({status,tags},saved.updatedAt);await load();});
    }
    async function load(){try{const r=await fetch("/api/projects",{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"加载失败");projects=d.list||[];render();}catch(e){listEl.innerHTML='<div class="pm-detail-empty"><b>项目索引加载失败</b><span>'+esc(e.message)+'</span></div>';}}
    function onHistory(){const r=root.ProjectWorkspaceUI&&root.ProjectWorkspaceUI.parseRoute(location.hash);if(!document.getElementById("projPanel"))return;if(!r){overlay.remove();removeEventListener("popstate",onHistory);return;}selected=r.projectId;view=r.view;render();}
    function close(){removeEventListener("popstate",onHistory);overlay.remove();if(returnHash)history.pushState(null,"",returnHash);else history.pushState(null,"",location.pathname+location.search);}
    overlay.onclick=e=>{if(e.target===overlay)close();};document.getElementById("ppClose").onclick=close;
    addEventListener("popstate",onHistory);
    document.getElementById("pmSearch").oninput=e=>{query=e.target.value;render();};document.getElementById("pmSort").onchange=e=>{sort=e.target.value;render();};
    document.querySelectorAll('[data-pm-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.pmTab;document.querySelectorAll('[data-pm-tab]').forEach(x=>x.classList.toggle("active",x===b));render();});
    document.querySelectorAll('[data-pm-head-view]').forEach(b=>b.onclick=()=>{if(!selected)return;view=b.dataset.pmHeadView;setRoute(selected,view);render();});
    document.getElementById("pmNew").onclick=()=>{if(confirm("新建项目后，当前项目仍会自动保存。是否继续？")){overlay.remove();options.newProject&&options.newProject();}};
    await load();
  }
  root.ProjectManager={open,health,matches,displayType};
  if(typeof module==="object"&&module.exports)module.exports={health,matches,displayType};
})(typeof window!=="undefined"?window:globalThis);
