/* 投资全周期项目驾驶舱：统一管理项目索引、Project Brain、阶段、恢复入口和元数据。 */
(function(root){
  "use strict";
  const PM_STATUS={draft:"草稿",collecting:"资料准备",calculated:"测算完成",generating:"生成中",review:"复核签发",signed:"已签发",paused:"暂缓"};
  const PM_TYPE={rent:"出租类",sale:"出售类",gaibao:"中资产（非居改保/商业改造等）","保障性租赁住房":"出租类","配售型保障性住房":"出售类"};
  const PM_ROLE={OWNER:"项目负责人",EDITOR:"编辑成员",VIEWER:"查看成员"};
  const esc=value=>String(value==null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const when=value=>{const d=new Date(Number(value)||value);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("zh-CN")+" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0");};
  function displayType(value){return PM_TYPE[value]||value||"类型待确认";}
  function health(p){
    const issues=[];
    if(!p.location)issues.push("位置待补");
    if(!p.calcVersions)issues.push("未形成测算快照");
    if(p.stale)issues.push(p.stale+"节待同步");
    if(!p.materials)issues.push("尚无项目资料");
    return issues.slice(0,3);
  }
  function matches(p,q){q=String(q||"").trim().toLowerCase();if(!q)return true;return [p.name,p.location,p.owner,p.type,p.stage].concat(p.tags||[]).join(" ").toLowerCase().includes(q);}
  function navigationGuard(){let version=0;return {cancel(){version++;},async run(preserve,commit,onError){const ticket=++version;try{if(preserve)await preserve();if(ticket!==version)return false;commit();return true;}catch(e){if(ticket===version&&onError)onError(e);return false;}}};}
  const pmDrafts=new Map();
  function reportVersionsHtml(p){
    const versions=Array.isArray(p.reportVersionItems)?p.reportVersionItems:[],current=p.generated?'<button type="button" class="pm-report-version current" data-pm-preview-project="'+esc(p.id)+'" data-pm-preview-version="current"><b>当前工作稿</b><span>'+p.generated+'/'+p.sections+' 小节 · 刷新后仍可直接打开</span><i>进入预览</i></button>':'';
    return '<div class="pm-detail-section pm-report-versions"><h3>可研进度与报告版本</h3><p class="pm-hint">每一版都是独立只读预览；打开历史版不会覆盖当前工作稿，也不会调用AI。</p><div class="pm-report-version-list">'+current+versions.map(v=>'<button type="button" class="pm-report-version" data-pm-preview-project="'+esc(p.id)+'" data-pm-preview-version="'+esc(v.id)+'"><b>报告 V'+Number(v.version||0)+(v.current?' · 当前正式版':'')+'</b><span>'+esc(v.reason||'报告版本')+' · '+esc(when(v.createdAt))+'</span><i>查看该版</i></button>').join('')+(current||versions.length?'':'<div class="pm-detail-empty"><span>尚未生成可研正文。</span></div>')+'</div></div>';
  }
  function projectCard(p,active,intelligence){
    const hs=health(p),real=intelligence&&intelligence.progress,hasReal=!!(real&&real.configured),progress=hasReal?Number(real.value)||0:0;
    return '<button type="button" class="pm-project '+(active?'active':'')+'" data-pm-select="'+esc(p.id)+'">'
      +'<span class="pm-project-primary"><b>'+esc(p.name||"未命名项目")+'</b><small>'+esc(p.location||"位置待补")+'</small></span>'
      +'<span class="pm-project-type">'+esc(displayType(p.type))+'</span>'
      +'<span class="pm-project-stage"><i class="pm-status s-'+esc(p.status)+'">'+esc(PM_STATUS[p.status]||p.stage||"进行中")+'</i><small>'+esc(p.stage||"草稿")+'</small></span>'
      +'<span class="pm-project-progress"><b>'+(hasReal?progress+'%':'—')+'</b><i class="pm-progress '+(hasReal?'':'pending')+'"><em style="width:'+Math.max(0,Math.min(100,progress))+'%"></em></i></span>'
      +'<span class="pm-project-time">'+esc(when(p.updated_at))+'</span>'
      +(hs.length?'<span class="pm-warnings">'+hs.map(x=>'<i>'+esc(x)+'</i>').join('')+'</span>':'')+'</button>';
  }
  function intelligenceHtml(model,error){
    if(error)return '<div class="pm-intelligence"><div class="pm-intel-head"><b>项目智能 · 项目总览</b><span class="bad">加载失败</span></div><p>'+esc(error)+'</p></div>';
    if(!model)return '<div class="pm-intelligence"><div class="pm-intel-head"><b>项目智能 · 项目总览</b><span>正在建立统一只读模型…</span></div></div>';
    const progress=model.progress||{},gate=model.gate,k=model.kpis||{},health=model.dataHealth||{},milestones=model.milestones||[],deliverables=model.deliverables||[],canEdit=!!(model.contextContract&&model.contextContract.permissions&&model.contextContract.permissions.edit),fmt=v=>v==null||v===""?'—':esc(v),statusLabel={not_started:'待开始',in_progress:'进行中',blocked:'受阻',done:'已完成',cancelled:'已取消',passed:'已通过',waived:'已豁免'};
    const role=model.contextContract?.permissions?.role||'VIEWER';
    return '<div class="pm-intelligence"><div class="pm-intel-head"><div><b>项目智能 · 项目总览</b><small>统一读取视图 V1 · '+esc(PM_ROLE[role]||role)+'</small></div><span>'+(progress.configured?'真实进度 '+Number(progress.value||0)+'%':'尚未配置真实进度')+'</span></div>'
      +'<div class="pm-intel-kpis"><div><b>'+fmt(k.totalInvestment)+'</b><span>总投资（白箱结果）</span></div><div><b>'+fmt(k.irr)+'</b><span>内部收益率（IRR，白箱结果）</span></div><div><b>'+Number(health.score||0)+'</b><span>数据健康分</span></div><div><b>'+Number(k.openRiskCount||0)+'</b><span>开放风险</span></div><div><b>'+Number(k.overdueTaskCount||0)+'</b><span>逾期任务</span></div></div>'
      +'<div class="pm-intel-gate"><span>当前阶段门</span><b>'+esc(gate?.name||'尚未设置')+'</b><i class="'+(gate?.status==='blocked'?'bad':'')+'">'+esc(statusLabel[gate?.status]||'待配置')+'</i>'+(gate?.blockReason?'<small>'+esc(gate.blockReason)+'</small>':'')+'</div>'
      +'<div class="pm-two pm-intel-grid"><section><h4>近期里程碑</h4>'+(milestones.length?milestones.slice(0,6).map(x=>'<div class="pm-intel-row"><span><b>'+esc(x.name)+'</b><small>'+esc(x.owner||'负责人待定')+(x.plannedDate?' · '+esc(x.plannedDate):'')+'</small></span><i>'+Number(x.progress||0)+'% · '+esc(statusLabel[x.status]||x.status)+'</i></div>').join(''):'<p>尚未配置里程碑；生命周期不会再冒充实际完成率。</p>')+'</section><section><h4>阶段成果</h4>'+(deliverables.length?deliverables.slice(0,6).map(x=>'<div class="pm-intel-row"><span><b>'+esc(x.name)+'</b><small>'+(x.required?'必需成果':'参考成果')+(x.dueDate?' · '+esc(x.dueDate):'')+'</small></span><i>'+esc(statusLabel[x.status]||x.status)+'</i></div>').join(''):'<p>尚未配置阶段成果。</p>')+'</section></div>'
      +(canEdit?'<div class="pm-intel-actions"><button class="ub-btn ghost" data-pi-gate="1">＋ 阶段门</button><button class="ub-btn ghost" data-pi-milestone="1">＋ 里程碑</button><button class="ub-btn ghost" data-pi-deliverable="1">＋ 阶段成果</button></div>':'')+'</div>';
  }
  function brainHtml(brain,error,part){
    if(error)return '<div class="pm-workspace-error"><b>项目事实与阶段加载失败</b><p>'+esc(error)+'</p><button data-pm-retry-context="brain">重试</button></div>';
    if(!brain)return '<div class="pm-workspace-loading">正在读取项目事实与阶段…</div>';
    const life=brain.lifecycle||{},facts=brain.facts||[],decisions=brain.decisions||[],typeName={FACT:"事实",ASSUMPTION:"假设",CALCULATION:"计算",AI_JUDGEMENT:"AI判断"};
    if(part==="decisions")return '<section class="pm-detail-section"><h3>决策议题台账</h3>'+(decisions.length?decisions.map(x=>'<div class="pm-decision-row"><b>'+esc(x.topic)+'</b><span>'+esc(x.status||"candidate")+'</span></div>').join(''):'<p>尚无决策事项。</p>')+'<div class="pm-brain-form"><input id="pmDecisionTopic" placeholder="新增决策议题"><select id="pmDecisionOwner"><option value="">负责人待定</option><option>投资部</option><option>项目负责人</option></select><button class="ub-btn" data-pm-decision="1">新增候选</button></div></section>';
    return '<section class="pm-detail-section"><h3>项目事实与证据索引</h3><p class="pm-hint">区分已确认事实、假设、计算和 AI 判断。详细参数及溯源位置请到“数据注册表”。</p>'+(facts.length?facts.map(x=>'<div class="pm-fact-row"><span>'+esc(x.label||x.factKey)+'</span><i>'+esc(typeName[x.factType]||x.factType)+' · '+esc(x.status==="confirmed"?"已确认":"待确认")+'</i></div>').join(''):'<div class="pm-detail-empty">尚无结构化事实。</div>')+'<button class="ub-btn ghost" data-pw-view="data">查看完整数据与溯源 →</button></section>';
  }
  function opsHtml(ops,error,part){
    if(error)return '<div class="pm-ops"><div class="pm-ops-title"><b>行动 · 情景 · 生产验收</b><span class="bad">加载失败</span></div><p>'+esc(error)+'</p></div>';
    if(!ops)return '<div class="pm-ops"><div class="pm-ops-title"><b>行动 · 情景 · 生产验收</b><span>正在加载…</span></div></div>';
    const meetings=ops.meetings||[],tasks=ops.tasks||[],risks=ops.risks||[],scenarios=ops.scenarios||[],packages=ops.packages||[],evaluations=ops.evaluations||[],optimizations=ops.optimizations||[],candidate=meetings.find(x=>x.status==="candidate"),cmp=(root.InvestmentOps&&root.InvestmentOps.compareScenarios(scenarios))||{columns:[]};
    const rows=(items,kind)=>items.slice(0,6).map(x=>'<div class="pm-action-row"><span><b>'+esc(x.title)+'</b><small>'+esc(kind==="task"?(x.owner||"负责人待定")+(x.dueDate?' · '+x.dueDate:''):(x.level||"normal")+'级风险')+'</small></span><button class="ub-btn ghost" data-pm-item="'+kind+'" data-id="'+esc(x.id)+'" data-status="'+(kind==="task"?'done':'mitigated')+'">'+(kind==="task"?'完成':'已缓释')+'</button></div>').join('');
    return '<div class="pm-ops">'+
      (part==="actions"?('<details class="pm-ops-block" open><summary><b>① 会议 → 决策 / 任务 / 风险</b><i>待办 '+tasks.filter(x=>x.status==="open").length+' · 风险 '+risks.filter(x=>x.status==="open").length+'</i></summary><div class="pm-ops-body"><div class="pm-meeting-form"><input id="pmMeetingTitle" placeholder="会议名称"><textarea id="pmMeetingText" placeholder="粘贴会议纪要；系统先抽取候选，人工确认后才进入正式台账"></textarea><button class="ub-btn" data-pm-extract="1">抽取候选</button></div>'
      +(candidate?'<div class="pm-candidate"><b>待确认：'+esc(candidate.title)+'</b><span>决定 '+Number(candidate.extraction?.summary?.decisions||0)+' · 任务 '+Number(candidate.extraction?.summary?.tasks||0)+' · 风险 '+Number(candidate.extraction?.summary?.risks||0)+'</span><button class="ub-btn" data-pm-confirm-meeting="'+esc(candidate.id)+'">人工确认并入台账</button></div>':'')
      +'<div class="pm-two"><section><h4>任务台账</h4>'+(rows(tasks.filter(x=>x.status!=="done"),"task")||'<p>暂无待办任务</p>')+'</section><section><h4>风险台账</h4>'+(rows(risks.filter(x=>!['mitigated','closed'].includes(x.status)),"risk")||'<p>暂无开放风险</p>')+'</section></div></div></details>'):'')+
      (part==="scenarios"?('<details class="pm-ops-block" open><summary><b>② 情景分析与投资决策包</b><i>'+scenarios.length+' 个情景 · '+packages.length+' 个决策包</i></summary><div class="pm-ops-body"><div class="pm-inline"><select id="pmScenarioKind"><option value="baseline">基准情景</option><option value="optimistic">乐观情景</option><option value="prudent">审慎情景</option><option value="custom">自定义情景</option></select><input id="pmScenarioName" placeholder="情景名称（可选）"><button class="ub-btn" data-pm-scenario="1">从当前白箱快照保存</button></div>'
      +(scenarios.length?'<div class="pm-scenario-grid">'+scenarios.map(s=>'<div class="pm-scenario"><b>'+esc(s.name)+'</b><span>'+esc(s.kind)+' · '+esc(s.calcSnapshotId)+'</span>'+Object.entries(s.metrics||{}).slice(0,4).map(([k,v])=>'<small>'+esc(k)+' '+esc(v)+'</small>').join('')+'</div>').join('')+'</div><div class="pm-compare">'+cmp.columns.filter(c=>c.values.some(v=>v!==null)).slice(0,6).map(c=>'<div><b>'+esc(c.label)+'</b>'+c.values.map(v=>'<span>'+esc(v==null?'—':v)+' '+esc(c.unit)+'</span>').join('')+'</div>').join('')+'</div><div class="pm-inline"><select id="pmPackageScenario">'+scenarios.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+'</option>').join('')+'</select><button class="ub-btn" data-pm-package="1">审计并形成投资决策包</button></div>':'<p class="pm-hint">先完成财务测算并形成快照，再保存基准/乐观/审慎情景；关键数字只读取白箱引擎。</p>')
      +(packages.length?'<div class="pm-package-list">'+packages.slice(0,5).map(x=>'<span class="'+(x.status==="ready"?'ok':'bad')+'"><b>'+esc(x.title)+'</b> '+(x.status==="ready"?'可提交':'阻断 '+Number(x.audit?.blockers?.length||0)+'项')+'</span>').join('')+'</div>':'')+'</div></details>'):'')+
      (part==="acceptance"?('<details class="pm-ops-block" open><summary><b>③ 真实项目验证与生产化</b><i>'+evaluations.length+' 条验收 · '+optimizations.length+' 条优化</i></summary><div class="pm-ops-body"><div class="pm-gates">'+((ops.production&&ops.production.checks)||[]).map(x=>'<span class="'+(x.ok?'ok':'bad')+'">'+(x.ok?'✓ ':'○ ')+esc(x.label)+'</span>').join('')+'</div><div class="pm-two"><section><h4>黄金项目 / 服务目标（SLO）验收</h4><div class="pm-inline"><button class="ub-btn" data-pm-golden="1">记录当前黄金项目评测</button><button class="ub-btn ghost" data-pm-slo="1">记录50人服务目标实测</button></div>'+evaluations.slice(0,5).map(x=>'<div class="pm-eval"><b>'+esc(x.type)+'</b><span>'+esc(x.status)+'</span></div>').join('')+'</section><section><h4>优化台账</h4><div class="pm-opt-form"><input id="pmOptTitle" placeholder="优化事项"><input id="pmOptEvidence" placeholder="证据/测试编号"><input id="pmOptBenefit" placeholder="实际收益"><button class="ub-btn" data-pm-opt="1">记录优化</button></div>'+optimizations.slice(0,5).map(x=>'<div class="pm-eval"><b>'+esc(x.title)+'</b><span>'+esc(x.actualBenefit||x.status)+'</span></div>').join('')+'</section></div><p class="pm-hint">这里记录真实结果，不自动伪造5—20个黄金项目或50人压测数据；达到门槛后才允许启动项目组合大脑。</p></div></details>'):'')+'</div>';
  }
  function detail(p,currentId,brain,error,ops,opsError,intelligence,intelligenceError,view,workspace,viewStageKey){
    if(!p)return '<div class="pm-detail-empty"><b>选择一个项目</b><span>查看项目进度、成果版本、资料状态和恢复入口。</span></div>';
    view=view||"overview";const current=p.id===currentId,hs=health(p),acts=(p.activity||[]),nav='<div class="pm-page-heading"><span>当前项目</span><h3>'+esc(root.ProjectWorkspaceUI?.VIEWS?.[view]||view)+'</h3></div>',workspaceHtml=view==="overview"?"":(root.ProjectWorkspaceUI?root.ProjectWorkspaceUI.render(view,workspace):'<div class="pm-detail-empty">工作区模块未加载</div>');
    const ui=root.ProjectWorkspaceUI,work=ui?.workStage(p,brain,intelligence)||{key:null,label:"待确认"},action=ui?.primaryAction(view,viewStageKey||work.key,p,p.permissions),actionAttr=action?.kind==="report"?'data-pm-ai="'+esc(p.id)+'"':action?.kind==="stage"?'data-pm-stage-view="'+esc(action.stageKey)+'"':'data-pw-view="'+esc(action?.view||"facts")+'"';
    const management=(p.permissions?.manage||p.permissions?.delete)?'<details class="pm-project-management"><summary>项目管理</summary>'+(p.permissions?.manage?(p.archived?'<button class="btn ghost" data-pm-archive="'+esc(p.id)+'" data-value="0">恢复</button>':'<button class="btn ghost" data-pm-archive="'+esc(p.id)+'" data-value="1">移至归档</button>'):'')+(p.permissions?.delete?'<button class="btn ghost danger-lite" data-pm-purge="'+esc(p.id)+'">删除项目</button>':'')+'</details>':'';
    const workSelector=p.permissions?.manage&&ui&&Number.isInteger(intelligence?.stage?.version)?'<label class="pm-work-stage">项目工作阶段：<select data-pm-work-stage aria-label="更正项目工作阶段">'+(!work.key?'<option value="">待确认</option>':'')+ui.STAGES.map(x=>'<option value="'+x.key+'" '+(x.key===work.key?'selected':'')+'>'+esc(x.label)+'</option>').join('')+'</select></label>':'<p class="pm-work-stage">项目工作阶段：<b>'+esc(work.label)+'</b></p>';
    const head='<div class="pm-detail-head"><div><span class="pm-eyebrow">项目工作区</span><h2>'+esc(p.name||"未命名项目")+'</h2><p>'+esc(displayType(p.type))+' · '+esc(p.location||"位置待补")+' · 负责人 '+esc(p.owner||"待指定")+'</p>'+workSelector+(intelligence?.stage?.legacyConflict?'<p class="pm-hint">历史阶段记录存在差异，请由负责人核对工作阶段。</p>':'')+'</div><div class="pm-detail-head-actions">'+(action?'<button type="button" class="btn pm-primary-action" '+actionAttr+'>'+esc(action.label)+'</button>':'')+management+'</div></div>'+(ui?ui.stageNavigation(view==="stages"?viewStageKey:null,work.key):'')+nav;
    if(view==="versions")return head+reportVersionsHtml(p);
    const requirementsHtml=ui?.requirements&&['stages','facts','files'].includes(view)?ui.requirements({brain,brainError:error,intelligence,intelligenceError},view!=='facts'):'';
    if(view==="stages")return head+(viewStageKey&&ui?ui.stageWorkspace(viewStageKey,{brain,brainError:error,intelligence,intelligenceError,ops,opsError}):intelligenceHtml(intelligence,intelligenceError))+(['implementation','post_investment'].includes(viewStageKey)?'<section class="pm-detail-section" data-pm-lifecycle-host="'+(viewStageKey==='implementation'?'plan':'operations')+'"><p role="status">正在读取'+(viewStageKey==='implementation'?'实施计划':'投后管理')+'…</p></section>':'')+requirementsHtml;
    if(view==="facts")return head+requirementsHtml+brainHtml(brain,error);
    if(view==="files")return head+workspaceHtml+requirementsHtml;
    if(["actions","scenarios","acceptance"].includes(view))return head+opsHtml(ops,opsError,view);
    if(view==="decisions")return head+workspaceHtml+brainHtml(brain,error,"decisions");
    if(view!=="overview")return head+workspaceHtml;
    return head
      +'<div class="pm-phase"><div><b>生命周期：'+esc(intelligence?.stage?.label||p.stage)+'</b><span>'+(intelligence?.progress?.configured?'项目真实进度 '+Number(intelligence.progress.value||0)+'%':'项目真实进度待配置')+'</span></div><i><em style="width:'+(intelligence?.progress?.configured?Number(intelligence.progress.value||0):0)+'%"></em></i></div>'
      +'<div class="pm-kpis"><div><b>'+esc(work.label)+'</b><span>项目工作阶段</span></div><div><b>'+esc(p.materials??"—")+'</b><span>项目资料</span></div><div><b>'+esc(intelligence?.kpis?.overdueTaskCount??"—")+'</b><span>逾期任务</span></div><div><b>'+esc(intelligence?.kpis?.pendingDecisionCount??"—")+'</b><span>待处理决策</span></div></div>'
      +'<div class="pm-overview-links"><button data-pw-view="stages"><b>推进项目</b><span>阶段门、里程碑与交付计划 →</span></button><button data-pw-view="versions"><b>查看成果</b><span>当前报告与历史版本 →</span></button><button data-pw-view="actions"><b>跟进行动</b><span>会议、待办与风险台账 →</span></button></div>'
      +'<div class="pm-detail-section"><h3>项目健康状态</h3><div class="pm-health">'+(hs.length?hs.map(x=>'<span class="warn">! '+esc(x)+'</span>').join(''):'<span class="ok">✓ 当前未发现明显保存或同步风险</span>')+(p.locked?'<span>🔒 '+p.locked+'节人工锁定</span>':'')+'</div></div>'
      +'<div class="pm-detail-section"><h3>项目状态与标签</h3><div class="pm-meta-edit"><select id="pmStatus">'+Object.entries(PM_STATUS).map(([k,v])=>'<option value="'+k+'" '+(p.status===k?'selected':'')+'>'+v+'</option>').join('')+'</select><input id="pmTags" value="'+esc((p.tags||[]).join('、'))+'" placeholder="标签，用顿号分隔"><button class="ub-btn" data-pm-meta="'+esc(p.id)+'">保存</button></div></div>'
      +'<div class="pm-detail-section"><h3>最近活动</h3><div class="pm-activity">'+(acts.length?acts.map(a=>'<div><i></i><span><b>'+esc(a.text||"项目更新")+'</b><small>'+esc(when(a.at))+(a.by?' · '+esc(a.by):'')+'</small></span></div>').join(''):'<p>尚无活动记录；后续归档、恢复、复制和状态修改会记录在这里。</p>')+'</div></div>'
      +'<div class="pm-detail-actions"><button class="btn" data-pm-open="'+esc(p.id)+'">'+(current?'返回当前项目':'打开并继续')+'</button><button class="btn ghost" data-pm-copy="'+esc(p.id)+'">复制项目</button>'
      +(p.archived?'<button class="btn ghost" data-pm-archive="'+esc(p.id)+'" data-value="0">恢复项目</button><button class="btn danger-lite" data-pm-purge="'+esc(p.id)+'">彻底删除</button>':'<button class="btn ghost" data-pm-archive="'+esc(p.id)+'" data-value="1">归档项目</button><button class="btn ghost danger-lite" data-pm-purge="'+esc(p.id)+'">删除项目</button>')+'</div>';
  }
  let activeCleanup=null;
  async function open(options){
    options=options||{};if(activeCleanup)activeCleanup();document.getElementById("projPanel")?.remove();const initialRoute=root.ProjectWorkspaceUI&&root.ProjectWorkspaceUI.parseRoute(location.hash),returnHash=initialRoute?"":location.hash;
    document.body.insertAdjacentHTML("beforeend",'<div id="projPanel" class="proj-overlay"><section class="proj-panel pm-shell"><header class="pm-head"><div class="pm-head-brand"><span>深圳 · 投资管理系统</span><b>投资全周期项目工作台</b><small>项目发现、测算、可研、审查、决策与投后管理统一入口</small></div><nav class="pm-head-nav" aria-label="项目主导航"><button class="active" type="button" data-pm-head-view="library">项目库</button><button type="button" data-pm-head-view="data">数据中心</button><button type="button" data-pm-head-view="decisions">决策中心</button><button type="button" data-pm-head-view="versions">成果档案</button></nav><button class="pp-close" id="ppClose" aria-label="返回主工作台" title="返回主工作台">×</button></header><div class="pm-toolbar"><label>⌕<input id="pmSearch" placeholder="搜索项目名称、区域、负责人或标签"></label><select id="pmSort"><option value="updated">按最近更新</option><option value="name">按项目名称</option><option value="progress">按完成进度</option></select><button class="pm-tab active" data-pm-tab="active">进行中</button><button class="pm-tab" data-pm-tab="archived">已归档</button><button class="btn" id="pmNew">＋ 新建项目</button></div><main class="pm-main"><aside id="pmSidebar"></aside><section class="pm-page-content"><div id="pmList"><div class="pm-loading">正在读取项目索引…</div></div><article id="pmDetail"></article></section></main></section></div>');
    const overlay=document.getElementById("projPanel"),listEl=document.getElementById("pmList"),detailEl=document.getElementById("pmDetail");
    let projects=[],selected=initialRoute&&initialRoute.projectId||null,view=initialRoute&&initialRoute.view||"library",viewStageKey=initialRoute?.viewStageKey||null,tab="active",query="",sort="updated",brainCache={},brainErrors={},brainLoading=new Set(),opsCache={},opsErrors={},opsLoading=new Set(),intelligenceCache={},intelligenceErrors={},intelligenceLoading=new Set(),workspaceCache={},workspaceErrors={},workspaceLoading=new Set();
    const ui=root.ProjectWorkspaceUI,guard=navigationGuard(),pageContent=overlay.querySelector('.pm-page-content'),userId=typeof options.userId==="function"?options.userId():options.userId,draftNamespace=userId?String(userId):"session-"+Date.now()+Math.random();
    let renderedKey=null,navigationError="",scrollPositions=new Map(),stageFeedback=new Map(),lifecycleMount=null;
    function disposeLifecycle(){lifecycleMount?.controller?.dispose?.();lifecycleMount=null;}
    function mountLifecycle(){
      const host=detailEl.querySelector('[data-pm-lifecycle-host]');
      if(!host){disposeLifecycle();return;}
      const mode=host.dataset.pmLifecycleHost;
      if(lifecycleMount?.projectId===selected&&lifecycleMount.mode===mode){host.replaceWith(lifecycleMount.host);return;}
      disposeLifecycle();
      const fail=()=>{host.innerHTML='<div class="pm-workspace-error"><b>此管理组件暂不可用</b><p>可继续浏览其他项目资料，或重新加载本组件。</p><button type="button" data-pm-lifecycle-retry>重试组件</button></div>';host.querySelector('[data-pm-lifecycle-retry]').onclick=mountLifecycle;};
      if(!root.InvestmentOps?.mountLifecycle){fail();return;}
      try{const controller=root.InvestmentOps.mountLifecycle(host,{projectId:selected,mode,headers});lifecycleMount={projectId:selected,mode,host,controller};}catch(_){fail();}
    }
    const screenKey=()=>draftNamespace+":"+(view==="library"?"library":selected+":"+view+":"+(viewStageKey||""));
    const fieldKey=el=>el.id||Object.entries(el.dataset||{}).filter(([k])=>k.startsWith("pw")).map(([k,v])=>k+":"+v).join("|");
    function rememberInput(e){const el=e.target;if(!renderedKey||!el.matches('input,textarea,select')||!fieldKey(el)||el.type==='password')return;const draft={...(pmDrafts.get(renderedKey)||{})};draft[fieldKey(el)]={value:el.value,checked:el.checked};pmDrafts.set(renderedKey,draft);}
    function restoreInputs(){const draft=pmDrafts.get(renderedKey)||{};detailEl.querySelectorAll('input,textarea,select').forEach(el=>{const saved=draft[fieldKey(el)];if(saved&&!el.disabled){el.value=saved.value;if(el.type==='checkbox'||el.type==='radio')el.checked=saved.checked;}});}
    function preferenceStorage(){try{return root.localStorage;}catch(_){return null;}}
    function saveView(){if(view!=="library")ui?.writeViewPreference(preferenceStorage(),userId,selected,{view,viewStageKey});}
    async function navigate(id,nextView,nextStage=null,historyNavigation=false){
      if(nextView!=="library"&&(!id||!ui?.VIEWS[nextView]))return false;
      if(nextStage&&!ui?.stage(nextStage))return false;
      const previous={projectId:selected,view,viewStageKey},oldKey=screenKey();
      return guard.run(options.preserveDraft?()=>options.preserveDraft(previous):null,()=>{scrollPositions.set(oldKey,pageContent.scrollTop);selected=id||selected;view=nextView;viewStageKey=nextView==="stages"?nextStage:null;navigationError="";saveView();if(!historyNavigation)setRoute(selected,view,false,viewStageKey);render();pageContent.scrollTop=scrollPositions.get(screenKey())||0;},e=>{navigationError=e.message||"草稿保存失败，已保留当前页面。请重试后再切换。";setRoute(previous.projectId,previous.view,true,previous.viewStageKey);render();});
    }
    detailEl.addEventListener('input',rememberInput);detailEl.addEventListener('change',rememberInput);
    function beforeUnload(e){if([...pmDrafts.keys()].some(key=>key.startsWith(draftNamespace+":"))){e.preventDefault();e.returnValue="";}}
    addEventListener('beforeunload',beforeUnload);
    const headers=()=>typeof options.headers==="function"?options.headers():{};
    async function api(body){const draftKey=renderedKey,draft=pmDrafts.get(draftKey),r=await fetch("/api/projects",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"操作失败");if(body.action==="updateMeta"&&pmDrafts.get(draftKey)===draft)pmDrafts.delete(draftKey);return d;}
    async function openReportPreview(projectId,versionId){
      const r=await fetch("/api/projects?id="+encodeURIComponent(projectId),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"报告版本加载失败");
      const data=d.project?.data||{},wf=data.workflow||{};let chapters=data.chapters||[],label="当前工作稿",reason="当前保存的报告正文";
      if(versionId!=="current"){
        const version=(wf.reportVersions||[]).find(v=>String(v.id)===String(versionId));if(!version)throw new Error("该报告版本不存在或已被清理");chapters=version.chapters||[];label="报告 V"+(Number(version.version)||0);reason=version.reason||"历史报告版本";
      }
      const active=chapters.filter(c=>c.checked!==false),render=value=>typeof root.renderContent==="function"?root.renderContent(value):'<p>'+esc(value).replace(/\n/g,'<br>')+'</p>',body=active.map(c=>'<section class="pm-version-chapter"><h2>'+esc(c.cn)+' '+esc(c.name)+'</h2>'+(c.sections||[]).map(s=>'<article><h3>'+esc(s.t)+'</h3>'+render(s.editedHtml&&typeof root.blocksToSource==="function"?root.blocksToSource(s.editedHtml):(s.content||""))+'</article>').join('')+'</section>').join('');
      document.getElementById("pmReportPreview")?.remove();document.body.insertAdjacentHTML("beforeend",'<div id="pmReportPreview" class="air-modal-overlay pm-version-preview"><div class="air-modal-card"><div class="air-modal-head"><div><b>'+esc(d.project.name)+' · '+esc(label)+'</b><span>'+esc(reason)+' · 只读预览，不调用AI、不覆盖当前稿</span></div><button type="button" class="air-modal-close" aria-label="关闭">×</button></div><div class="pm-version-preview-body">'+(body||'<p>这一版没有可显示的正文。</p>')+'</div></div></div>');
      const modal=document.getElementById("pmReportPreview"),close=()=>modal?.remove();modal.querySelector(".air-modal-close").onclick=close;modal.onclick=e=>{if(e.target===modal)close();};
    }
    async function brainApi(body){const draftKey=renderedKey,draft=pmDrafts.get(draftKey),r=await fetch("/api/projectbrain",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目大脑操作失败");if(pmDrafts.get(draftKey)===draft)pmDrafts.delete(draftKey);return d;}
    async function opsApi(body){const draftKey=renderedKey,draft=pmDrafts.get(draftKey),r=await fetch("/api/investmentops",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"投资管理操作失败");if(pmDrafts.get(draftKey)===draft)pmDrafts.delete(draftKey);if(d.warning)alert(d.warning);return d;}
    async function intelligenceApi(body){const r=await fetch("/api/projectintelligence",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目智能模型操作失败");return d;}
    async function workspaceApi(body){const draftKey=renderedKey,draft=pmDrafts.get(draftKey),r=await fetch("/api/projectworkspace",{method:"POST",headers:Object.assign({"Content-Type":"application/json"},headers()),body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目工作区操作失败");if(pmDrafts.get(draftKey)===draft)pmDrafts.delete(draftKey);return d;}
    async function purgeProject(id){const p=projects.find(x=>x.id===id),name=p?.name||"未命名项目";if(prompt("彻底删除不可恢复。请输入项目名称确认：")!==name)return false;const r=await fetch("/api/projects?id="+encodeURIComponent(id),{method:"DELETE",headers:headers()});let d={};try{d=await r.json();}catch(_){}if(!r.ok||d.ok===false)throw new Error(d.error||"删除失败");const deletingCurrent=options.currentId&&id===options.currentId();selected=null;if(deletingCurrent&&options.newProject)options.newProject(true);await load();return true;}
    async function loadBrain(id){if(!id||brainLoading.has(id))return;brainLoading.add(id);delete brainErrors[id];try{const r=await fetch("/api/projectbrain?projectId="+encodeURIComponent(id),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目大脑加载失败");brainCache[id]=d.context;}catch(e){brainErrors[id]=e.message;}finally{brainLoading.delete(id);if(selected===id)render();}}
    async function loadOps(id){if(!id||opsLoading.has(id))return;opsLoading.add(id);delete opsErrors[id];try{const r=await fetch("/api/investmentops?projectId="+encodeURIComponent(id),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"执行台加载失败");opsCache[id]=d.ops;}catch(e){opsErrors[id]=e.message;}finally{opsLoading.delete(id);if(selected===id)render();}}
    async function loadIntelligence(id){if(!id||intelligenceLoading.has(id))return;intelligenceLoading.add(id);delete intelligenceErrors[id];try{const r=await fetch("/api/projectintelligence?projectId="+encodeURIComponent(id),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目智能总览加载失败");intelligenceCache[id]=d.readModel;}catch(e){intelligenceErrors[id]=e.message;}finally{intelligenceLoading.delete(id);if(selected===id)render();}}
    async function loadWorkspace(id,requestedView){if(!id||!["data","files","decisions","spatial","members"].includes(requestedView))return;const key=id+":"+requestedView;if(workspaceLoading.has(key))return;workspaceLoading.add(key);delete workspaceErrors[key];try{const r=await fetch("/api/projectworkspace?projectId="+encodeURIComponent(id)+"&view="+encodeURIComponent(requestedView),{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"项目工作区加载失败");workspaceCache[key]=d;}catch(e){workspaceErrors[key]=e.message;}finally{workspaceLoading.delete(key);if(selected===id&&view===requestedView)render();}}
    function setRoute(id,nextView,replace,nextStage=viewStageKey){if(!root.ProjectWorkspaceUI||(!id&&nextView!=="library"))return;const hash=nextView==="library"?"#investment/projects":root.ProjectWorkspaceUI.route(id,nextView,nextStage);if(location.hash===hash)return;if(replace)history.replaceState(null,"",hash);else history.pushState(null,"",hash);}
    function visible(){
      const arr=projects.filter(p=>(tab==="archived")===!!p.archived&&matches(p,query));
      return arr.sort(sort==="name"?(a,b)=>String(a.name).localeCompare(String(b.name),"zh-CN"):sort==="progress"?(a,b)=>b.progress-a.progress:(a,b)=>b.updated_at-a.updated_at);
    }
    function render(){
      if(!overlay.isConnected)return;
      const rows=visible(),p=projects.find(p=>p.id===selected),library=view==="library";
      overlay.classList.toggle("pm-library-page",library);
      overlay.querySelector(".pm-toolbar").hidden=!library;
      listEl.hidden=!library;detailEl.hidden=library;
      const sidebar=overlay.querySelector("#pmSidebar");
      sidebar.innerHTML='<button class="pm-library-link" data-pm-library>← 项目库 / 切换项目</button>'+
        (p?'<div class="pm-current-project"><small>当前项目</small><b>'+esc(p.name||"未命名项目")+'</b></div>':'<div class="pm-current-project"><b>投资全周期</b><small>请先在项目库选择项目</small></div>')+
        (!library&&p&&root.ProjectWorkspaceUI?root.ProjectWorkspaceUI.nav(selected,view):'<div class="pm-library-guide"><b>先选项目，再办业务</b><p>选定项目后，左侧会展开项目管理、数据、决策与成果功能。</p></div>');
      listEl.innerHTML='<div class="pm-list-summary"><b>项目库 · '+rows.length+' 个项目</b><span>选择项目，进入独立工作页面</span></div><div class="pm-list-columns"><span>项目 / 区域</span><span>类型</span><span>阶段</span><span>进度</span><span>更新时间</span></div>'+
        (rows.length?rows.map(p=>projectCard(p,p.id===selected,intelligenceCache[p.id])).join(''):'<div class="pm-detail-empty"><b>'+(query?'没有匹配的项目':'这里还没有项目')+'</b><span>'+(query?'试试其他关键词，或清空搜索条件。':tab==="archived"?'归档项目会安全地保存在这里。':'点击右上方“新建项目”开始。')+'</span></div>');
      const key=selected+":"+view,workspace=workspaceCache[key]||workspaceErrors[key]&&{error:workspaceErrors[key]};
      const focused=document.activeElement,focusKey=detailEl.contains(focused)?fieldKey(focused):null,selectionStart=focusKey?focused.selectionStart:null,selectionEnd=focusKey?focused.selectionEnd:null;
      const sameScreen=renderedKey===screenKey();
      if(!sameScreen)disposeLifecycle();
      try{detailEl.innerHTML=library?"":detail(p,options.currentId&&options.currentId(),brainCache[selected],brainErrors[selected],opsCache[selected],opsErrors[selected],intelligenceCache[selected],intelligenceErrors[selected],view,workspace,viewStageKey);}catch(e){detailEl.innerHTML='<div class="pm-workspace-error"><b>此页面暂时无法显示</b><p>已保留其他页面和草稿，请重试。</p><button type="button" data-pm-retry-all>重试当前页面</button></div>';}
      renderedKey=screenKey();
      if(navigationError)detailEl.insertAdjacentHTML('afterbegin','<div class="pm-workspace-error" role="alert">'+esc(navigationError)+'</div>');
      const feedback=stageFeedback.get(selected);if(!library&&feedback)detailEl.querySelector('.pm-work-stage')?.insertAdjacentHTML('afterend','<div class="pm-stage-feedback" role="status">'+esc(feedback.message)+(feedback.undo?'<button type="button" data-pm-undo-stage>撤销</button>':'')+'</div>');
      const group=library?"library":["facts","data","files","spatial"].includes(view)?"data":["decisions","actions","scenarios"].includes(view)?"decisions":["versions","acceptance"].includes(view)?"versions":"library";
      overlay.querySelectorAll('[data-pm-head-view]').forEach(b=>b.classList.toggle('active',b.dataset.pmHeadView===group));
      if(!library){const failed=brainErrors[selected]||opsErrors[selected]||intelligenceErrors[selected];if(failed&&["overview","stages","facts","files","actions","scenarios","acceptance","decisions"].includes(view))detailEl.insertAdjacentHTML("beforeend",'<button class="ub-btn ghost" data-pm-retry-all>重试当前页面数据</button>');}
      bind();
      restoreInputs();
      mountLifecycle();
      if(sameScreen&&focusKey){const next=[...detailEl.querySelectorAll('input,textarea,select')].find(el=>fieldKey(el)===focusKey);if(next){next.focus({preventScroll:true});if(typeof next.setSelectionRange==='function'&&selectionStart!=null)try{next.setSelectionRange(selectionStart,selectionEnd);}catch(_){}}}
      if(library||!p)return;
      if(["facts","files","stages","scenarios","decisions"].includes(view)&&!brainCache[selected]&&!brainErrors[selected])loadBrain(selected);
      if(["actions","scenarios","acceptance"].includes(view)||(view==="stages"&&viewStageKey)){if(!opsCache[selected]&&!opsErrors[selected])loadOps(selected);}
      if(["overview","stages","facts","files"].includes(view)&&!intelligenceCache[selected]&&!intelligenceErrors[selected])loadIntelligence(selected);
      if(!workspaceCache[key]&&!workspaceErrors[key])loadWorkspace(selected,view);
    }
    function bind(){
      detailEl.querySelectorAll("[data-pm-retry-all]").forEach(b=>b.onclick=()=>{delete brainErrors[selected];delete opsErrors[selected];delete intelligenceErrors[selected];render();});
      const selectedProject=projects.find(p=>p.id===selected),perms=selectedProject?.permissions||{};
      const hide=selector=>detailEl.querySelectorAll(selector).forEach(el=>el.remove());
      if(!perms.manage)hide('[data-pm-archive]');
      if(!perms.delete)hide('[data-pm-purge]');
      if(!perms.duplicate)hide('[data-pm-copy]');
      if(!perms.edit){
        hide('[data-pm-meta],[data-pm-open],[data-pm-ai]');
        detailEl.querySelectorAll('.pm-meta-edit input,.pm-meta-edit select').forEach(el=>el.disabled=true);
      }
      if(!perms.edit){hide('[data-pm-decision],[data-pm-extract],[data-pm-confirm-meeting],[data-pm-item],[data-pm-scenario],[data-pm-package],[data-pm-golden],[data-pm-slo],[data-pm-opt],[data-pw-file-save],[data-pw-extract-save]');detailEl.querySelectorAll('.pm-ops input,.pm-ops textarea,.pm-ops select,.pm-brain-form input,.pm-brain-form select').forEach(el=>el.disabled=true);}
      detailEl.querySelectorAll('[data-pm-retry-context]').forEach(b=>b.onclick=()=>{delete brainErrors[selected];loadBrain(selected);});
      const heading=detailEl.querySelector('.pm-eyebrow');
      if(heading)heading.textContent='项目工作区 · '+(PM_ROLE[selectedProject?.role]||'权限待确认');
      listEl.querySelectorAll('[data-pm-select]').forEach(b=>b.onclick=()=>{const id=b.dataset.pmSelect,saved=ui?.readViewPreference(preferenceStorage(),userId,id),work=ui?.workStage(projects.find(x=>x.id===id),brainCache[id],intelligenceCache[id]);return navigate(id,saved?.view||"stages",saved?.viewStageKey||(saved?null:work?.key||"discovery"));});
      overlay.querySelectorAll('[data-pm-library]').forEach(b=>b.onclick=()=>navigate(selected,"library"));
      overlay.querySelectorAll('[data-pw-view]').forEach(b=>b.onclick=()=>navigate(selected,b.dataset.pwView));
      detailEl.querySelectorAll('[data-pm-stage-view]').forEach(b=>b.onclick=()=>navigate(selected,"stages",b.dataset.pmStageView));
      detailEl.querySelectorAll('[data-pm-retry-source]').forEach(b=>b.onclick=()=>{const kind=b.dataset.pmRetrySource;if(kind==='brain'){delete brainCache[selected];delete brainErrors[selected];loadBrain(selected);}if(kind==='intelligence'){delete intelligenceCache[selected];delete intelligenceErrors[selected];loadIntelligence(selected);}if(kind==='ops'){delete opsCache[selected];delete opsErrors[selected];loadOps(selected);}render();});
      async function updateWorkStage(stageKey,expectedVersion){const id=selected;try{const d=await intelligenceApi({action:"updateWorkStage",projectId:id,stageKey,expectedVersion});stageFeedback.set(id,{message:"工作阶段已更新；阶段门与审批保持独立。",undo:d.undo});delete intelligenceCache[id];delete brainCache[id];await Promise.all([loadIntelligence(id),loadBrain(id)]);}catch(e){stageFeedback.set(id,{message:e.message||"工作阶段保存失败，请重新读取后重试。"});delete intelligenceCache[id];await loadIntelligence(id);}if(selected===id)render();}
      detailEl.querySelectorAll('[data-pm-work-stage]').forEach(el=>el.onchange=()=>{el.disabled=true;return updateWorkStage(el.value,intelligenceCache[selected]?.stage?.version);});
      detailEl.querySelectorAll('[data-pm-undo-stage]').forEach(el=>el.onclick=()=>{const undo=stageFeedback.get(selected)?.undo;if(undo){el.disabled=true;return updateWorkStage(undo.stageKey,undo.expectedVersion);}});
      detailEl.querySelectorAll('[data-pw-retry]').forEach(b=>b.onclick=()=>{const key=selected+":"+view;delete workspaceErrors[key];delete workspaceCache[key];loadWorkspace(selected,view);render();});
      detailEl.querySelectorAll('[data-pw-file-save]').forEach(b=>b.onclick=async()=>{const name=document.getElementById("pwFileName")?.value.trim(),category=document.getElementById("pwFileCategory")?.value.trim()||"other",storageRef=document.getElementById("pwFileRef")?.value.trim()||"";if(!name){alert("请填写文件名");return;}try{await workspaceApi({action:"registerFile",projectId:selected,file:{name,category,storageRef,fileType:(name.split('.').pop()||'').toLowerCase()}});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-extract-save]').forEach(b=>b.onclick=async()=>{const fileId=b.dataset.pwExtractSave,key=detailEl.querySelector('[data-pw-extract-key="'+CSS.escape(fileId)+'"]')?.value.trim(),label=detailEl.querySelector('[data-pw-extract-label="'+CSS.escape(fileId)+'"]')?.value.trim(),raw=detailEl.querySelector('[data-pw-extract-value="'+CSS.escape(fileId)+'"]')?.value.trim();if(!key){alert("请填写结构化字段键");return;}let value=raw;try{value=JSON.parse(raw);}catch(_){}try{await workspaceApi({action:"saveExtraction",projectId:selected,extraction:{fileId,type:"fact",key,label,value,confidence:.7}});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-extract-review]').forEach(b=>b.onclick=async()=>{const tip=b.dataset.decision==="approve"?"审核通过后会沉淀为正式项目数据。":"驳回后该提取项不会进入正式项目数据。";if(!confirm(tip+"是否继续？"))return;try{await workspaceApi({action:"reviewExtraction",projectId:selected,id:b.dataset.pwExtractReview,decision:b.dataset.decision});delete workspaceCache[selected+":"+view];delete workspaceCache[selected+":data"];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-member-save]').forEach(b=>b.onclick=async()=>{const userId=Number(document.getElementById("pwMemberId")?.value),role=document.getElementById("pwMemberRole")?.value;if(!userId){alert("请填写有效用户ID");return;}try{await workspaceApi({action:"updateMember",projectId:selected,userId,role});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-member-remove]').forEach(b=>b.onclick=async()=>{if(!confirm("移除后该成员将无法访问此项目，是否继续？"))return;try{await workspaceApi({action:"removeMember",projectId:selected,userId:Number(b.dataset.pwMemberRemove)});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pw-profile-save]').forEach(b=>b.onclick=async()=>{try{await workspaceApi({action:"updateProfile",projectId:selected,profile:{organizationId:document.getElementById("pwOrgId")?.value.trim(),departmentId:document.getElementById("pwDeptId")?.value.trim(),visibility:document.getElementById("pwVisibility")?.value,confidentialityLevel:document.getElementById("pwConf")?.value}});delete workspaceCache[selected+":"+view];await loadWorkspace(selected,view);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-decision]').forEach(b=>b.onclick=async()=>{const topic=document.getElementById("pmDecisionTopic")?.value.trim(),owner=document.getElementById("pmDecisionOwner")?.value||"";if(!topic){alert("请先填写决策议题");return;}try{await brainApi({action:"createDecision",projectId:selected,decision:{topic,owner,stageKey:brainCache[selected]?.lifecycle?.current||"feasibility"}});delete brainCache[selected];await loadBrain(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-extract]').forEach(b=>b.onclick=async()=>{const title=document.getElementById("pmMeetingTitle")?.value.trim(),content=document.getElementById("pmMeetingText")?.value.trim();if(!content){alert("请先粘贴会议纪要");return;}b.disabled=true;try{const d=await opsApi({action:"extractMeeting",projectId:selected,title,content});alert("已形成候选：决定 "+d.extraction.summary.decisions+" 项、任务 "+d.extraction.summary.tasks+" 项、风险 "+d.extraction.summary.risks+" 项。确认前不会写入正式台账。");delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}finally{b.disabled=false;}});
      detailEl.querySelectorAll('[data-pm-confirm-meeting]').forEach(b=>b.onclick=async()=>{if(!confirm("确认后，全部候选决定、任务和风险将进入正式台账。是否继续？"))return;try{const d=await opsApi({action:"confirmMeeting",projectId:selected,meetingId:b.dataset.pmConfirmMeeting,confirmAll:true});alert("已入台账：决定 "+d.decisionCount+" 项、任务 "+d.taskCount+" 项、风险 "+d.riskCount+" 项");delete opsCache[selected];delete brainCache[selected];await Promise.all([loadOps(selected),loadBrain(selected)]);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-item]').forEach(b=>b.onclick=async()=>{
        if(b.disabled)return;const projectId=selected,type=b.dataset.pmItem,id=b.dataset.id,status=b.dataset.status,extra={};
        if(['done','mitigated','closed'].includes(status)){
          const evidence=prompt('完成或缓释必须提供本项目有效证据ID（多个用逗号分隔）。仅填写说明不能作为完成证据。','');if(evidence===null)return;
          extra.evidenceIds=[...new Set(evidence.split(/[,，、\s]+/).map(x=>x.trim()).filter(Boolean))];if(!extra.evidenceIds.length){alert('请先登记并填写本项目有效证据ID；本次未修改状态。');return;}
          const item=(type==='task'?opsCache[projectId]?.tasks:opsCache[projectId]?.risks)?.find(x=>x.id===id),stageKey=prompt('关联阶段键（可选，如 implementation、post_investment；留空保留原关联）',item?.stageKey||'');if(stageKey===null)return;
          if(stageKey.trim()&&!ui?.stage(stageKey.trim())){alert('阶段键无效，请选择现有八阶段之一；本次未修改状态。');return;}if(stageKey.trim())extra.stageKey=stageKey.trim();
          const milestoneId=prompt('关联本项目里程碑ID（可选，留空保留原关联）',item?.milestoneId||'');if(milestoneId===null)return;if(milestoneId.trim())extra.milestoneId=milestoneId.trim();
        }
        b.disabled=true;try{await opsApi({action:"updateItem",projectId,type,id,status,...extra});delete opsCache[projectId];await loadOps(projectId);}catch(e){alert(e.message||'状态未保存，请核对证据后重试。');}finally{if(b.isConnected)b.disabled=false;}
      });
      detailEl.querySelectorAll('[data-pi-gate]').forEach(b=>b.onclick=async()=>{const name=prompt("阶段门名称，例如：可研审查","");if(!name)return;const plannedDate=prompt("计划日期（YYYY-MM-DD，可留空）","");if(plannedDate===null)return;try{await intelligenceApi({action:"saveGate",projectId:selected,gate:{name,status:"in_progress",plannedDate}});delete intelligenceCache[selected];await loadIntelligence(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pi-milestone]').forEach(b=>b.onclick=async()=>{const name=prompt("里程碑名称，例如：可研初稿","");if(!name)return;const progress=prompt("当前真实完成度（0—100）","0");if(progress===null)return;const owner=prompt("负责人（可留空）","");if(owner===null)return;try{await intelligenceApi({action:"saveMilestone",projectId:selected,milestone:{name,status:Number(progress)>=100?"done":"in_progress",progress:Number(progress)||0,owner}});delete intelligenceCache[selected];await loadIntelligence(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pi-deliverable]').forEach(b=>b.onclick=async()=>{const name=prompt("阶段成果名称，例如：可研报告","");if(!name)return;const dueDate=prompt("计划完成日期（YYYY-MM-DD，可留空）","");if(dueDate===null)return;try{await intelligenceApi({action:"saveDeliverable",projectId:selected,deliverable:{name,status:"not_started",required:true,dueDate}});delete intelligenceCache[selected];await loadIntelligence(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-scenario]').forEach(b=>b.onclick=async()=>{const kind=document.getElementById("pmScenarioKind")?.value||"baseline",name=document.getElementById("pmScenarioName")?.value.trim();try{await opsApi({action:"saveScenario",projectId:selected,scenario:{kind,name}});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-package]').forEach(b=>b.onclick=async()=>{const scenarioId=document.getElementById("pmPackageScenario")?.value,evidenceIds=(brainCache[selected]?.artifacts||[]).map(x=>x.id).filter(Boolean);try{const d=await opsApi({action:"createDecisionPackage",projectId:selected,scenarioId,evidenceIds,title:"投资决策包"});alert(d.package.audit.passed?"投资决策包已通过提交前审计":"决策包已生成但被阻断：\n- "+d.package.audit.blockers.join("\n- "));delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-golden]').forEach(b=>b.onclick=async()=>{const numericErrors=prompt("关键数字错误数（必须如实填写）","0");if(numericErrors===null)return;const evidenceCoverage=prompt("证据覆盖率（0—100）","80");if(evidenceCoverage===null)return;const manualMinutes=prompt("人工耗时（分钟）","");if(manualMinutes===null)return;try{await opsApi({action:"saveEvaluation",projectId:selected,type:"golden_project",status:Number(numericErrors)===0?"recorded":"failed",result:{numericErrors:Number(numericErrors)||0,evidenceCoverage:Number(evidenceCoverage)||0,manualMinutes:Number(manualMinutes)||0,recordedAt:Date.now()}});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-slo]').forEach(b=>b.onclick=async()=>{const concurrency=prompt("实测并发人数（目标50）","50");if(concurrency===null)return;const p95Ms=prompt("核心路径P95耗时（毫秒）","5000");if(p95Ms===null)return;const successRate=prompt("成功率（0—100）","99");if(successRate===null)return;const recoveryRate=prompt("失败恢复率（0—100）","95");if(recoveryRate===null)return;const result={concurrency:Number(concurrency)||0,p95Ms:Number(p95Ms)||0,successRate:(Number(successRate)||0)/100,recoveryRate:(Number(recoveryRate)||0)/100,passed:Number(concurrency)>=50&&Number(p95Ms)<=5000&&Number(successRate)>=99&&Number(recoveryRate)>=95};try{await opsApi({action:"saveEvaluation",projectId:selected,type:"slo_load",status:result.passed?"passed":"failed",result});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      detailEl.querySelectorAll('[data-pm-opt]').forEach(b=>b.onclick=async()=>{const title=document.getElementById("pmOptTitle")?.value.trim(),evidence=document.getElementById("pmOptEvidence")?.value.trim(),actualBenefit=document.getElementById("pmOptBenefit")?.value.trim();if(!title){alert("请填写优化事项");return;}try{await opsApi({action:"saveOptimization",projectId:selected,title,evidence,actualBenefit,status:actualBenefit?"verified":"candidate"});delete opsCache[selected];await loadOps(selected);}catch(e){alert(e.message);}});
      async function openEditor(b,id){b.disabled=true;try{if(options.preserveDraft)await options.preserveDraft({projectId:selected,view,viewStageKey});if(options.openAiReport)await options.openAiReport(id);else if(options.openProject)await options.openProject(id);if(!overlay.isConnected)activeCleanup?.();}catch(e){alert(e.message||"进入 AI 可研失败，已保留当前页面。");}finally{b.disabled=false;}}
      detailEl.querySelectorAll('[data-pm-ai]').forEach(b=>b.onclick=()=>openEditor(b,b.dataset.pmAi));
      detailEl.querySelectorAll('[data-pm-preview-project]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await openReportPreview(b.dataset.pmPreviewProject,b.dataset.pmPreviewVersion);}catch(e){alert(e.message||"打开报告预览失败");}finally{b.disabled=false;}});
      detailEl.querySelectorAll('[data-pm-open]').forEach(b=>b.onclick=()=>openEditor(b,b.dataset.pmOpen));
      detailEl.querySelectorAll('[data-pm-copy]').forEach(b=>b.onclick=async()=>{const src=projects.find(p=>p.id===b.dataset.pmCopy),name=prompt("副本名称",(src?.name||"未命名项目")+"（副本）");if(!name)return;await api({action:"duplicate",sourceId:b.dataset.pmCopy,id:options.genId(),name});await load();});
      detailEl.querySelectorAll('[data-pm-archive]').forEach(b=>b.onclick=async()=>{const archived=b.dataset.value==="1";if(!confirm(archived?"归档后不会出现在进行中列表，可随时恢复。是否继续？":"恢复该项目到进行中列表？"))return;await api({action:"setArchived",id:b.dataset.pmArchive,archived});if(archived&&options.currentId&&b.dataset.pmArchive===options.currentId())options.newProject&&options.newProject(true);await load();});
      detailEl.querySelectorAll('[data-pm-purge]').forEach(b=>b.onclick=async()=>{try{await purgeProject(b.dataset.pmPurge);}catch(e){alert(e.message||"删除失败");}});
      detailEl.querySelectorAll('[data-pm-meta]').forEach(b=>b.onclick=async()=>{const tags=document.getElementById("pmTags").value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean),status=document.getElementById("pmStatus").value,saved=await api({action:"updateMeta",id:b.dataset.pmMeta,status,tags});if(options.updateCurrentMeta&&b.dataset.pmMeta===options.currentId())options.updateCurrentMeta({status,tags},saved.updatedAt);await load();});
    }
    async function load(){try{const r=await fetch("/api/projects",{headers:headers()}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"加载失败");projects=d.list||[];render();}catch(e){listEl.hidden=false;detailEl.hidden=true;listEl.innerHTML='<div class="pm-detail-empty"><b>项目索引加载失败</b><span>'+esc(e.message)+'</span><button class="ub-btn" id="pmRetryList">重试加载项目</button></div>';listEl.querySelector("#pmRetryList").onclick=load;}}
    function onHistory(){const r=root.ProjectWorkspaceUI&&root.ProjectWorkspaceUI.parseRoute(location.hash);if(!overlay.isConnected){activeCleanup?.();return;}if(!r){guard.run(options.preserveDraft?()=>options.preserveDraft({projectId:selected,view,viewStageKey}):null,()=>{activeCleanup?.();overlay.remove();},e=>{navigationError=e.message||"草稿保存失败，已保留当前页面。";setRoute(selected,view,true);render();});return;}navigate(r.projectId||selected,r.view,r.viewStageKey||null,true);}
    function close(){return guard.run(options.preserveDraft?()=>options.preserveDraft({projectId:selected,view,viewStageKey}):null,()=>{activeCleanup?.();overlay.remove();if(returnHash)history.pushState(null,"",returnHash);else history.pushState(null,"",location.pathname+location.search);},e=>{navigationError=e.message||"草稿保存失败，已保留当前页面。";render();});}
    overlay.onclick=e=>{if(e.target===overlay)close();};document.getElementById("ppClose").onclick=close;
    addEventListener("popstate",onHistory);
    addEventListener("hashchange",onHistory);
    activeCleanup=()=>{guard.cancel();disposeLifecycle();removeEventListener("popstate",onHistory);removeEventListener("hashchange",onHistory);removeEventListener('beforeunload',beforeUnload);activeCleanup=null;};
    document.getElementById("pmSearch").oninput=e=>{query=e.target.value;render();};document.getElementById("pmSort").onchange=e=>{sort=e.target.value;render();};
    document.querySelectorAll('[data-pm-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.pmTab;document.querySelectorAll('[data-pm-tab]').forEach(x=>x.classList.toggle("active",x===b));render();});
    document.querySelectorAll('[data-pm-head-view]').forEach(b=>{if(b.dataset.pmHeadView!=="library")b.textContent="本项目 · "+({data:"数据",decisions:"决策",versions:"成果"}[b.dataset.pmHeadView]||"");b.onclick=()=>{const next=b.dataset.pmHeadView;if(next!=="library"&&!projects.some(p=>p.id===selected)){alert("请先从项目库选择项目；数据、决策和成果均属于所选项目。");return;}return navigate(selected,next);};});
    document.getElementById("pmNew").onclick=async()=>{if(confirm("即将离开项目库并创建项目。是否继续？")&&await close())options.newProject&&options.newProject();};
    setRoute(selected,view,!!initialRoute);
    await load();
  }
  root.ProjectManager={open,health,matches,displayType};
  if(typeof module==="object"&&module.exports)module.exports={health,matches,displayType,renderDetail:detail,navigationGuard};
})(typeof window!=="undefined"?window:globalThis);
