import test from 'node:test';
import assert from 'node:assert/strict';
import {createD1Shim} from '../local-server/d1-shim.js';
import {testDatabaseUrl} from '../scripts/require-test-database.mjs';
import {ensureInvestmentTables} from '../functions/api/investmentops.js';
import {ensureStep4,mutateStep4,readStep4,tickStep4} from '../functions/api/_investment-step4.js';
import {withProjectMutation} from '../functions/api/_lifecycle-integrity.js';
import {resolveProjectAccess,ensureProjectMemberships} from '../functions/api/_project-access.js';
import {reportEvidenceHash as hash} from '../functions/api/_report-trusted-evaluation.js';
import {wikiPageAccessible,wikiRetrievalAccess} from '../functions/api/_wiki-source-access.js';
const target=testDatabaseUrl();
test('步骤4真实数据库闭环：目标→独立复核→整改→经验→RAG/撤回/失效/周期',{skip:!target},async()=>{
 const DB=createD1Shim(target),env={DB,DEPLOY_MODE:'local',AI:{run:async(_,b)=>({data:b.text.map(()=>[.1,.2])})},VECTORIZE:{upsert:async()=>{},deleteByIds:async()=>{}}},pid=crypto.randomUUID();
 try{
  await ensureInvestmentTables(env);await ensureProjectMemberships(env);await ensureStep4(env);await ensureStep4(env);
  const users=[];for(let i=0;i<3;i++){const name='[系统测试]step4-'+crypto.randomUUID();await DB.prepare('INSERT INTO users(username,pass_hash,salt,created_at) VALUES(?,?,?,?)').bind(name,'disabled','disabled',Date.now()).run();users.push(Number((await DB.prepare('SELECT id FROM users WHERE username=?').bind(name).first()).id));}
  const [owner,reviewer,outsider]=users;await DB.prepare('INSERT INTO projects(id,user_id,name,data,updated_at) VALUES(?,?,?,?,?)').bind(pid,owner,'[系统测试]后评价','{}',Date.now()).run();
  await DB.prepare("INSERT INTO project_memberships(project_id,user_id,role,status,created_at,updated_at) VALUES(?,?,'EDITOR','active',?,?)").bind(pid,reviewer,Date.now(),Date.now()).run();
  for(const u of [owner,reviewer])await DB.prepare('INSERT INTO investment_fact_verifiers(project_id,user_id,basis,active,version,updated_at) VALUES(?,?,?,1,1,?)').bind(pid,u,'测试授权',Date.now()).run();
  const sourceId=crypto.randomUUID(),approvalId=crypto.randomUUID(),proofId=crypto.randomUUID();
  await DB.prepare('INSERT INTO report_source_artifacts(id,project_id,user_id,content_hash,storage_key,file_name,mime_type,size_bytes,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(sourceId,pid,owner,'test-hash','test-key','[系统测试]批准.txt','text/plain',10,Date.now()).run();
  const source=await DB.prepare('SELECT id,content_hash,storage_key,file_name,size_bytes FROM report_source_artifacts WHERE id=?').bind(sourceId).first();
  await DB.prepare("INSERT INTO investment_formal_facts(id,project_id,event_id,kind,round,version,status,payload_json,source_id,source_hash,created_by,verified_by,updated_at) VALUES(?,?,?,'original',1,2,'verified',?,?,?,?,?,?)").bind(approvalId,pid,'event',JSON.stringify({title:'批准',date:'2026-01-01',amount:'100',currency:'CNY',amountBasis:'含税'}),sourceId,await hash(source),owner,reviewer,Date.now()).run();
  await DB.prepare("INSERT INTO project_facts(id,project_id,user_id,fact_type,fact_key,value_json,status,source_ref,created_by,created_at,updated_at) VALUES(?,?,?,'operations','proof',?,'confirmed','第1页','reviewer',?,?)").bind(proofId,pid,owner,JSON.stringify('完成整改并验收，支出90万元'),Date.now(),Date.now()).run();
  const call=(b,u=owner)=>withProjectMutation(env,{userId:u},pid,'edit',(tx,a)=>mutateStep4(tx,{userId:u},a,b));
  const read=async()=>readStep4(env,{userId:owner},await resolveProjectAccess(env,owner,pid));
  const metric={metricKey:'支出',unit:'万元',currency:'CNY',basis:'含税',periodStart:'2026-01-01',periodEnd:'2026-12-31',value:100,confirmed:true,quote:'计划支出100万元',locator:'第1页',sourceEvidenceId:sourceId};
  await assert.rejects(call({action:'evaluationCreate',title:'评价',approvalId,requestKey:'bad',targets:[{...metric,sourceEvidenceId:proofId}]}),{status:400});
  const created=await call({action:'evaluationCreate',title:'[系统测试]专项后评价',approvalId,requestKey:'one',targets:[metric]});
  assert.equal(created.snapshot.comparison.rows[0].actual,null);
  assert.equal((await call({action:'evaluationCreate',title:'[系统测试]专项后评价',approvalId,requestKey:'one',targets:[metric]})).reused,true);
  await call({action:'evaluationSubmit',id:created.id,expectedVersion:1,reason:'目标经批准原文核对，实际缺失已列明'});
  await assert.rejects(call({action:'evaluationReview',id:created.id,expectedVersion:2,reason:'自审',confirmed:true,approved:true}),{status:403});
  await call({action:'evaluationReview',id:created.id,expectedVersion:2,reason:'已核对缺失范围，不视为绩效合格',confirmed:true,approved:true},reviewer);
  const fix=await call({action:'rectificationCreate',id:'fix-'+crypto.randomUUID(),evaluationId:created.id,issue:'补齐实际台账',cause:'尚未录入',ownerId:owner,dueDate:'2026-10-01',dueBasis:'专项整改计划'});
  await assert.rejects(call({action:'rectificationSubmit',id:fix.id,expectedVersion:1,sourceEvidenceId:'missing',locator:'第1页',reason:'已完成'}));
  await call({action:'rectificationSubmit',id:fix.id,expectedVersion:1,sourceEvidenceId:proofId,locator:'第1页',reason:'已核对'});
  await call({action:'rectificationReview',id:fix.id,expectedVersion:2,confirmed:true,approved:false,reason:'需补充解释'},reviewer);
  assert.equal((await DB.prepare('SELECT status FROM project_tasks WHERE id=?').bind(fix.id).first()).status,'open');
  await call({action:'rectificationSubmit',id:fix.id,expectedVersion:3,sourceEvidenceId:proofId,locator:'第1页',reason:'补充核对完成'});
  await call({action:'rectificationReview',id:fix.id,expectedVersion:4,confirmed:true,approved:true,reason:'逐项复核完成'},reviewer);
  const exp=await call({action:'experienceSave',evaluationId:created.id,expectedVersion:0,title:'[系统测试]经验',content:'必须保持批准目标、实际数据及整改证据的完整关联，不能用预测数替代实际数。对于没有完成收集的指标，应当明确标为缺失并注明范围，不得填零或者给出满分。',reviewDate:'2099-01-01',rectificationIds:[fix.id]});
  await call({action:'experienceSubmit',id:exp.id,expectedVersion:1});
  await assert.rejects(call({action:'experienceReview',id:exp.id,expectedVersion:2,confirmed:true,approved:true,reason:'自己审核'}),{status:403});
  await call({action:'experienceReview',id:exp.id,expectedVersion:2,confirmed:true,approved:true,reason:'经验与来源一致'},reviewer);
  const goodAI=env.AI;env.AI={run:async()=>{throw Error('offline');}};await assert.rejects(call({action:'experiencePublish',id:exp.id,expectedVersion:3}));env.AI=goodAI;
  assert.equal((await read()).records.find(x=>x.id===exp.id).status,'approved');
  await call({action:'experiencePublish',id:exp.id,expectedVersion:3});
  let page=await DB.prepare('SELECT * FROM wiki_pages WHERE id=?').bind(exp.id).first();assert.equal(await wikiPageAccessible(env,owner,page),true);assert.equal(await wikiPageAccessible(env,outsider,page),false);
  const title=('【Wiki】'+page.id+'｜'+page.title).slice(0,80),vectorId=JSON.parse(page.vector_ids)[0];
  assert.equal((await wikiRetrievalAccess(env,owner,[title]))(title,vectorId),true);
  assert.equal((await wikiRetrievalAccess(env,owner,[title]))(title,'old-vector'),false);
  assert.equal((await wikiRetrievalAccess(env,outsider,[title]))(title,vectorId),false);
  await DB.prepare("UPDATE project_memberships SET status='removed' WHERE project_id=? AND user_id=?").bind(pid,reviewer).run();
  assert.equal(await wikiPageAccessible(env,reviewer,page),false);
  await DB.prepare("UPDATE project_memberships SET status='active' WHERE project_id=? AND user_id=?").bind(pid,reviewer).run();
  await DB.prepare("UPDATE project_facts SET status='rejected' WHERE id=?").bind(proofId).run();
  assert.equal((await wikiRetrievalAccess(env,owner,[title]))(title,vectorId),false);
  await DB.prepare("UPDATE project_facts SET status='confirmed' WHERE id=?").bind(proofId).run();
  assert.equal(await wikiPageAccessible(env,owner,{...page,expiry_date:'2000-01-01'}),false);
  await assert.rejects(call({action:'experiencePublish',id:exp.id,expectedVersion:3}),{status:409});
  await call({action:'experienceWithdraw',id:exp.id,expectedVersion:4,reason:'调整经验'});page=await DB.prepare('SELECT * FROM wiki_pages WHERE id=?').bind(exp.id).first();assert.equal(await wikiPageAccessible(env,owner,page),false);
  await DB.prepare("UPDATE project_facts SET status='rejected' WHERE id=?").bind(proofId).run();
  await call({action:'step4Refresh'});assert.ok((await read()).notices.some(n=>n.id==='review-'+fix.id));assert.equal((await DB.prepare('SELECT status FROM project_tasks WHERE id=?').bind(fix.id).first()).status,'open');
  await call({action:'evaluationSchedule',expectedVersion:0,enabled:true,nextDate:'2026-01-01',intervalDays:90,basis:'试点季度专项评价'});
  await tickStep4(env);await tickStep4(env);assert.equal((await read()).notices.filter(n=>n.id.startsWith('scheduled-')).length,1);
  const notice=(await read()).notices.find(n=>n.id.startsWith('scheduled-'));
  await call({action:'evaluationNoticeComplete',id:notice.id,evaluationId:created.id});assert.equal((await read()).notices.filter(n=>n.id.startsWith('scheduled-')).length,0);
  const replacementId=crypto.randomUUID();await DB.prepare("INSERT INTO project_facts(id,project_id,user_id,fact_type,fact_key,value_json,status,source_ref,created_by,created_at,updated_at) VALUES(?,?,?,'operations','replacement',?,'confirmed','第2页','reviewer',?,?)").bind(replacementId,pid,owner,JSON.stringify('重新验收完成'),Date.now(),Date.now()).run();
  await call({action:'rectificationSubmit',id:fix.id,expectedVersion:5,sourceEvidenceId:replacementId,locator:'第2页',reason:'旧证据失效后补充新证据'});
  await call({action:'rectificationReview',id:fix.id,expectedVersion:6,confirmed:true,approved:true,reason:'核对替代证据'},reviewer);
  await call({action:'step4Refresh'});assert.equal((await read()).notices.some(n=>n.id==='review-'+fix.id),false);
  assert.equal((await DB.prepare('SELECT status FROM project_tasks WHERE id=?').bind(fix.id).first()).status,'done');
 }finally{await DB._close();}
});
