const test=require("node:test");
const assert=require("node:assert/strict");
global.window=global;
require("../ppt-design-ir.js");require("../ppt-design-ir-v2.js");const IR=require("../ppt-premium-design.js");
const Director=require("../ppt-content-director.js");require("../ppt-design-learning.js");require("../ppt-component-registry.js");const Benchmark=require("../ppt-quality-benchmark.js");

const evidencePack={assets:[{id:"a1",name:"项目资料.txt",kind:"text",text:"项目总投资43.5亿元，建设工期16个季度。项目IRR为5.62%。应重点控制建设成本和工期风险。"}],facts:[{statement:"项目总投资43.5亿元",values:["43.5亿元"],sourceLabel:"项目资料.txt",locator:"第1行"},{statement:"建设工期16个季度",values:["16个季度"],sourceLabel:"项目资料.txt",locator:"第1行"},{statement:"项目IRR为5.62%",values:["5.62%"],sourceLabel:"项目资料.txt",locator:"第1行"}],summary:{assetCount:1}};

test("内容导演会补齐页面说明并把空内容转成明确证据缺口",()=>{const plan=Director.applyToDeck({title:"项目汇报",sourceText:evidencePack.assets[0].text,evidencePack,slides:[{type:"content",layoutId:"metric",title:"关键指标"},{type:"content",layoutId:"image-hero",title:"项目区位"}]});assert.equal(plan.contentDirection.totalPages,2);assert.equal(plan.slides[0].designBrief.componentId,"premium-metrics");assert.ok(plan.slides[0].content.metrics.length>=2);assert.equal(plan.slides[1].contentStatus,"evidence-gap");assert.ok(plan.slides[1].content.items.length>=3);});

test("十二类高级组件直接进入Design IR v3",()=>{const slides=[{layoutId:"cover",title:"项目决策汇报"},{layoutId:"agenda",title:"汇报结构",bullets:["项目价值","关键指标","实施计划"]},{layoutId:"bullets",title:"核心判断",claim:"项目具备推进条件",bullets:["目标明确","成本可控","风险可管"]},{layoutId:"metric",title:"关键指标",content:{metrics:[{label:"总投资",value:"43.5亿元"},{label:"IRR",value:"5.62%"}]}},{layoutId:"comparison",title:"方案选择",content:{columns:[{title:"方案A",items:["稳健"]},{title:"方案B",items:["增强"]}]}},{layoutId:"timeline",title:"实施路径",content:{steps:[{label:"立项",text:"确认边界"},{label:"设计",text:"完成报批"},{label:"建设",text:"控制进度"}]}},{layoutId:"risk",title:"风险应对",bullets:["成本风险","工期风险","市场风险","合规风险"]},{layoutId:"chart-bar",title:"投资变化",content:{series:[{label:"2026",value:30},{label:"2027",value:70}]}},{layoutId:"table",title:"方案数据",content:{headers:["方案","投资"],rows:[["A",100],["B",120]]}},{layoutId:"conclusion",title:"建议继续推进",bullets:["核实参数","完成复核","明确责任"]}],plan={title:"项目汇报",slides};slides.forEach((slide,i)=>{const scene=IR.buildScene(slide,plan,i);assert.equal(scene.version,3,slide.layoutId);assert.ok(scene.elements.length>=8,slide.layoutId);});assert.ok(IR.buildScene(slides[7],plan,7).elements.some(x=>x.type==="chart"));assert.ok(IR.buildScene(slides[8],plan,8).elements.some(x=>x.type==="table"));});

test("流程闭环与时间里程碑使用不同的高级组件",()=>{const timeline={layoutId:"timeline",title:"建设进度",content:{steps:[{label:"开工",text:"确认条件"},{label:"封顶",text:"完成主体"}]}},process={layoutId:"process",title:"审核闭环",content:{steps:[{label:"采集",text:"形成证据"},{label:"复核",text:"核对规则"},{label:"签发",text:"形成成果"}]}},plan={title:"项目汇报",slides:[timeline,process]};const timeScene=IR.buildScene(timeline,plan,0),processScene=IR.buildScene(process,plan,1);assert.equal(timeScene.composition,"premium-roadmap");assert.equal(processScene.composition,"premium-process");assert.ok(timeScene.elements.some(x=>x.type==="text"&&x.text==="MILESTONE ROADMAP"));assert.ok(processScene.elements.some(x=>x.type==="text"&&x.text==="EXECUTION PATH"));});

test("新版质量基准不会把空白卡片页误判成高分",()=>{const empty={title:"空白",slides:[{layoutId:"bullets",title:"只有标题",bullets:[]}]},low=Benchmark.inspect(empty);assert.ok(low.score<70);const rich=Director.applyToDeck({title:"项目汇报",sourceText:evidencePack.assets[0].text,evidencePack,slides:[{layoutId:"metric",title:"关键指标",sources:["项目资料.txt"]},{layoutId:"timeline",title:"实施路径",bullets:["立项：确认边界","设计：完成报批","建设：控制进度"],sources:["项目资料.txt"]}]});const high=Benchmark.inspect(rich);assert.ok(high.dimensions.pageQuality>low.dimensions.pageQuality);});

test("设计偏好可导出、导入并持续影响权重",()=>{const L=global.PptDesignLearning;L.clear();L.record({action:"accept",componentId:"premium-metrics"});const profile=L.exportProfile();assert.equal(profile.weights.component["premium-metrics"],2);L.clear();L.importProfile(profile);assert.equal(L.adjustment("component","premium-metrics"),2);});
