const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
test('研究退出默认打开正式项目，AI历史入口保持可研路由，保存失败不导航',async()=>{
 for(const hash of ['', '#aireport']){const {ctx,sent}=harness();let remembered;ctx.rememberActiveProjectId=id=>remembered=id;await ctx.ResearchUI.bootstrap();await ctx.ResearchUI.leaveForProject('legacy_a',{hash});const target=new URL(sent.find(x=>x.navigate).navigate);assert.equal(target.search,'');assert.equal(target.hash,hash);assert.equal(remembered,'legacy_a');}
 const src=fs.readFileSync('auth.js','utf8');const fn=src.slice(src.indexOf('async function openAiReportProject('),src.indexOf('async function startApp('));let calls=0,argument;const ui={active:()=>true,leaveForProject:async(id,opts)=>{argument={id,opts};return false;}};const ctx=vm.createContext({window:{ResearchUI:ui},ResearchUI:ui,openProject:()=>{calls++;}});vm.runInContext(fn,ctx);assert.equal(await ctx.openAiReportProject('legacy_b'),false);assert.equal(argument.id,'legacy_b');assert.equal(argument.opts.hash,'#aireport');assert.equal(calls,0);
 ui.leaveForProject=async()=>{throw Error('save failed');};await assert.rejects(()=>ctx.openAiReportProject('legacy_b'),/save failed/);assert.equal(calls,0);
});
function harness(storage=new Map()) {
 const sent=[],elements=new Map(),entry={ok:true,userId:7,study:{researchId:'research_123',title:'研究甲',status:'active',version:1,role:'manager'},run:{researchId:'research_123',runId:'round_123',ordinal:1,status:'active',version:1,epoch:1,state:{materialRefs:[{fileId:'material_a'}]}}};
 function el(){return {append(){},prepend(){},before(){},after(){},replaceChildren(){},style:{},remove(){},showModal(){},close(){}};}
 const ctx={localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},URL,URLSearchParams,AbortSignal,crypto:crypto.webcrypto,setTimeout,clearTimeout,console,location:{search:'?research=research_123',href:'http://localhost/?research=research_123',assign:u=>sent.push({navigate:u})},document:{getElementById:id=>elements.get(id)||null,createElement:()=>el(),body:{...el(),firstChild:el()}},authHeaders:()=>({}),mountUserBar(){},fetchOutlines:async()=>{},fetchCalcConfig:async()=>{},renderTOC(){},renderSheet(){},restoreDraft(){},currentProjectId:'formal_old',currentProjectRole:'OWNER',currentProjectReadOnlyData:null,appMode:null,project:{},kbEntries:[{materialRef:{fileId:'material_b'}}],reportDocumentRevision:3,reportCloudPersistedRevision:0,buildDraftData:()=>({project:{name:'研究甲'},chapters:[]}),airSerializableState:()=>({chat:[{content:'未串入正式项目'}]}),setSaveState(){},fetch:async(url,options)=>{sent.push({url,options});const body=options.body&&JSON.parse(options.body);if(body?.action==='save'){if(ctx.failSave)return {json:async()=>({ok:false,error:'模拟失败'})};return {json:async()=>({ok:true,researchId:'research_123',runId:'round_123',epoch:1,acceptedVersion:body.expectedVersion+1})};}return {json:async()=>structuredClone(entry)};}};
 ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);for(const f of ['research-context.js','research-session.js','research-ui.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);return {ctx,sent,entry,storage};
}
test('研究启动清除正式项目指针，保存仅写研究快照并保留可信资料引用',async()=>{const {ctx,sent}=harness();await ctx.ResearchUI.bootstrap();assert.equal(ctx.currentProjectId,null);assert.equal(ctx.ResearchUI.editable(),true);assert.equal(await ctx.ResearchUI.save(),true);const request=sent.find(x=>x.options?.method==='POST');assert.equal(request.url,'/api/research');const data=JSON.parse(request.options.body);assert.equal(data.researchId,'research_123');assert.equal(data.state.draft.project.name,'研究甲');assert.equal(data.state.materialRefs.length,2);assert.equal(sent.some(x=>x.url?.startsWith('/api/projects')),false);});
test('研究保存失败不能切换正式项目，远端废弃拒绝七链迟到返回',async()=>{const {ctx,sent,entry}=harness();await ctx.ResearchUI.bootstrap();ctx.failSave=true;await assert.rejects(()=>ctx.ResearchUI.leaveForProject('formal_next'),/模拟失败/);assert.equal(sent.some(x=>x.navigate),false);ctx.failSave=false;await ctx.ResearchUI.save();for(const chain of ['chat','parameters','calculation','file','report','autosave','export']){const token=ctx.ResearchUI.capture(chain);entry.study.status='abandoned';await assert.rejects(()=>ctx.ResearchUI.guard(token));entry.study.status='active';}});
test('失败草稿刷新后经授权恢复，冲突版本不自动覆盖',async()=>{const first=harness();await first.ctx.ResearchUI.bootstrap();first.ctx.failSave=true;assert.equal(await first.ctx.ResearchUI.save(),false);assert.equal(first.storage.size,1);const next=harness(first.storage);next.ctx.failSave=true;await next.ctx.ResearchUI.bootstrap();assert.equal(next.ctx.ResearchUI.state().aiReport.chat[0].content,'未串入正式项目');assert.equal(next.storage.size,1);const conflict=harness(first.storage);conflict.entry.run.epoch=2;await conflict.ctx.ResearchUI.bootstrap();assert.equal(conflict.sent.some(x=>x.options?.method==='POST'),false);assert.equal(conflict.storage.size,1);});
test('AI编辑只标记待保存，显式刷新保存后不残留伪冲突',async()=>{const {ctx,storage}=harness();await ctx.ResearchUI.bootstrap();const source=fs.readFileSync('aireport.js','utf8').split(/\r?\n/).find(x=>x.startsWith('function airSaveLocalState('));vm.runInContext(source,ctx);let copies=0;const original=ctx.buildDraftData;ctx.buildDraftData=()=>{copies++;return original();};for(let i=0;i<100;i++)ctx.airSaveLocalState();assert.equal(copies,0);assert.equal(storage.size,0);await ctx.ResearchUI.flush();assert.equal(copies,1);assert.equal(storage.size,0);const refreshed=harness(storage);await refreshed.ctx.ResearchUI.bootstrap();assert.equal(refreshed.sent.some(x=>x.options?.method==='POST'),false);});

test('慢请求期间合并编辑，只发送最新快照，旧回执不显示全部已保存',async()=>{
 const {ctx}=harness();await ctx.ResearchUI.bootstrap();const normal=ctx.fetch,states=[],statuses=[];let release,started;
 const began=new Promise(r=>started=r);ctx.setSaveState=s=>statuses.push(s);
 ctx.fetch=async(url,options)=>{const body=options.body&&JSON.parse(options.body);if(body?.action==='save'){states.push(body.state.draft.project.name);if(states.length===1){started();await new Promise(r=>release=r);}}return normal(url,options);};
 let name='first';ctx.buildDraftData=()=>({project:{name}});const saving=ctx.ResearchUI.save();await began;
 for(let i=0;i<100;i++){name='edit-'+i;ctx.reportDocumentRevision++;ctx.ResearchUI.schedule();}
 assert.equal(states.length,1);release();assert.equal(await saving,true);assert.deepEqual(states,['first','edit-99']);assert.equal(statuses.filter(s=>s==='ok').length,1);assert.equal(ctx.reportCloudPersistedRevision,ctx.reportDocumentRevision);
});
test('历史视图显示已提取信息与计算快照而不是瞬时处理占位符',()=>{const source=fs.readFileSync('research-ui.js','utf8').split(/\r?\n/).find(x=>x.startsWith(' function historyText('));const ctx=vm.createContext({});vm.runInContext(source,ctx);const text=ctx.historyText({aiReport:{chat:[{kind:'loading',content:'正在理解项目信息…'},{kind:'text',content:'用户要求'}],extracted:{projectName:'历史甲项目'},calcSummary:{NPV:123}}});assert.match(text,/历史甲项目/);assert.match(text,/NPV：123/);assert.match(text,/用户要求/);assert.doesNotMatch(text,/正在理解/);});
test('恢复成功返回同一研究URL时强制重载，不遗留失效session按钮',async()=>{let confirmAction,reloads=0,assigns=0;const destination='http://localhost/?research=research_123#aireport';const ctx=vm.createContext({current:()=>({study:{researchId:'research_123',visibility:'private'}}),modal:()=>({append(){}}),document:{createElement:()=>({append(){}})},button:(_d,_label,fn)=>{confirmAction=fn;},flush:async()=>true,session:{transition:async()=>({ok:true,researchId:'research_123'})},url:()=>destination,location:{href:destination,reload(){reloads++;},assign(){assigns++;}},busy:false,loaded:true});const source=fs.readFileSync('research-ui.js','utf8').split(/\r?\n/).find(x=>x.startsWith(' async function transition('));vm.runInContext(source,ctx);await ctx.transition('restore');await confirmAction();assert.equal(reloads,1);assert.equal(assigns,0);assert.equal(ctx.loaded,false);});
test('恢复后旧epoch缓存与服务器完全一致则去除伪冲突，不覆盖不同草稿',async()=>{const first=harness();await first.ctx.ResearchUI.bootstrap();first.ctx.failSave=true;await first.ctx.ResearchUI.save();const saved=JSON.parse([...first.storage.values()][0]);const second=harness(first.storage);second.entry.run.epoch=3;second.entry.run.version=9;second.entry.run.state=structuredClone(saved.state);await second.ctx.ResearchUI.bootstrap();assert.equal(second.storage.size,0);assert.equal(second.sent.some(x=>x.options?.method==='POST'),false);const conflict=harness(new Map([['fs_research_7_research_123_round_123',JSON.stringify(saved)]]));conflict.entry.run.epoch=3;conflict.entry.run.version=9;await conflict.ctx.ResearchUI.bootstrap();assert.equal(conflict.storage.size,1);assert.equal(conflict.sent.some(x=>x.options?.method==='POST'),false);});
test('冲突副本独立留存；缓存满时原位保留原件并继续版本校验保存',async()=>{const original={userId:7,researchId:'research_123',runId:'round_123',epoch:1,baseVersion:1,state:{draft:{privateText:'未同步内容'}}},key='fs_research_7_research_123_round_123',raw=JSON.stringify(original);const good=harness(new Map([[key,raw]]));good.entry.run.epoch=3;await good.ctx.ResearchUI.bootstrap();assert.equal(good.storage.get(key+'_conflict_1_1'),raw);await good.ctx.ResearchUI.save();assert.equal(good.storage.get(key+'_conflict_1_1'),raw);const bad=harness(new Map([[key,raw]]));bad.entry.run.version=3;bad.ctx.localStorage.setItem=()=>{throw new Error('quota');};await bad.ctx.ResearchUI.bootstrap();assert.equal(await bad.ctx.ResearchUI.save(),true);assert.equal(bad.storage.get(key),raw);assert.equal(await bad.ctx.ResearchUI.save(),true);assert.equal(bad.storage.get(key),raw);bad.ctx.failSave=true;await assert.rejects(()=>bad.ctx.ResearchUI.flush(),/模拟失败/);assert.equal(bad.storage.get(key),raw);bad.storage.set(key,'changed-by-another-tab');bad.ctx.failSave=false;assert.equal(await bad.ctx.ResearchUI.save(),false);assert.equal(bad.storage.get(key),'changed-by-another-tab');});
test('研究列表委托统一项目入口，公开读取支持分页和明确失败',async()=>{const {ctx,sent}=harness();let opened=0;ctx.openProjectsPanel=()=>{opened++;};await ctx.ResearchUI.list();assert.equal(opened,1);ctx.fetch=async(url)=>{sent.push({url});return {json:async()=>({ok:true,items:[],nextOffset:50})};};const result=await ctx.ResearchUI.listRecords('abandoned',50);assert.equal(result.nextOffset,50);assert.match(sent.at(-1).url,/status=abandoned/);assert.match(sent.at(-1).url,/offset=50/);ctx.fetch=async()=>({json:async()=>({ok:false,error:'明确失败'})});await assert.rejects(()=>ctx.ResearchUI.listRecords(),/明确失败/);});
test('研究操作嵌入原AI行，新建和废止显眼可见且不重复重新开始；普通模式也有新建',()=>{const source=fs.readFileSync('research-ui.js','utf8').match(/ function toolbar\([\s\S]*?(?= function recoverConflict)/)[0];const names=[],children=[],anchor={append:x=>children.push(x)},sheet={};const ctx=vm.createContext({enabled:true,session:{identity:()=>({study:{title:'测试研究',status:'active',role:'manager'},run:{ordinal:1}})},editable:()=>true,lastError:'',create(){},save(){},rounds(){},materials(){},transition(){},button:(_p,text)=>names.push(text),document:{getElementById:id=>id==='airRestartBtn'?{parentElement:anchor}:id==='sheet'?sheet:null,createElement:()=>({append(){}})}});vm.runInContext(source,ctx);ctx.toolbar();assert.equal(children.length,1);assert.ok(names.includes('历史轮次'));assert.ok(names.includes('废止可研'));assert.equal(names.includes('重新开始'),false);assert.equal(names.includes('新增研究'),false);assert.ok(names.includes('新建可研'));ctx.enabled=false;ctx.toolbar();assert.equal(children.length,2);});
test('打开保存冲突核对不取消自动保存，也不让慢读取阻塞工具栏按钮',()=>{const source=fs.readFileSync('research-ui.js','utf8').match(/ function recoverConflict\(\)[\s\S]*?(?=\n function setLegacyRecord)/)[0];assert.doesNotMatch(source,/clearTimeout\(saveTimer\)/);assert.match(source,/Promise\.resolve\(ResearchRecovery\.open\(options\)\)\.catch\(failed\)/);assert.match(source,/原副本未删除/);});
test('保存冲突核对先显示可关闭窗口，慢速或失败读取不阻塞按钮',()=>{const source=fs.readFileSync('research-recovery.js','utf8');const shown=source.indexOf('d.showModal()'),background=source.indexOf('void (async()=>',shown),returned=source.indexOf('return d;',background);assert.ok(shown>=0&&background>shown&&returned>background);assert.match(source,/原副本未删除，可关闭窗口后继续使用当前页面/);});
test('统一项目入口保存研究失败时返回false，不进入旧项目保存链',async()=>{const source=fs.readFileSync('auth.js','utf8');const body=source.slice(source.indexOf('async function authPreserveCurrentDraft(){'),source.indexOf('async function newProject('));let oldCalls=0;const ctx=vm.createContext({window:{ResearchUI:{active:()=>true,flush:async()=>{throw new Error('offline');}}},projectCanEdit:()=>{oldCalls++;return true;}});vm.runInContext(body,ctx);assert.equal(await ctx.authPreserveCurrentDraft(),false);assert.equal(oldCalls,0);ctx.window.ResearchUI.flush=async()=>true;assert.equal(await ctx.authPreserveCurrentDraft(),true);});
test('列表管理另一份研究只导航到目标，不对当前研究发送废止请求',async()=>{const {ctx,sent}=harness();await ctx.ResearchUI.bootstrap();await ctx.ResearchUI.actionForRecord('research_other','abandon');const destination=new URL(sent.find(x=>x.navigate).navigate);assert.equal(destination.searchParams.get('research'),'research_other');assert.equal(destination.searchParams.get('researchAction'),'abandon');assert.equal(sent.some(x=>x.options?.body&&JSON.parse(x.options.body).action==='abandon'),false);await assert.rejects(()=>ctx.ResearchUI.actionForRecord('research_other','delete'),/不支持/);});
test('旧可研废止只限制AI编辑，不改变正式项目的原权限',()=>{const src=fs.readFileSync('auth.js','utf8').split(/\r?\n/).find(x=>x.startsWith('function projectCanEdit('));const ctx=vm.createContext({window:{ResearchUI:{active:()=>false,legacyAbandoned:()=>true}},appMode:'aireport',currentProjectRole:'OWNER'});vm.runInContext(src,ctx);assert.equal(ctx.projectCanEdit(),false);ctx.appMode='project';assert.equal(ctx.projectCanEdit(),true);assert.equal(ctx.currentProjectRole,'OWNER');ctx.currentProjectRole='VIEWER';assert.equal(ctx.projectCanEdit(),false);});
test('旧可研AI会话保存入队时捕获epoch，废止后不再写入',async()=>{const source=fs.readFileSync('aireport.js','utf8');let release,payload;const ctx=vm.createContext({window:{ResearchUI:{active:()=>false,legacyAbandoned:()=>false}},aiReportStateRevision:0,airSerializableState:()=>({chat:[]}),currentProjectId:'legacy_a',projectWorkflow:{management:{legacyResearchEpoch:2}},airSaveLocalState(){},aiReportStateSaveInFlight:new Promise(r=>release=r),authHeaders:()=>({}),fetch:async(_url,opts)=>{payload=JSON.parse(opts.body);return {ok:true};}});vm.runInContext(source.slice(source.indexOf('function airSaveState(){'),source.indexOf('function airRestoredConfirmation(')),ctx);const pending=ctx.airSaveState();ctx.projectWorkflow.management.legacyResearchEpoch=4;ctx.currentProjectId='legacy_b';release();assert.equal(await pending,true);assert.equal(payload.projectId,'legacy_a');assert.equal(payload.legacyResearchEpoch,2);ctx.window.ResearchUI.legacyAbandoned=()=>true;assert.equal(await ctx.airSaveState(),false);assert.equal(ctx.aiReportStateRevision,1);});
test('旧可研废止保存失败不发状态请求，恢复精确绑定目标且不自动输入密码',async()=>{const src=fs.readFileSync('research-ui.js','utf8').split(/\r?\n/).find(x=>x.startsWith(' async function legacyTransition('));let confirmAction,payload,reloaded=false;const fields=[];const ctx=vm.createContext({currentProjectId:'legacy_a',currentProjectUpdatedAt:7,legacyRecord:{id:'legacy_a'},modal:()=>({append(){}}),document:{createElement:()=>{const el={};fields.push(el);return el;}},button:(_d,_text,fn)=>confirmAction=fn,flush:async()=>true,airSaveState:async()=>false,authHeaders:()=>({}),AbortSignal,fetch:async(_url,opts)=>{payload=JSON.parse(opts.body);return {ok:true,json:async()=>({ok:true})};},location:{reload:()=>reloaded=true}});vm.runInContext(src,ctx);await ctx.legacyTransition('abandon');await assert.rejects(()=>confirmAction(),/保存失败/);assert.equal(payload,undefined);await ctx.legacyTransition('restore');const password=fields.at(-1);assert.equal(password.type,'password');assert.equal(password.value,undefined);password.value='test-only';await confirmAction();assert.equal(payload.id,'legacy_a');assert.equal(payload.abandoned,false);assert.equal(payload.expectedUpdatedAt,7);assert.equal(password.value,'');assert.equal(reloaded,true);await ctx.legacyTransition('restore');ctx.currentProjectId='legacy_b';await assert.rejects(()=>confirmAction(),/项目已切换/);});
