import {coordinate,toWgs84} from './core.mjs';
export const categories=['轨道交通','公交','教育','医疗','商业配套','产业园区'];
const R=6371008.8,rad=Math.PI/180;
export function distance(a,b){const p=coordinate(a),q=coordinate(b);if(!p||!q)throw Error('坐标无效');const h=Math.sin((q[1]-p[1])*rad/2)**2+Math.cos(p[1]*rad)*Math.cos(q[1]*rad)*Math.sin((q[0]-p[0])*rad/2)**2;return 2*R*Math.asin(Math.sqrt(Math.min(1,h)));}
export function circle(center,radius){if(!coordinate(center)||![500,1000,2000,3000].includes(radius))throw Error('范围无效');const [lon,lat]=center.map(v=>v*rad),d=radius/R;const ring=Array.from({length:96},(_,i)=>{const t=i*2*Math.PI/96,y=Math.asin(Math.sin(lat)*Math.cos(d)+Math.cos(lat)*Math.sin(d)*Math.cos(t)),x=lon+Math.atan2(Math.sin(t)*Math.sin(d)*Math.cos(lat),Math.cos(d)-Math.sin(lat)*Math.sin(y));return [x/rad,y/rad];});return [...ring,ring[0]];}
function cross(a,b,c){return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);}
function intersects(a,b,c,d){return Math.max(Math.min(a[0],b[0]),Math.min(c[0],d[0]))<=Math.min(Math.max(a[0],b[0]),Math.max(c[0],d[0]))&&Math.max(Math.min(a[1],b[1]),Math.min(c[1],d[1]))<=Math.min(Math.max(a[1],b[1]),Math.max(c[1],d[1]))&&cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0;}
export function polygon(points){if(!Array.isArray(points))throw Error('红线必须是坐标数组');let p=points.map(coordinate);if(p.some(x=>!x)||p.length>2000)throw Error('红线坐标无效或超过2000点');if(p.length>1&&distance(p[0],p.at(-1))<.01)p.pop();if(p.length<3)throw Error('红线至少三个点');for(let i=0;i<p.length;i++){if(distance(p[i],p[(i+1)%p.length])<.05)throw Error('红线有重复顶点');for(let j=i+2;j<p.length;j++){if(i===0&&j===p.length-1)continue;const a=p[i],b=p[(i+1)%p.length],c=p[j],d=p[(j+1)%p.length];if(intersects(a,b,c,d))throw Error('红线自相交或重复，请重新绘制');}}if(p.every(q=>Math.abs(cross(p[0],p[1],q))<1e-14))throw Error('红线顶点共线');const ring=[...p,p[0]];if(area(ring)<1)throw Error('红线面积过小或共线');return ring;}
export function area(ring){let sum=0;for(let i=0;i<ring.length-1;i++)sum+=(ring[i+1][0]-ring[i][0])*rad*(2+Math.sin(ring[i][1]*rad)+Math.sin(ring[i+1][1]*rad));return Math.abs(sum*R*R/2);}
export function length(points){return points.slice(1).reduce((sum,p,i)=>sum+distance(points[i],p),0);}
export function parseCSV(text){const rows=[];let row=[],field='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){field+='"';i++;}else quote=!quote;}else if(!quote&&(c===','||c==='\n')){row.push(field.replace(/\r$/,''));field='';if(c==='\n'){rows.push(row);row=[];}}else field+=c;}if(quote)throw Error('CSV引号未闭合');row.push(field.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);const heads=rows.shift()?.map(s=>s.replace(/^\uFEFF/,'').trim())||[];return rows.filter(r=>r.some(Boolean)).map((r,i)=>{if(r.length!==heads.length)throw Error('CSV第'+(i+2)+'行列数不一致');return Object.fromEntries(heads.map((h,j)=>[h,r[j]]));});}
export function safeURL(value){try{const u=new URL(String(value));return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:'';}catch{return '';}}
const str=(v,n=200)=>String(v??'').trim().slice(0,n);
export function normalizeProject(raw,index=0){const name=str(raw.name||raw['项目名称']);if(!name)throw Error('第'+(index+1)+'条缺少项目名称');const crs=raw.crs||raw['坐标系']||'WGS84';const lon=raw.lon??raw['经度'],lat=raw.lat??raw['纬度'];const input=raw.point||((String(lon??'').trim()||String(lat??'').trim())?[lon,lat]:null);const point=input?toWgs84(input,crs):null;if(input&&!point)throw Error(name+'坐标无效（支持WGS84/GCJ02）');return {id:str(raw.id||crypto.randomUUID(),80),name,address:str(raw.address||raw['地址']),district:str(raw.district||raw['行政区'],40),type:str(raw.type||raw['类型'],40),stage:str(raw.stage||raw['阶段'],40),metrics:str(raw.metrics||raw['关键指标'],2000),source:str(raw.source||raw['来源']),point,confirmed:false,photo:safeURL(raw.photo||raw['照片链接']),document:safeURL(raw.document||raw['资料链接']),redline:raw.redline?polygon(raw.redline):null};}
export function mergeProjects(existing,incoming){const added=[],duplicates=[];for(const p of incoming){const same=[...existing,...added].find(x=>x.id===p.id||(!(x.source==='正式项目库（只读）'&&p.source===x.source)&&x.name===p.name&&((!!x.address&&x.address===p.address)||(x.point&&p.point&&distance(x.point,p.point)<10))));(same?duplicates:added).push(p);}return {added,duplicates};}
export function filterProjects(items,filters){return items.filter(p=>(!filters.query||(p.name+' '+p.address).toLowerCase().includes(filters.query.toLowerCase()))&&['district','type','stage'].every(k=>!filters[k]||p[k]===filters[k]));}
export function decodeBundle(text){
 if(text.length>5*1024*1024)throw Error('研判包不能超过5MiB');
 const b=JSON.parse(text);if(b.version!==1||!Array.isArray(b.projects)||b.projects.length>2000||!Array.isArray(b.records)||b.records.length>500)throw Error('不是支持的研判包或条目超限');
 const projects=b.projects.map(normalizeProject);if(new Set(projects.map(p=>p.id)).size!==projects.length)throw Error('研判包存在重复ID');
 const records=b.records.map(r=>{
  if(!r.id||!Number.isFinite(Date.parse(r.date))||!r.project?.name||!coordinate(r.project.point)||![500,1000,2000,3000].includes(r.radius)||!Array.isArray(r.facilities)||r.facilities.length>200)throw Error('研判记录格式无效');
  const project=normalizeProject(r.project),outcomes={};
  for(const c of categories){const o=r.outcomes?.[c];if(o){if(!['ready','failed','loading'].includes(o.state))throw Error('配套状态无效');outcomes[c]={state:o.state==='loading'?'failed':o.state,source:str(o.source),queriedAt:str(o.queriedAt),truncated:!!o.truncated,total:Math.max(0,Number(o.total)||0),error:o.state==='loading'?'上次查询未完成，请重试':str(o.error)};}}
  const facilities=r.facilities.map(f=>{const point=coordinate(f.point);if(!point||!categories.includes(f.category)||!f.name||distance(project.point,point)>r.radius+2)throw Error('配套记录坐标、类别或范围无效');return {name:str(f.name),address:str(f.address),category:f.category,point,distance:distance(project.point,point)};});
  return {id:str(r.id,80),date:new Date(r.date).toISOString(),project:{...project,confirmed:true},radius:r.radius,facilities,outcomes,note:str(r.note,8000)};
 });
 if(new Set(records.map(r=>r.id)).size!==records.length)throw Error('研判记录存在重复ID');
 return {version:1,projects:projects.map((p,i)=>({...p,confirmed:!!b.projects[i].confirmed&&!!p.point})),records};
}
