CREATE TABLE IF NOT EXISTS web_search_runs (id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,project_id TEXT DEFAULT '',section_key TEXT DEFAULT '',plan_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'running',provider TEXT DEFAULT '',query_count INTEGER NOT NULL DEFAULT 0,result_count INTEGER NOT NULL DEFAULT 0,error_text TEXT DEFAULT '',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_web_runs_user_project ON web_search_runs(user_id,project_id,updated_at);
CREATE TABLE IF NOT EXISTS web_evidence (id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,project_id TEXT DEFAULT '',logic_id TEXT DEFAULT '',chapter TEXT DEFAULT '',section TEXT DEFAULT '',query_text TEXT DEFAULT '',title TEXT NOT NULL,url TEXT NOT NULL,canonical_url TEXT NOT NULL,publisher TEXT DEFAULT '',published_at TEXT DEFAULT '',fetched_at TEXT DEFAULT '',source_type TEXT DEFAULT 'web',authority_level TEXT DEFAULT 'D',authority_score INTEGER NOT NULL DEFAULT 0,excerpt TEXT DEFAULT '',content_text TEXT DEFAULT '',content_hash TEXT DEFAULT '',data_period TEXT DEFAULT '',provider TEXT DEFAULT '',confidence INTEGER NOT NULL DEFAULT 0,verification_status TEXT DEFAULT 'single',status TEXT NOT NULL DEFAULT 'candidate',metadata_json TEXT NOT NULL DEFAULT '{}',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_web_evidence_project ON web_evidence(user_id,project_id,status,updated_at);
CREATE INDEX IF NOT EXISTS idx_web_evidence_section ON web_evidence(user_id,project_id,chapter,section);
CREATE TABLE IF NOT EXISTS web_evidence_bindings (id TEXT PRIMARY KEY,evidence_id TEXT NOT NULL,user_id INTEGER NOT NULL,project_id TEXT DEFAULT '',logic_id TEXT NOT NULL,chapter TEXT DEFAULT '',section TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'approved',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,UNIQUE(evidence_id,logic_id));
CREATE INDEX IF NOT EXISTS idx_web_evidence_bindings_project ON web_evidence_bindings(user_id,project_id,logic_id,status);
CREATE TABLE IF NOT EXISTS web_provider_health (provider TEXT PRIMARY KEY,status TEXT NOT NULL DEFAULT 'unknown',latency_ms INTEGER NOT NULL DEFAULT 0,last_error TEXT DEFAULT '',success_count INTEGER NOT NULL DEFAULT 0,failure_count INTEGER NOT NULL DEFAULT 0,last_checked_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS web_search_lenses (id TEXT PRIMARY KEY,name TEXT NOT NULL,dimension TEXT DEFAULT '',domains_json TEXT NOT NULL DEFAULT '[]',housing_types_json TEXT NOT NULL DEFAULT '[]',query_suffix TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'active',version INTEGER NOT NULL DEFAULT 1,updated_by TEXT DEFAULT '',updated_at BIGINT NOT NULL);
