-- Investment OS阶段4—6：会议、任务风险、情景、决策包、评测与优化台账。
CREATE TABLE IF NOT EXISTS project_meetings (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,content TEXT NOT NULL,extraction_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'candidate',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_meetings_lookup ON project_meetings(project_id,user_id,updated_at);
CREATE TABLE IF NOT EXISTS project_tasks (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,owner TEXT DEFAULT '',due_date TEXT DEFAULT '',source_ref TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'candidate',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_tasks_lookup ON project_tasks(project_id,user_id,status,updated_at);
CREATE TABLE IF NOT EXISTS project_risks (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,risk_level TEXT DEFAULT 'normal',owner TEXT DEFAULT '',source_ref TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'candidate',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_risks_lookup ON project_risks(project_id,user_id,status,updated_at);
CREATE TABLE IF NOT EXISTS project_scenarios (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,calc_type TEXT DEFAULT '',calc_snapshot_id TEXT NOT NULL,engine TEXT NOT NULL DEFAULT 'whitebox',params_json TEXT NOT NULL DEFAULT '{}',metrics_json TEXT NOT NULL DEFAULT '{}',risks_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'draft',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_scenarios_lookup ON project_scenarios(project_id,user_id,status,updated_at);
CREATE TABLE IF NOT EXISTS project_decision_packages (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,scenario_id TEXT NOT NULL,decision_id TEXT DEFAULT '',package_json TEXT NOT NULL DEFAULT '{}',audit_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'blocked',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_packages_lookup ON project_decision_packages(project_id,user_id,status,updated_at);
CREATE TABLE IF NOT EXISTS project_evaluations (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,evaluation_type TEXT NOT NULL,result_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'draft',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_evaluations_lookup ON project_evaluations(project_id,user_id,updated_at);
CREATE TABLE IF NOT EXISTS optimization_ledger (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,evidence TEXT DEFAULT '',before_value TEXT DEFAULT '',after_value TEXT DEFAULT '',actual_benefit TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'candidate',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_optimization_ledger_lookup ON optimization_ledger(project_id,user_id,updated_at);
