-- Investment OS Phase 2.5 Sprint A：项目边界、成员、阶段门、里程碑和阶段成果。
CREATE TABLE IF NOT EXISTS project_profiles (project_id TEXT PRIMARY KEY,owner_user_id INTEGER NOT NULL,organization_id TEXT DEFAULT '',department_id TEXT DEFAULT '',visibility TEXT NOT NULL DEFAULT 'private',confidentiality_level TEXT NOT NULL DEFAULT 'internal',lifecycle_stage TEXT NOT NULL DEFAULT 'discovery',current_gate_id TEXT DEFAULT '',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS project_memberships (project_id TEXT NOT NULL,user_id INTEGER NOT NULL,role TEXT NOT NULL DEFAULT 'VIEWER',status TEXT NOT NULL DEFAULT 'active',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,PRIMARY KEY(project_id,user_id));
CREATE INDEX IF NOT EXISTS idx_project_memberships_user ON project_memberships(user_id,status,updated_at);
CREATE TABLE IF NOT EXISTS project_gates (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,name TEXT NOT NULL,stage_key TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'not_started',planned_date TEXT DEFAULT '',actual_date TEXT DEFAULT '',owner TEXT DEFAULT '',criteria_json TEXT NOT NULL DEFAULT '[]',block_reason TEXT DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_gates_project ON project_gates(project_id,sort_order,updated_at);
CREATE TABLE IF NOT EXISTS project_milestones (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,name TEXT NOT NULL,stage_key TEXT DEFAULT '',gate_id TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'not_started',planned_date TEXT DEFAULT '',forecast_date TEXT DEFAULT '',actual_date TEXT DEFAULT '',owner TEXT DEFAULT '',progress REAL NOT NULL DEFAULT 0,weight REAL NOT NULL DEFAULT 1,risk_level TEXT DEFAULT 'normal',sort_order INTEGER NOT NULL DEFAULT 0,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_milestones_project ON project_milestones(project_id,sort_order,updated_at);
CREATE TABLE IF NOT EXISTS project_deliverables (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,name TEXT NOT NULL,stage_key TEXT DEFAULT '',gate_id TEXT DEFAULT '',milestone_id TEXT DEFAULT '',artifact_id TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'not_started',required INTEGER NOT NULL DEFAULT 1,owner TEXT DEFAULT '',due_date TEXT DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_deliverables_project ON project_deliverables(project_id,sort_order,updated_at);
