// /api/investmentops —— Investment OS阶段4—6的会议行动化、情景决策包与生产验收台账。
import "../../investment-ops.js";
import { verifyAuth, json } from "./_auth.js";
import { adaptEnv } from "./_adapters.js";

const Ops=globalThis.InvestmentOps;
const clean=(v,n=500)=>String(v==null?"":v).trim().slice(0,n);
const parse=(v,f={})=>{try{return typeof v==="string"?JSON.parse(v):v==null?f:v;}catch(_){return f;}};
const uid=p=>p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,9);
const TABLES=[
  "CREATE TABLE IF NOT EXISTS project_meetings (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,content TEXT NOT NULL,extraction_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'candidate',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_project_meetings_lookup ON project_meetings(project_id,user_id,updated_at)",
  "CREATE TABLE IF NOT EXISTS project_tasks (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,owner TEXT DEFAULT '',due_date TEXT DEFAULT '',source_ref TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'candidate',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_project_tasks_lookup ON project_tasks(project_id,user_id,status,updated_at)",
  "CREATE TABLE IF NOT EXISTS project_risks (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,risk_level TEXT DEFAULT 'normal',owner TEXT DEFAULT '',source_ref TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'candidate',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_project_risks_lookup ON project_risks(project_id,user_id,status,updated_at)",
  "CREATE TABLE IF NOT EXISTS project_scenarios (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,calc_type TEXT DEFAULT '',calc_snapshot_id TEXT NOT NULL,engine TEXT NOT NULL DEFAULT 'whitebox',params_json TEXT NOT NULL DEFAULT '{}',metrics_json TEXT NOT NULL DEFAULT '{}',risks_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'draft',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_project_scenarios_lookup ON project_scenarios(project_id,user_id,status,updated_at)",
  "CREATE TABLE IF NOT EXISTS project_decision_packages (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,scenario_id TEXT NOT NULL,decision_id TEXT DEFAULT '',package_json TEXT NOT NULL DEFAULT '{}',audit_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'blocked',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_project_packages_lookup ON project_decision_packages(project_id,user_id,status,updated_at)",
  "CREATE TABLE IF NOT EXISTS project_evaluations (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,evaluation_type TEXT NOT NULL,result_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'draft',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_project_evaluations_lookup ON project_evaluations(project_id,user_id,updated_at)",
  "CREATE TABLE IF NOT EXISTS optimization_ledger (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,title TEXT NOT NULL,evidence TEXT DEFAULT '',before_value TEXT DEFAULT '',after_value TEXT DEFAULT '',actual_benefit TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'candidate',created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_optimization_ledger_lookup ON optimization_ledger(project_id,user_id,updated_at)"
];
async function ensure(env){for(const sql of TABLES)await env.DB.prepare(sql).run();}
async function owned(env,user,id){return env.DB.prepare("SELECT id,name,data FROM projects WHERE id=? AND user_id=?").bind(id,user.userId).first();}
function pid(v){const x=clean(v,100);return /^[A-Za-z0-9_-]{8,100}$/.test(x)?x:"";}
async function list(env,user,projectId){
  const q=async(sql)=>(await env.DB.prepare(sql).bind(projectId,user.userId).all()).results||[];
  const [meetings,tasks,risks,scenarios,packages,evaluations,optimizations]=await Promise.all([
    q("SELECT * FROM project_meetings WHERE project_id=? AND user_id=? ORDER BY updated_at DESC LIMIT 40"),q("SELECT * FROM project_tasks WHERE project_id=? AND user_id=? ORDER BY updated_at DESC LIMIT 100"),q("SELECT * FROM project_risks WHERE project_id=? AND user_id=? ORDER BY updated_at DESC LIMIT 100"),q("SELECT * FROM project_scenarios WHERE project_id=? AND user_id=? ORDER BY updated_at DESC LIMIT 40"),q("SELECT * FROM project_decision_packages WHERE project_id=? AND user_id=? ORDER BY updated_at DESC LIMIT 30"),q("SELECT * FROM project_evaluations WHERE project_id=? AND user_id=? ORDER BY updated_at DESC LIMIT 30"),q("SELECT * FROM optimization_ledger WHERE project_id=? AND user_id=? ORDER BY updated_at DESC LIMIT 60")
  ]);
  const allEval=(await env.DB.prepare("SELECT project_id,evaluation_type,result_json,status,updated_at FROM project_evaluations WHERE user_id=? ORDER BY updated_at DESC LIMIT 200").bind(user.userId).all()).results||[],seen=new Set(),golden=[];let slo=null;
  allEval.forEach(x=>{const result=parse(x.result_json,{});if(x.evaluation_type==="golden_project"&&!seen.has(x.project_id)){seen.add(x.project_id);golden.push({id:x.project_id,type:result.projectType,numericErrors:result.numericErrors});}if(!slo&&x.evaluation_type==="slo_load")slo={passed:x.status==="passed",result};});
  const production=Ops.productionGate({goldenProjects:golden,slo:slo||{passed:false}});
  return {meetings:meetings.map(x=>({id:x.id,title:x.title,content:x.content,extraction:parse(x.extraction_json,{}),status:x.status,updatedAt:Number(x.updated_at)})),tasks:tasks.map(x=>({id:x.id,title:x.title,owner:x.owner,dueDate:x.due_date,sourceRef:x.source_ref,status:x.status})),risks:risks.map(x=>({id:x.id,title:x.title,level:x.risk_level,owner:x.owner,sourceRef:x.source_ref,status:x.status})),scenarios:scenarios.map(x=>({id:x.id,name:x.name,kind:x.kind,calcType:x.calc_type,calcSnapshotId:x.calc_snapshot_id,engine:x.engine,params:parse(x.params_json,{}),metrics:parse(x.metrics_json,{}),risks:parse(x.risks_json,[]),status:x.status,updatedAt:Number(x.updated_at)})),packages:packages.map(x=>({id:x.id,title:x.title,scenarioId:x.scenario_id,decisionId:x.decision_id,package:parse(x.package_json,{}),audit:parse(x.audit_json,{}),status:x.status,updatedAt:Number(x.updated_at)})),evaluations:evaluations.map(x=>({id:x.id,type:x.evaluation_type,result:parse(x.result_json,{}),status:x.status,updatedAt:Number(x.updated_at)})),optimizations:optimizations.map(x=>({id:x.id,title:x.title,evidence:x.evidence,before:x.before_value,after:x.after_value,actualBenefit:x.actual_benefit,status:x.status,updatedAt:Number(x.updated_at)})),production};
}
async function event(env,user,projectId,type,payload){await env.DB.prepare("INSERT INTO project_events(id,project_id,user_id,event_type,actor,payload_json,created_at) VALUES(?,?,?,?,?,?,?)").bind(uid("event"),projectId,user.userId,type,clean(user.username||user.userId,80),JSON.stringify(payload||{}),Date.now()).run();}

export async function onRequestGet(c){const env=adaptEnv(c.env),user=await verifyAuth(c.request,env);if(!user)return json({ok:false,error:"未登录或登录已过期"},401);await ensure(env);const projectId=pid(new URL(c.request.url).searchParams.get("projectId"));if(!projectId)return json({ok:false,error:"项目ID不合法"},400);if(!await owned(env,user,projectId))return json({ok:false,error:"项目不存在或无权访问"},404);return json({ok:true,ops:await list(env,user,projectId)});}

export async function onRequestPost(c){
  const env=adaptEnv(c.env),user=await verifyAuth(c.request,env);if(!user)return json({ok:false,error:"未登录或登录已过期"},401);await ensure(env);let b={};try{b=await c.request.json();}catch(_){return json({ok:false,error:"请求格式有误"},400);}const projectId=pid(b.projectId),action=clean(b.action,50),row=projectId&&await owned(env,user,projectId);if(!row)return json({ok:false,error:"项目不存在或无权访问"},404);const now=Date.now();
  if(action==="extractMeeting"){
    const content=clean(b.content,20000);if(!content)return json({ok:false,error:"请粘贴会议纪要内容"},400);const extraction=Ops.parseMeeting(content),id=uid("meeting");await env.DB.prepare("INSERT INTO project_meetings(id,project_id,user_id,title,content,extraction_json,status,created_at,updated_at) VALUES(?,?,?,?,? ,?,'candidate',?,?)").bind(id,projectId,user.userId,clean(b.title,200)||"项目会议纪要",content,JSON.stringify(extraction),now,now).run();await event(env,user,projectId,"meeting.extracted",{meetingId:id,summary:extraction.summary});return json({ok:true,id,extraction});
  }
  if(action==="confirmMeeting"){
    const meetingId=clean(b.meetingId,100),m=await env.DB.prepare("SELECT * FROM project_meetings WHERE id=? AND project_id=? AND user_id=?").bind(meetingId,projectId,user.userId).first();if(!m)return json({ok:false,error:"会议候选不存在"},404);const x=parse(m.extraction_json,{}),picked=new Set(Array.isArray(b.selectedIds)?b.selectedIds:[]);let taskCount=0,riskCount=0,decisionCount=0;
    for(const t of (x.tasks||[])){if(picked.size&&!picked.has(t.id))continue;await env.DB.prepare("INSERT INTO project_tasks(id,project_id,user_id,title,owner,due_date,source_ref,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'open',?,?)").bind(uid("task"),projectId,user.userId,clean(t.text,500),clean(t.owner,100),clean(t.due,40),"meeting:"+meetingId+":line:"+t.sourceLine,now,now).run();taskCount++;}
    for(const r of (x.risks||[])){if(picked.size&&!picked.has(r.id))continue;await env.DB.prepare("INSERT INTO project_risks(id,project_id,user_id,title,risk_level,owner,source_ref,status,created_at,updated_at) VALUES(?,?,?,?,?, '',?,'open',?,?)").bind(uid("risk"),projectId,user.userId,clean(r.text,500),clean(r.level,20),"meeting:"+meetingId+":line:"+r.sourceLine,now,now).run();riskCount++;}
    for(const d of (x.decisions||[])){if(picked.size&&!picked.has(d.id))continue;await env.DB.prepare("INSERT INTO project_decisions(id,project_id,user_id,stage_key,topic,options_json,decision_text,evidence_ids_json,scenario_ids_json,owner,status,created_by,created_at,updated_at) VALUES(?,?,?,'decision',?,'[]','','[]','[]','','candidate',?,?,?)").bind(uid("decision"),projectId,user.userId,clean(d.text,240),clean(user.username||user.userId,80),now,now).run();decisionCount++;}
    await env.DB.prepare("UPDATE project_meetings SET status='confirmed',updated_at=? WHERE id=? AND project_id=? AND user_id=?").bind(now,meetingId,projectId,user.userId).run();await event(env,user,projectId,"meeting.confirmed",{meetingId,taskCount,riskCount,decisionCount});return json({ok:true,taskCount,riskCount,decisionCount});
  }
  if(action==="saveScenario"){
    const data=parse(row.data,{}),snapshots=(data.workflow&&data.workflow.calcSnapshots)||[],snapshot=snapshots.slice(-1)[0]||{},calcSnapshotId=clean(b.calcSnapshotId||snapshot.id||snapshot.snapshotId||(snapshot.version?"calc-v"+snapshot.version:""),120);if(!calcSnapshotId)return json({ok:false,error:"请先完成一次财务测算并形成快照，情景不能脱离白箱引擎保存"},409);
    const scenario=Ops.normalizeScenario({...b.scenario,calcSnapshotId,calcType:b.scenario&&b.scenario.calcType||snapshot.calcType||data.project&&data.project.type,engine:"whitebox",params:b.scenario&&b.scenario.params||snapshot.params||data.calcParams||{},metrics:b.scenario&&b.scenario.metrics||snapshot.summary||data.calcSummary||{}}),id=uid("scenario");await env.DB.prepare("INSERT INTO project_scenarios(id,project_id,user_id,name,kind,calc_type,calc_snapshot_id,engine,params_json,metrics_json,risks_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,projectId,user.userId,scenario.name,scenario.kind,scenario.calcType,scenario.calcSnapshotId,"whitebox",JSON.stringify(scenario.params),JSON.stringify(scenario.metrics),JSON.stringify(scenario.risks),scenario.status,now,now).run();await event(env,user,projectId,"scenario.saved",{scenarioId:id,kind:scenario.kind,calcSnapshotId});return json({ok:true,id,scenario:{...scenario,id}});
  }
  if(action==="createDecisionPackage"){
    const scenarioId=clean(b.scenarioId,100),s=await env.DB.prepare("SELECT * FROM project_scenarios WHERE id=? AND project_id=? AND user_id=?").bind(scenarioId,projectId,user.userId).first();if(!s)return json({ok:false,error:"请选择一个已保存的白箱情景"},404);const data=await list(env,user,projectId),scenario={id:s.id,name:s.name,kind:s.kind,calcType:s.calc_type,calcSnapshotId:s.calc_snapshot_id,engine:s.engine,params:parse(s.params_json,{}),metrics:parse(s.metrics_json,{}),risks:parse(s.risks_json,[])},artifactRows=(await env.DB.prepare("SELECT artifact_type,id FROM project_artifacts WHERE project_id=? AND user_id=?").bind(projectId,user.userId).all()).results||[],artifacts=artifactRows.map(x=>({id:x.id,artifactType:x.artifact_type||x.artifactType||x.artifacttype})),evidenceIds=Array.isArray(b.evidenceIds)?b.evidenceIds:[],pack=Ops.buildDecisionPackage({projectId,title:b.title,scenario,scenarios:data.scenarios,decisionId:b.decisionId,evidenceIds,artifactIds:artifacts.map(x=>x.id),context:{artifacts},consistencyIssues:b.consistencyIssues||[]}),id=uid("package");await env.DB.prepare("INSERT INTO project_decision_packages(id,project_id,user_id,title,scenario_id,decision_id,package_json,audit_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(id,projectId,user.userId,pack.title,scenarioId,clean(b.decisionId,100),JSON.stringify({...pack,id}),JSON.stringify(pack.audit),pack.status,now,now).run();await event(env,user,projectId,"decision.package.created",{packageId:id,status:pack.status,blockers:pack.audit.blockers.length});return json({ok:true,id,package:{...pack,id}});
  }
  if(action==="saveEvaluation"){
    const type=["golden_project","slo_load","workflow_recovery","business_acceptance"].includes(b.type)?b.type:"business_acceptance",projectData=parse(row.data,{}),result={...(b.result||{}),projectType:clean((b.result||{}).projectType||projectData.project&&projectData.project.type,30)},status=clean(b.status||"recorded",30),id=uid("evaluation");await env.DB.prepare("INSERT INTO project_evaluations(id,project_id,user_id,evaluation_type,result_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").bind(id,projectId,user.userId,type,JSON.stringify(result),status,now,now).run();await event(env,user,projectId,"evaluation.saved",{evaluationId:id,type,status});return json({ok:true,id});
  }
  if(action==="saveOptimization"){
    const title=clean(b.title,240);if(!title)return json({ok:false,error:"优化事项不能为空"},400);const id=uid("optimization");await env.DB.prepare("INSERT INTO optimization_ledger(id,project_id,user_id,title,evidence,before_value,after_value,actual_benefit,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(id,projectId,user.userId,title,clean(b.evidence,2000),clean(b.before,300),clean(b.after,300),clean(b.actualBenefit,500),clean(b.status||"candidate",30),now,now).run();await event(env,user,projectId,"optimization.saved",{optimizationId:id,title});return json({ok:true,id});
  }
  if(action==="updateItem"){
    const type=clean(b.type,20),id=clean(b.id,100),status=clean(b.status,30),allowed={task:["project_tasks","open","done","cancelled"],risk:["project_risks","open","mitigated","closed"]}[type];if(!allowed||!allowed.slice(1).includes(status))return json({ok:false,error:"事项类型或状态无效"},400);await env.DB.prepare(`UPDATE ${allowed[0]} SET status=?,updated_at=? WHERE id=? AND project_id=? AND user_id=?`).bind(status,now,id,projectId,user.userId).run();await event(env,user,projectId,type+".status",{id,status});return json({ok:true,id,status});
  }
  return json({ok:false,error:"不支持的Investment OS操作"},400);
}
