// /api/personalnotes — 个人知识库。所有读写均按登录用户隔离，不进入部门 RAG。
import { verifyAuth, json } from "./_auth.js";
import { adaptEnv } from "./_adapters.js";

let schemaReady=false, schemaPromise=null;
function clean(v,n=200000){return String(v==null?"":v).trim().slice(0,n);}
function makeId(prefix){const a=new Uint32Array(1);crypto.getRandomValues(a);return prefix+Date.now().toString(36)+a[0].toString(36).slice(0,7);}
function parseJson(v,fallback=[]){try{const x=JSON.parse(v||"");return x==null?fallback:x;}catch(e){return fallback;}}
function tagsOf(v){const a=Array.isArray(v)?v:String(v||"").split(/[,，;；\n]/);return [...new Set(a.map(x=>clean(x,30)).filter(Boolean))].slice(0,20);}
function output(row){return row?{id:row.id,parentId:row.parent_id||"",kind:row.kind,title:row.title,content:row.content||"",tags:parseJson(row.tags,[]),favorite:!!row.favorite,status:row.status,sourceName:row.source_name||"",sourceType:row.source_type||"",revision:Number(row.revision||1),sortOrder:Number(row.sort_order||0),createdAt:Number(row.created_at||0),updatedAt:Number(row.updated_at||0),deletedAt:Number(row.deleted_at||0)}:null;}

async function ensureSchema(env){
  if(schemaReady)return;if(schemaPromise)return schemaPromise;
  schemaPromise=(async()=>{const ts=env.DEPLOY_MODE==="local"?"BIGINT":"INTEGER";const sql=[
    "CREATE TABLE IF NOT EXISTS personal_notes (id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,parent_id TEXT NOT NULL DEFAULT '',kind TEXT NOT NULL DEFAULT 'note',title TEXT NOT NULL,content TEXT NOT NULL DEFAULT '',tags TEXT NOT NULL DEFAULT '[]',favorite INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',source_name TEXT DEFAULT '',source_type TEXT DEFAULT '',revision INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at "+ts+" NOT NULL,updated_at "+ts+" NOT NULL,deleted_at "+ts+" DEFAULT 0)",
    "CREATE INDEX IF NOT EXISTS idx_personal_notes_user_status ON personal_notes(user_id,status,updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_personal_notes_parent ON personal_notes(user_id,parent_id,status,sort_order,title)",
    "CREATE TABLE IF NOT EXISTS personal_note_versions (id TEXT PRIMARY KEY,note_id TEXT NOT NULL,user_id INTEGER NOT NULL,revision INTEGER NOT NULL,title TEXT NOT NULL,content TEXT NOT NULL DEFAULT '',tags TEXT NOT NULL DEFAULT '[]',created_at "+ts+" NOT NULL)",
    "CREATE INDEX IF NOT EXISTS idx_personal_versions_note ON personal_note_versions(user_id,note_id,created_at DESC)",
    "CREATE TABLE IF NOT EXISTS personal_note_links (id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,from_note_id TEXT NOT NULL,to_note_id TEXT DEFAULT '',target_title TEXT NOT NULL,link_text TEXT DEFAULT '',created_at "+ts+" NOT NULL)",
    "CREATE INDEX IF NOT EXISTS idx_personal_links_from ON personal_note_links(user_id,from_note_id)",
    "CREATE INDEX IF NOT EXISTS idx_personal_links_to ON personal_note_links(user_id,to_note_id,target_title)"
  ];for(const s of sql)await env.DB.prepare(s).run();schemaReady=true;})().catch(e=>{schemaPromise=null;throw e;});return schemaPromise;
}
async function owned(env,user,id,includeTrash=true){return env.DB.prepare("SELECT * FROM personal_notes WHERE id=? AND user_id=?"+(includeTrash?"":" AND status='active'")).bind(id,user.userId).first();}
async function descendantIds(env,user,rootId){const ids=[rootId],seen=new Set(ids);for(let cursor=0;cursor<ids.length&&ids.length<2000;cursor++){const rows=await env.DB.prepare("SELECT id FROM personal_notes WHERE parent_id=? AND user_id=?").bind(ids[cursor],user.userId).all();for(const x of (rows.results||[]))if(!seen.has(x.id)){seen.add(x.id);ids.push(x.id);}}return ids;}
async function snapshot(env,user,row,force=false){
  if(!row||row.kind!=="note")return;const last=await env.DB.prepare("SELECT created_at FROM personal_note_versions WHERE note_id=? AND user_id=? ORDER BY created_at DESC LIMIT 1").bind(row.id,user.userId).first();
  if(!force&&last&&Date.now()-Number(last.created_at||0)<5*60*1000)return;
  await env.DB.prepare("INSERT INTO personal_note_versions(id,note_id,user_id,revision,title,content,tags,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(makeId("pnv_"),row.id,user.userId,Number(row.revision||1),row.title,row.content||"",row.tags||"[]",Date.now()).run();
  const all=await env.DB.prepare("SELECT id FROM personal_note_versions WHERE note_id=? AND user_id=? ORDER BY created_at DESC").bind(row.id,user.userId).all();for(const old of (all.results||[]).slice(30))await env.DB.prepare("DELETE FROM personal_note_versions WHERE id=? AND user_id=?").bind(old.id,user.userId).run();
}
function linksIn(text){const out=[],re=/\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|([^\]]+))?\]\]/g;let m;while((m=re.exec(String(text||"")))&&out.length<200){const title=clean(m[1],120),label=clean(m[2]||m[1],120);if(title)out.push({title,label});}return out;}
async function refreshLinks(env,user,row){await env.DB.prepare("DELETE FROM personal_note_links WHERE from_note_id=? AND user_id=?").bind(row.id,user.userId).run();for(const link of linksIn(row.content)){const target=await env.DB.prepare("SELECT id FROM personal_notes WHERE user_id=? AND status='active' AND kind='note' AND LOWER(title)=LOWER(?) ORDER BY updated_at DESC LIMIT 1").bind(user.userId,link.title).first();await env.DB.prepare("INSERT INTO personal_note_links(id,user_id,from_note_id,to_note_id,target_title,link_text,created_at) VALUES(?,?,?,?,?,?,?)").bind(makeId("pnl_"),user.userId,row.id,target&&target.id||"",link.title,link.label,Date.now()).run();}}
function tokens(q){return [...new Set(clean(q,1000).toLowerCase().split(/[\s,，。；;：:、!?！？()（）【】\[\]]+/).map(x=>x.trim()).filter(x=>x.length>1))].slice(0,30);}
function score(row,words){const title=String(row.title||"").toLowerCase(),body=String(row.content||"").toLowerCase(),tag=String(row.tags||"").toLowerCase();let n=0;for(const w of words)n+=(title.includes(w)?8:0)+(tag.includes(w)?5:0)+(body.includes(w)?1:0);return n;}

export async function onRequestPost(context){
  const {request}=context,env=adaptEnv(context.env),user=await verifyAuth(request,adaptEnv(context.env));if(!user)return json({ok:false,error:"未登录"},401);
  try{await ensureSchema(env);}catch(e){return json({ok:false,error:"个人知识库初始化失败："+e.message},500);}let body;try{body=await request.json();}catch(e){return json({ok:false,error:"请求格式有误"},400);}const action=clean(body.action,32)||"list";
  if(action==="list"){const status=body.status==="trash"?"trash":"active",rows=await env.DB.prepare("SELECT * FROM personal_notes WHERE user_id=? AND status=? ORDER BY kind DESC,sort_order ASC,updated_at DESC LIMIT 2000").bind(user.userId,status).all();return json({ok:true,items:(rows.results||[]).map(output)});}
  if(action==="get"){const row=await owned(env,user,clean(body.id,80));if(!row)return json({ok:false,error:"笔记不存在或无权访问"},404);const back=await env.DB.prepare("SELECT l.from_note_id,n.title FROM personal_note_links l LEFT JOIN personal_notes n ON n.id=l.from_note_id AND n.user_id=l.user_id WHERE l.user_id=? AND (l.to_note_id=? OR LOWER(l.target_title)=LOWER(?)) AND n.status='active' ORDER BY n.updated_at DESC").bind(user.userId,row.id,row.title).all(),out=await env.DB.prepare("SELECT to_note_id,target_title,link_text FROM personal_note_links WHERE user_id=? AND from_note_id=? ORDER BY created_at").bind(user.userId,row.id).all();return json({ok:true,item:output(row),backlinks:back.results||[],outlinks:out.results||[]});}
  if(action==="create"){const kind=body.kind==="folder"?"folder":"note",parentId=clean(body.parentId,80);if(parentId){const parent=await owned(env,user,parentId,false);if(!parent||parent.kind!=="folder")return json({ok:false,error:"目标文件夹不存在"},400);}const id=makeId(kind==="folder"?"pf_":"pn_"),now=Date.now(),title=clean(body.title,120)||(kind==="folder"?"新建文件夹":"未命名笔记"),content=kind==="note"?clean(body.content):"";await env.DB.prepare("INSERT INTO personal_notes(id,user_id,parent_id,kind,title,content,tags,favorite,status,source_name,source_type,revision,sort_order,created_at,updated_at,deleted_at) VALUES(?,?,?,?,?,?,?,0,'active',?,?,1,0,?,?,0)").bind(id,user.userId,parentId,kind,title,content,JSON.stringify(tagsOf(body.tags)),clean(body.sourceName,180),clean(body.sourceType,40),now,now).run();const row=await owned(env,user,id);if(kind==="note")await refreshLinks(env,user,row);return json({ok:true,item:output(row)});}
  if(action==="save"){const id=clean(body.id,80),row=await owned(env,user,id,false);if(!row)return json({ok:false,error:"笔记不存在或无权修改"},404);const expected=Number(body.revision||0);if(expected&&expected!==Number(row.revision||1))return json({ok:false,error:"该笔记已在其他页面更新，请先刷新后再保存",conflict:true,current:output(row)},409);const parentId=body.parentId===undefined?row.parent_id:clean(body.parentId,80);if(parentId&&parentId!==row.parent_id){const parent=await owned(env,user,parentId,false),desc=row.kind==="folder"?await descendantIds(env,user,row.id):[];if(!parent||parent.kind!=="folder"||parent.id===id||desc.includes(parentId))return json({ok:false,error:"目标文件夹无效或会形成循环层级"},400);}await snapshot(env,user,row,!!body.checkpoint);const title=clean(body.title,120)||row.title,content=row.kind==="note"?clean(body.content):"",tags=JSON.stringify(tagsOf(body.tags)),favorite=body.favorite?1:0,now=Date.now();await env.DB.prepare("UPDATE personal_notes SET parent_id=?,title=?,content=?,tags=?,favorite=?,revision=revision+1,updated_at=? WHERE id=? AND user_id=?").bind(parentId,title,content,tags,favorite,now,id,user.userId).run();const saved=await owned(env,user,id);if(saved.kind==="note")await refreshLinks(env,user,saved);return json({ok:true,item:output(saved)});}
  if(action==="trash"||action==="restore"){const id=clean(body.id,80),row=await owned(env,user,id);if(!row)return json({ok:false,error:"条目不存在"},404);const status=action==="trash"?"trash":"active",now=Date.now(),ids=row.kind==="folder"?await descendantIds(env,user,id):[id];for(const itemId of ids)await env.DB.prepare("UPDATE personal_notes SET status=?,deleted_at=?,updated_at=?,revision=revision+1 WHERE id=? AND user_id=?").bind(status,status==="trash"?now:0,now,itemId,user.userId).run();return json({ok:true,status,affected:ids.length});}
  if(action==="versions"){const row=await owned(env,user,clean(body.id,80));if(!row)return json({ok:false,error:"笔记不存在"},404);const rows=await env.DB.prepare("SELECT id,revision,title,tags,created_at FROM personal_note_versions WHERE note_id=? AND user_id=? ORDER BY created_at DESC LIMIT 30").bind(row.id,user.userId).all();return json({ok:true,current:output(row),versions:(rows.results||[]).map(x=>({...x,tags:parseJson(x.tags,[]),created_at:Number(x.created_at||0)}))});}
  if(action==="restoreVersion"){const row=await owned(env,user,clean(body.id,80),false);if(!row)return json({ok:false,error:"笔记不存在"},404);const ver=await env.DB.prepare("SELECT * FROM personal_note_versions WHERE id=? AND note_id=? AND user_id=?").bind(clean(body.versionId,80),row.id,user.userId).first();if(!ver)return json({ok:false,error:"历史版本不存在"},404);await snapshot(env,user,row,true);const now=Date.now();await env.DB.prepare("UPDATE personal_notes SET title=?,content=?,tags=?,revision=revision+1,updated_at=? WHERE id=? AND user_id=?").bind(ver.title,ver.content,ver.tags,now,row.id,user.userId).run();const saved=await owned(env,user,row.id);await refreshLinks(env,user,saved);return json({ok:true,item:output(saved)});}
  if(action==="search"){const q=clean(body.query,200).toLowerCase();if(!q)return json({ok:true,items:[]});const like="%"+q+"%",rows=await env.DB.prepare("SELECT * FROM personal_notes WHERE user_id=? AND status='active' AND kind='note' AND (LOWER(title) LIKE ? OR LOWER(content) LIKE ? OR LOWER(tags) LIKE ?) ORDER BY favorite DESC,updated_at DESC LIMIT 100").bind(user.userId,like,like,like).all();return json({ok:true,items:(rows.results||[]).map(output)});}
  if(action==="context"){const scope=["current","folder","all"].includes(body.scope)?body.scope:"current",id=clean(body.id,80),question=clean(body.question,1000),current=id?await owned(env,user,id,false):null;if(id&&!current)return json({ok:false,error:"笔记不存在"},404);let rows=[];if(scope==="current")rows=current?[current]:[];else if(scope==="folder"){const parent=current?(current.kind==="folder"?current.id:current.parent_id):"",r=await env.DB.prepare("SELECT * FROM personal_notes WHERE user_id=? AND status='active' AND kind='note' AND parent_id=? ORDER BY updated_at DESC LIMIT 200").bind(user.userId,parent).all();rows=r.results||[];}else{const r=await env.DB.prepare("SELECT * FROM personal_notes WHERE user_id=? AND status='active' AND kind='note' ORDER BY updated_at DESC LIMIT 500").bind(user.userId).all();rows=r.results||[];}const words=tokens(question),ranked=rows.map(x=>({x,s:score(x,words)})).sort((a,b)=>b.s-a.s||Number(b.x.updated_at)-Number(a.x.updated_at)).slice(0,8);let used=0;const notes=[];for(const r of ranked){const remain=24000-used;if(remain<=0)break;const content=String(r.x.content||"").slice(0,Math.min(6000,remain));used+=content.length;notes.push({id:r.x.id,title:r.x.title,revision:Number(r.x.revision||1),content});}return json({ok:true,scope,notes});}
  return json({ok:false,error:"未知操作"},400);
}
