// /api/projectanalysis —— 项目人口、职住、通勤、需求、POI分析数据与正式快照。
// 结构化数字只进入本模块；RAG/Wiki仅提供定义和文字依据，AI不得绕过审核状态取数。
import { verifyAuth, json } from "./_auth.js";
import { adaptEnv } from "./_adapters.js";
import "../../analysis-core.js";
const Core=globalThis.AnalysisCore;
function isAdmin(env,u){const a=(env.ADMIN_USERS||"").split(",").map(x=>x.trim()).filter(Boolean);return a.includes(u.username)||a.includes(String(u.userId));}
function passOk(env,r){return !env.ADMIN_PASS||r.headers.get("x-admin-pass")===env.ADMIN_PASS;}
function text(v,n=300){return String(v??"").trim().slice(0,n);}
function id(prefix){return prefix+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,10);}
function parse(v,f={}){try{return JSON.parse(v||"");}catch(e){return f;}}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null;}
let ready=false,ensurePromise=null;
async function ensure(env){
  if(ready)return;
  if(ensurePromise)return ensurePromise;
  ensurePromise=(async()=>{const ts=env.DEPLOY_MODE==="local"?"BIGINT":"INTEGER",real=env.DEPLOY_MODE==="local"?"DOUBLE PRECISION":"REAL";
  const sql=[
    "CREATE TABLE IF NOT EXISTS analysis_metric_catalog (metric_key TEXT PRIMARY KEY,metric_name TEXT NOT NULL,domain TEXT NOT NULL,unit TEXT DEFAULT '',value_type TEXT NOT NULL DEFAULT 'number',definition TEXT DEFAULT '',formula TEXT DEFAULT '',direction TEXT DEFAULT 'neutral',required_level TEXT DEFAULT 'general',default_scope "+real+" DEFAULT 3,default_period TEXT DEFAULT '',enabled INTEGER NOT NULL DEFAULT 1,updated_at "+ts+" NOT NULL)",
    "CREATE TABLE IF NOT EXISTS project_analysis_scopes (project_id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,longitude "+real+",latitude "+real+",scope_type TEXT NOT NULL DEFAULT 'radius',scope_value TEXT NOT NULL DEFAULT '1,3,5',scope_geojson TEXT DEFAULT '',confirmed_by TEXT DEFAULT '',confirmed_at "+ts+" DEFAULT 0,updated_at "+ts+" NOT NULL)",
    "CREATE TABLE IF NOT EXISTS analysis_observations (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,metric_key TEXT NOT NULL,scope_type TEXT NOT NULL DEFAULT 'radius',scope_value "+real+" DEFAULT 3,period_start TEXT DEFAULT '',period_end TEXT DEFAULT '',value_num "+real+",value_text TEXT DEFAULT '',value_json TEXT DEFAULT '',unit TEXT DEFAULT '',source_asset_id TEXT DEFAULT '',source_version_id TEXT DEFAULT '',workbook_id TEXT DEFAULT '',sheet_name TEXT DEFAULT '',cell_address TEXT DEFAULT '',source_label TEXT DEFAULT '',quality_grade TEXT DEFAULT 'C',review_status TEXT NOT NULL DEFAULT 'pending',reviewed_by TEXT DEFAULT '',reviewed_at "+ts+" DEFAULT 0,created_by TEXT DEFAULT '',created_at "+ts+" NOT NULL,updated_at "+ts+" NOT NULL)",
    "CREATE TABLE IF NOT EXISTS project_pois (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,subcategory TEXT DEFAULT '',longitude "+real+",latitude "+real+",distance_m "+real+",level TEXT DEFAULT '',level_weight "+real+" DEFAULT 1,status TEXT DEFAULT '',address TEXT DEFAULT '',source_asset_id TEXT DEFAULT '',source_version_id TEXT DEFAULT '',workbook_id TEXT DEFAULT '',sheet_name TEXT DEFAULT '',cell_address TEXT DEFAULT '',source_label TEXT DEFAULT '',review_status TEXT NOT NULL DEFAULT 'pending',observed_at TEXT DEFAULT '',reviewed_by TEXT DEFAULT '',reviewed_at "+ts+" DEFAULT 0,created_at "+ts+" NOT NULL,updated_at "+ts+" NOT NULL)",
    "CREATE TABLE IF NOT EXISTS project_od_flows (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,origin_id TEXT DEFAULT '',origin_name TEXT NOT NULL,destination_id TEXT DEFAULT '',destination_name TEXT NOT NULL,flow_type TEXT NOT NULL DEFAULT 'home_to_work',population "+real+" NOT NULL,distance_km "+real+",period_start TEXT DEFAULT '',period_end TEXT DEFAULT '',source_asset_id TEXT DEFAULT '',source_version_id TEXT DEFAULT '',workbook_id TEXT DEFAULT '',sheet_name TEXT DEFAULT '',cell_address TEXT DEFAULT '',source_label TEXT DEFAULT '',review_status TEXT NOT NULL DEFAULT 'pending',reviewed_by TEXT DEFAULT '',reviewed_at "+ts+" DEFAULT 0,created_at "+ts+" NOT NULL,updated_at "+ts+" NOT NULL)",
    "CREATE TABLE IF NOT EXISTS analysis_rules (rule_key TEXT PRIMARY KEY,domain TEXT NOT NULL,draft_data TEXT NOT NULL DEFAULT '{}',published_data TEXT NOT NULL DEFAULT '{}',draft_version INTEGER NOT NULL DEFAULT 1,published_version INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'published',updated_by TEXT DEFAULT '',updated_at "+ts+" NOT NULL,published_by TEXT DEFAULT '',published_at "+ts+" DEFAULT 0)",
    "CREATE TABLE IF NOT EXISTS analysis_chapter_mappings (domain TEXT NOT NULL,chapter_keyword TEXT NOT NULL,section_keyword TEXT DEFAULT '',enabled INTEGER NOT NULL DEFAULT 1,updated_at "+ts+" NOT NULL,PRIMARY KEY(domain,chapter_keyword,section_keyword))",
    "CREATE TABLE IF NOT EXISTS project_analysis_snapshots (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id INTEGER NOT NULL,version INTEGER NOT NULL,scope_value "+real+" NOT NULL DEFAULT 3,input_data TEXT NOT NULL DEFAULT '{}',result_data TEXT NOT NULL DEFAULT '{}',result_hash TEXT NOT NULL,rule_versions TEXT NOT NULL DEFAULT '{}',source_summary TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'official',created_by TEXT DEFAULT '',created_at "+ts+" NOT NULL,UNIQUE(project_id,user_id,version))",
  ];for(const s of sql)await env.DB.prepare(s).run();
  if(env.DEPLOY_MODE==="local"){for(const table of ["project_pois","project_od_flows"]){for(const col of ["source_version_id TEXT DEFAULT ''","workbook_id TEXT DEFAULT ''","sheet_name TEXT DEFAULT ''","cell_address TEXT DEFAULT ''"]){try{await env.DB.prepare("ALTER TABLE "+table+" ADD COLUMN IF NOT EXISTS "+col).run();}catch(e){}}}}
  const now=Date.now();
  for(const m of Core.METRICS)await env.DB.prepare("INSERT INTO analysis_metric_catalog(metric_key,metric_name,domain,unit,required_level,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(metric_key) DO NOTHING").bind(m.key,m.name,m.domain,m.unit,m.level,now).run();
  for(const r of Core.LOGIC_RULES){const data=JSON.stringify(r);await env.DB.prepare("INSERT INTO analysis_rules(rule_key,domain,draft_data,published_data,draft_version,published_version,status,updated_by,updated_at,published_by,published_at) VALUES(?,?,?,?,1,1,'published','system',?,'system',?) ON CONFLICT(rule_key) DO NOTHING").bind(r.key,r.domain,data,data,now,now).run();for(const ch of (r.chapters||[]))await env.DB.prepare("INSERT INTO analysis_chapter_mappings(domain,chapter_keyword,section_keyword,enabled,updated_at) VALUES(?,?,?,1,?) ON CONFLICT(domain,chapter_keyword,section_keyword) DO NOTHING").bind(r.domain,String(ch),"",now).run();}
  ready=true;
  })().catch(e=>{ensurePromise=null;throw e;});
  return ensurePromise;
}
async function loadRules(env,includeDraft=false){const r=await env.DB.prepare("SELECT * FROM analysis_rules ORDER BY rule_key").all(),list=(r.results||[]).map(x=>{const published=parse(x.published_data,{}),draft=parse(x.draft_data,published);return{key:x.rule_key,domain:x.domain,status:x.status,draftVersion:Number(x.draft_version||1),publishedVersion:Number(x.published_version||0),updatedBy:x.updated_by||"",updatedAt:x.updated_at||0,publishedBy:x.published_by||"",publishedAt:x.published_at||0,published,...(includeDraft?{draft}: {})};}),map={},versions={};list.forEach(x=>{map[x.key]=x.published;versions[x.key]=x.publishedVersion;});return{list,map,versions};}
async function owns(env,user,pid){if(!pid)return false;const p=await env.DB.prepare("SELECT user_id FROM projects WHERE id=?").bind(pid).first();return !!p&&Number(p.user_id)===Number(user.userId);}
async function load(env,user,pid,approvedOnly=false){const cond=approvedOnly?" AND review_status='approved'":"";
  const scope=await env.DB.prepare("SELECT * FROM project_analysis_scopes WHERE project_id=? AND user_id=?").bind(pid,user.userId).first();
  const o=await env.DB.prepare("SELECT * FROM analysis_observations WHERE project_id=? AND user_id=?"+cond+" ORDER BY updated_at DESC").bind(pid,user.userId).all();
  const p=await env.DB.prepare("SELECT * FROM project_pois WHERE project_id=? AND user_id=?"+cond+" ORDER BY updated_at DESC").bind(pid,user.userId).all();
  const d=await env.DB.prepare("SELECT * FROM project_od_flows WHERE project_id=? AND user_id=?"+cond+" ORDER BY updated_at DESC").bind(pid,user.userId).all();
  return{scope,observations:(o.results||[]).map(x=>({id:x.id,metricKey:x.metric_key,scopeKm:x.scope_value,value:x.value_num??x.value_text,unit:x.unit,periodStart:x.period_start,periodEnd:x.period_end,sourceAssetId:x.source_asset_id,sourceVersionId:x.source_version_id,workbookId:x.workbook_id,sheetName:x.sheet_name,cellAddress:x.cell_address,sourceLabel:x.source_label,qualityGrade:x.quality_grade,reviewStatus:x.review_status})),
    pois:(p.results||[]).map(x=>({id:x.id,name:x.name,category:x.category,subcategory:x.subcategory,longitude:x.longitude,latitude:x.latitude,levelWeight:x.level_weight,address:x.address,sourceAssetId:x.source_asset_id,sourceVersionId:x.source_version_id,workbookId:x.workbook_id,sheetName:x.sheet_name,cellAddress:x.cell_address,sourceLabel:x.source_label,reviewStatus:x.review_status})),
    odFlows:(d.results||[]).map(x=>({id:x.id,originName:x.origin_name,destinationName:x.destination_name,flowType:x.flow_type,population:x.population,distanceKm:x.distance_km,periodStart:x.period_start,periodEnd:x.period_end,sourceAssetId:x.source_asset_id,sourceVersionId:x.source_version_id,workbookId:x.workbook_id,sheetName:x.sheet_name,cellAddress:x.cell_address,sourceLabel:x.source_label,reviewStatus:x.review_status}))};
}
function provenance(x){return{sourceAssetId:text(x.sourceAssetId,80),sourceVersionId:text(x.sourceVersionId,80),workbookId:text(x.workbookId,80),sheetName:text(x.sheetName,120),cellAddress:text(x.cellAddress,30),sourceLabel:text(x.sourceLabel,240)};}
async function submitRows(env,user,pid,kind,rows){const now=Date.now(),saved=[];for(const raw of (Array.isArray(rows)?rows:[]).slice(0,2000)){const rid=id(kind==="observation"?"obs":kind==="poi"?"poi":"od"),pv=provenance(raw);
    if(kind==="observation"){const key=text(raw.metricKey,80),v=finite(raw.value);if(!key||v===null)continue;await env.DB.prepare("INSERT INTO analysis_observations(id,project_id,user_id,metric_key,scope_value,period_start,period_end,value_num,unit,source_asset_id,source_version_id,workbook_id,sheet_name,cell_address,source_label,quality_grade,review_status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(rid,pid,user.userId,key,finite(raw.scopeKm)||3,text(raw.periodStart,10),text(raw.periodEnd,10),v,text(raw.unit,30),pv.sourceAssetId,pv.sourceVersionId,pv.workbookId,pv.sheetName,pv.cellAddress,pv.sourceLabel,["A","B","C","D"].includes(raw.qualityGrade)?raw.qualityGrade:"C","pending",user.username,now,now).run();}
    else if(kind==="poi"){const name=text(raw.name,160),cat=text(raw.category,40),lat=finite(raw.latitude),lon=finite(raw.longitude);if(!name||!Core.POI_CATEGORIES[cat]||lat===null||lon===null)continue;await env.DB.prepare("INSERT INTO project_pois(id,project_id,user_id,name,category,subcategory,longitude,latitude,level_weight,address,source_asset_id,source_version_id,workbook_id,sheet_name,cell_address,source_label,review_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(rid,pid,user.userId,name,cat,text(raw.subcategory,80),lon,lat,finite(raw.levelWeight)||1,text(raw.address,240),pv.sourceAssetId,pv.sourceVersionId,pv.workbookId,pv.sheetName,pv.cellAddress,pv.sourceLabel,"pending",now,now).run();}
    else{const a=text(raw.originName,120),b=text(raw.destinationName,120),pop=finite(raw.population);if(!a||!b||pop===null||pop<0)continue;await env.DB.prepare("INSERT INTO project_od_flows(id,project_id,user_id,origin_name,destination_name,flow_type,population,distance_km,period_start,period_end,source_asset_id,source_version_id,workbook_id,sheet_name,cell_address,source_label,review_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(rid,pid,user.userId,a,b,["home_to_work","work_to_home","other"].includes(raw.flowType)?raw.flowType:"home_to_work",pop,finite(raw.distanceKm),text(raw.periodStart,10),text(raw.periodEnd,10),pv.sourceAssetId,pv.sourceVersionId,pv.workbookId,pv.sheetName,pv.cellAddress,pv.sourceLabel,"pending",now,now).run();}saved.push(rid);}return saved;}
export async function onRequestGet(context){const {request}=context,env=adaptEnv(context.env),user=await verifyAuth(request,env);if(!user)return json({ok:false,error:"未登录"},401);await ensure(env);const u=new URL(request.url),pid=text(u.searchParams.get("projectId"),64),action=u.searchParams.get("action")||"workspace";
  if(action==="catalog"){const r=await env.DB.prepare("SELECT * FROM analysis_metric_catalog WHERE enabled=1 ORDER BY domain,metric_key").all(),rules=await loadRules(env);return json({ok:true,metrics:r.results||[],poiCategories:Core.POI_CATEGORIES,provider:Core.providerContract(),chapterMap:Core.CHAPTER_MAP,logicRules:rules.list.map(x=>({key:x.key,domain:x.domain,publishedVersion:x.publishedVersion,published:x.published}))});}
  if(!await owns(env,user,pid))return json({ok:false,error:"项目不存在或无权限"},404);
  if(action==="snapshots"){const r=await env.DB.prepare("SELECT id,version,scope_value,result_hash,source_summary,status,created_by,created_at FROM project_analysis_snapshots WHERE project_id=? AND user_id=? ORDER BY version DESC LIMIT 30").bind(pid,user.userId).all();return json({ok:true,snapshots:r.results||[]});}
  const data=await load(env,user,pid,false),official=await load(env,user,pid,true),scope=official.scope||data.scope||{},rules=await loadRules(env),result=Core.analyze({scopeKm:Number(u.searchParams.get("scope"))||3,project:{longitude:scope.longitude,latitude:scope.latitude},observations:official.observations,pois:official.pois,odFlows:official.odFlows,rules:rules.map});return json({ok:true,...data,officialResult:result,ruleVersions:rules.versions,provider:Core.providerContract()});
}
export async function onRequestPost(context){const {request}=context,env=adaptEnv(context.env),user=await verifyAuth(request,env);if(!user)return json({ok:false,error:"未登录"},401);await ensure(env);let b;try{b=await request.json();}catch(e){return json({ok:false,error:"格式有误"},400);}const action=text(b.action,40),pid=text(b.projectId,64);
  if(action==="listRules"){if(!isAdmin(env,user)||!passOk(env,request))return json({ok:false,error:"仅管理员可维护研判逻辑"},403);const rules=await loadRules(env,true);return json({ok:true,rules:rules.list,metrics:Core.METRICS,poiCategories:Core.POI_CATEGORIES});}
  if(action==="saveRuleDraft"){if(!isAdmin(env,user)||!passOk(env,request))return json({ok:false,error:"仅管理员可维护研判逻辑"},403);const key=text(b.key,80),old=await env.DB.prepare("SELECT draft_version FROM analysis_rules WHERE rule_key=?").bind(key).first();if(!old)return json({ok:false,error:"规则不存在"},404);const source=b.rule&&typeof b.rule==="object"?b.rule:{},rule={key,name:text(source.name,100),domain:text(source.domain,40),purpose:text(source.purpose,500),inputs:(Array.isArray(source.inputs)?source.inputs:[]).map(x=>text(x,100)).filter(Boolean).slice(0,30),formula:text(source.formula,1000),thresholds:text(source.thresholds,1000),missingPolicy:text(source.missingPolicy,600),outputs:(Array.isArray(source.outputs)?source.outputs:[]).map(x=>text(x,100)).filter(Boolean).slice(0,30),chapters:(Array.isArray(source.chapters)?source.chapters:[]).map(x=>text(x,100)).filter(Boolean).slice(0,30),config:source.config&&typeof source.config==="object"?source.config:{}};if(!rule.name||!rule.domain||!rule.formula||!rule.missingPolicy)return json({ok:false,error:"名称、领域、公式和缺数处理不能为空"},400);await env.DB.prepare("UPDATE analysis_rules SET domain=?,draft_data=?,draft_version=draft_version+1,status='draft',updated_by=?,updated_at=? WHERE rule_key=?").bind(rule.domain,JSON.stringify(rule),user.username,Date.now(),key).run();return json({ok:true,message:"草稿已保存，尚未影响前台分析"});}
  if(action==="publishRule"){if(!isAdmin(env,user)||!passOk(env,request))return json({ok:false,error:"仅管理员可发布研判逻辑"},403);const key=text(b.key,80),old=await env.DB.prepare("SELECT draft_data,draft_version FROM analysis_rules WHERE rule_key=?").bind(key).first();if(!old)return json({ok:false,error:"规则不存在"},404);const now=Date.now(),draft=parse(old.draft_data,{});await env.DB.prepare("UPDATE analysis_rules SET published_data=draft_data,published_version=draft_version,status='published',published_by=?,published_at=?,updated_by=?,updated_at=? WHERE rule_key=?").bind(user.username,now,user.username,now,key).run();for(const ch of (Array.isArray(draft.chapters)?draft.chapters:[]))await env.DB.prepare("INSERT INTO analysis_chapter_mappings(domain,chapter_keyword,section_keyword,enabled,updated_at) VALUES(?,?,?,1,?) ON CONFLICT(domain,chapter_keyword,section_keyword) DO NOTHING").bind(text(draft.domain,40),text(ch,100),"",now).run();return json({ok:true,message:"规则已发布，新形成的分析结果与快照将采用该版本"});}
  if(action==="reviewQueue"){if(!isAdmin(env,user)||!passOk(env,request))return json({ok:false,error:"仅管理员可审核"},403);const status=text(b.status,20)||"pending",out=[];for(const [kind,table] of [["observation","analysis_observations"],["poi","project_pois"],["od","project_od_flows"]]){const r=await env.DB.prepare("SELECT * FROM "+table+" WHERE review_status=? ORDER BY updated_at DESC LIMIT 200").bind(status).all();(r.results||[]).forEach(x=>out.push({kind,...x}));}return json({ok:true,items:out});}
  if(action==="review"){if(!isAdmin(env,user)||!passOk(env,request))return json({ok:false,error:"仅管理员可审核"},403);const tables={observation:"analysis_observations",poi:"project_pois",od:"project_od_flows"},table=tables[b.kind],decision=b.decision==="approve"?"approved":b.decision==="reject"?"rejected":"";if(!table||!decision)return json({ok:false,error:"审核参数无效"},400);await env.DB.prepare("UPDATE "+table+" SET review_status=?,reviewed_by=?,reviewed_at=?,updated_at=? WHERE id=?").bind(decision,user.username,Date.now(),Date.now(),text(b.id,100)).run();return json({ok:true,status:decision});}
  if(!await owns(env,user,pid))return json({ok:false,error:"项目不存在或无权限"},404);
  if(action==="saveScope"){const lon=finite(b.longitude),lat=finite(b.latitude);if(lon===null||lat===null||Math.abs(lon)>180||Math.abs(lat)>90)return json({ok:false,error:"经纬度不合法"},400);const old=await env.DB.prepare("SELECT project_id FROM project_analysis_scopes WHERE project_id=?").bind(pid).first(),now=Date.now();if(old)await env.DB.prepare("UPDATE project_analysis_scopes SET longitude=?,latitude=?,scope_value=?,confirmed_by=?,confirmed_at=?,updated_at=? WHERE project_id=? AND user_id=?").bind(lon,lat,"1,3,5",user.username,now,now,pid,user.userId).run();else await env.DB.prepare("INSERT INTO project_analysis_scopes(project_id,user_id,longitude,latitude,scope_value,confirmed_by,confirmed_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").bind(pid,user.userId,lon,lat,"1,3,5",user.username,now,now).run();return json({ok:true});}
  if(action==="submit"){const kind=["observation","poi","od"].includes(b.kind)?b.kind:"",saved=kind?await submitRows(env,user,pid,kind,b.rows):[];return json({ok:true,saved:saved.length,status:"pending",message:"已提交管理员审核，审核前不参与正式分析"});}
  if(action==="snapshot"){const data=await load(env,user,pid,true),scope=data.scope||{},scopeKm=finite(b.scopeKm)||3,rules=await loadRules(env),result=Core.analyze({scopeKm,project:{longitude:scope.longitude,latitude:scope.latitude},observations:data.observations,pois:data.pois,odFlows:data.odFlows,rules:rules.map}),last=await env.DB.prepare("SELECT MAX(version) AS n FROM project_analysis_snapshots WHERE project_id=? AND user_id=?").bind(pid,user.userId).first(),version=Number(last&&last.n||0)+1,sid=id("asnap"),sources=[...data.observations,...data.pois,...data.odFlows].map(x=>({sourceAssetId:x.sourceAssetId||"",sourceLabel:x.sourceLabel||"",workbookId:x.workbookId||"",sheetName:x.sheetName||"",cellAddress:x.cellAddress||""})).filter(x=>x.sourceAssetId||x.sourceLabel||x.workbookId);await env.DB.prepare("INSERT INTO project_analysis_snapshots(id,project_id,user_id,version,scope_value,input_data,result_data,result_hash,rule_versions,source_summary,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(sid,pid,user.userId,version,scopeKm,JSON.stringify(data),JSON.stringify(result),result.hash,JSON.stringify(rules.versions),JSON.stringify(sources),result.ready?"official":"incomplete",user.username,Date.now()).run();return json({ok:true,snapshot:{id:sid,version,status:result.ready?"official":"incomplete",ruleVersions:rules.versions,result}});}
  if(action==="diff"){const a=await env.DB.prepare("SELECT result_data FROM project_analysis_snapshots WHERE id=? AND project_id=? AND user_id=?").bind(text(b.beforeId,100),pid,user.userId).first(),z=await env.DB.prepare("SELECT result_data FROM project_analysis_snapshots WHERE id=? AND project_id=? AND user_id=?").bind(text(b.afterId,100),pid,user.userId).first();if(!a||!z)return json({ok:false,error:"快照不存在"},404);return json({ok:true,preview:Core.impactPreview(parse(a.result_data,{}),parse(z.result_data,{}))});}
  return json({ok:false,error:"未知操作"},400);
}
