// AI可研黄金项目库：候选提交、管理员发布、离线重复评测。
import { verifyAuth, json } from "./_auth.js";
import { adaptEnv } from "./_adapters.js";
import "../../report-golden.js";
import "../../report-evidence-graph.js";

const clean=(v,n=200)=>String(v==null?"":v).trim().slice(0,n);
const parse=(v,d)=>{try{return JSON.parse(v||"");}catch(_){return d;}};
const admins=(env,user)=>String(env.ADMIN_USERS||"").split(",").map(x=>x.trim()).filter(Boolean).some(x=>x===user.username||x===String(user.userId));
const passOk=(env,request)=>!env.ADMIN_PASS||request.headers.get("x-admin-pass")===env.ADMIN_PASS;
const uid=p=>p+"-"+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));
function hash(v){const s=JSON.stringify(v||{});let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16);}
async function ensure(env){const ts=env.DEPLOY_MODE==="local"?"BIGINT":"INTEGER";await env.DB.prepare("CREATE TABLE IF NOT EXISTS report_golden_samples (id TEXT PRIMARY KEY,name TEXT NOT NULL,calc_type TEXT NOT NULL DEFAULT '',region TEXT NOT NULL DEFAULT '',tags_json TEXT NOT NULL DEFAULT '[]',source_project_id TEXT NOT NULL DEFAULT '',sample_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'candidate',user_id INTEGER NOT NULL,created_by TEXT NOT NULL DEFAULT '',created_at "+ts+" NOT NULL,updated_at "+ts+" NOT NULL)").run();await env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_report_golden_samples_status ON report_golden_samples(status,calc_type,updated_at)").run();await env.DB.prepare("CREATE TABLE IF NOT EXISTS report_golden_runs (id TEXT PRIMARY KEY,sample_id TEXT NOT NULL,user_id INTEGER NOT NULL,score INTEGER NOT NULL DEFAULT 0,passed INTEGER NOT NULL DEFAULT 0,metrics_json TEXT NOT NULL DEFAULT '{}',result_json TEXT NOT NULL DEFAULT '{}',candidate_hash TEXT NOT NULL DEFAULT '',created_at "+ts+" NOT NULL)").run();await env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_report_golden_runs_sample ON report_golden_runs(sample_id,created_at)").run();}
function golden(){const g=globalThis.ReportGolden;if(!g)throw new Error("黄金评测模块未加载");return g;}
function rowOut(x,full=false){const out={id:x.id,name:x.name,calcType:x.calc_type,region:x.region,tags:parse(x.tags_json,[]),sourceProjectId:x.source_project_id,status:x.status,createdBy:x.created_by,createdAt:x.created_at,updatedAt:x.updated_at};if(full)out.sample=parse(x.sample_json,{});return out;}

export async function onRequestGet(context){const env=adaptEnv(context.env),user=await verifyAuth(context.request,env);if(!user)return json({ok:false,error:"未登录或登录已过期"},401);await ensure(env);const url=new URL(context.request.url),id=clean(url.searchParams.get("id"),120),status=clean(url.searchParams.get("status"),20);if(id){const row=await env.DB.prepare("SELECT * FROM report_golden_samples WHERE id=?").bind(id).first();if(!row)return json({ok:false,error:"黄金样本不存在"},404);if(row.status!=="published"&&row.user_id!==user.userId&&!admins(env,user))return json({ok:false,error:"无权查看该候选样本"},403);const runs=(await env.DB.prepare("SELECT id,score,passed,metrics_json,result_json,created_at FROM report_golden_runs WHERE sample_id=? ORDER BY created_at DESC LIMIT 30").bind(id).all()).results||[];return json({ok:true,item:rowOut(row,true),runs:runs.map(x=>({...x,metrics:parse(x.metrics_json,{}),result:parse(x.result_json,{})}))});}let sql="SELECT * FROM report_golden_samples",bind=[];if(status){sql+=" WHERE status=?";bind.push(status);}else if(!admins(env,user)){sql+=" WHERE status='published' OR user_id=?";bind.push(user.userId);}sql+=" ORDER BY updated_at DESC LIMIT 100";const rows=(await env.DB.prepare(sql).bind(...bind).all()).results||[];return json({ok:true,list:rows.map(x=>rowOut(x,false))});}

export async function onRequestPost(context){const env=adaptEnv(context.env),request=context.request,user=await verifyAuth(request,env);if(!user)return json({ok:false,error:"未登录或登录已过期"},401);await ensure(env);let b;try{b=await request.json();}catch(_){return json({ok:false,error:"请求格式有误"},400);}const action=clean(b.action,30)||"create";
  if(action==="create"){
    const sample=golden().createSample(b.sample||b),name=clean(sample.name,120);if(!name||!(sample.sections||[]).length)return json({ok:false,error:"黄金样本至少需要项目名称和一节正式报告内容"},400);const raw=JSON.stringify(sample);if(raw.length>3000000)return json({ok:false,error:"样本超过3MB，请移除原始附件，仅保留结构、事实和期望结果"},413);const id=uid("golden"),now=Date.now(),status=admins(env,user)&&passOk(env,request)&&b.publish===true?"published":"candidate";await env.DB.prepare("INSERT INTO report_golden_samples(id,name,calc_type,region,tags_json,source_project_id,sample_json,status,user_id,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,name,clean(sample.calcType,30),clean(sample.region,120),JSON.stringify(sample.tags||[]),clean(sample.sourceProjectId,120),raw,status,user.userId,user.username||"",now,now).run();return json({ok:true,id,status,message:status==="published"?"黄金样本已发布":"已提交黄金样本候选，管理员发布后进入正式评测集"});
  }
  if(action==="evaluate"){
    const id=clean(b.sampleId,120),row=await env.DB.prepare("SELECT * FROM report_golden_samples WHERE id=?").bind(id).first();if(!row)return json({ok:false,error:"黄金样本不存在"},404);if(row.status!=="published"&&row.user_id!==user.userId&&!admins(env,user))return json({ok:false,error:"无权运行该样本"},403);const sample=parse(row.sample_json,{}),candidate=b.candidate||(()=>{const by=new Map();(sample.sections||[]).forEach(s=>{const key=s.chapter||"未分类",c=by.get(key)||{cn:by.size+1,name:key,sections:[]};c.sections.push({t:s.title,content:s.text,numeric:s.numeric,trust:s.trust,prov:s.prov});by.set(key,c);});return {chapters:[...by.values()],facts:sample.expectedFacts||{},summary:sample.expectedFacts||{}};})(),audit=globalThis.ReportEvidenceGraph?globalThis.ReportEvidenceGraph.preSubmitAudit(candidate.chapters||[]):null,result=golden().evaluate(sample,{...candidate,preSubmitAudit:audit||candidate.preSubmitAudit}),runId=uid("grun"),now=Date.now();await env.DB.prepare("INSERT INTO report_golden_runs(id,sample_id,user_id,score,passed,metrics_json,result_json,candidate_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(runId,id,user.userId,result.score,result.passed?1:0,JSON.stringify(result.metrics),JSON.stringify(result),hash(candidate),now).run();return json({ok:true,runId,result});
  }
  return json({ok:false,error:"未知操作"},400);
}

export async function onRequestPatch(context){const env=adaptEnv(context.env),request=context.request,user=await verifyAuth(request,env);if(!user)return json({ok:false,error:"未登录或登录已过期"},401);if(!admins(env,user)||!passOk(env,request))return json({ok:false,error:"仅管理员可发布或归档黄金样本"},403);await ensure(env);const id=clean(new URL(request.url).searchParams.get("id"),120);let b={};try{b=await request.json();}catch(_){}const status=["published","archived","candidate"].includes(b.status)?b.status:null;if(!id||!status)return json({ok:false,error:"缺少样本ID或状态"},400);await env.DB.prepare("UPDATE report_golden_samples SET status=?,updated_at=? WHERE id=?").bind(status,Date.now(),id).run();return json({ok:true,status});}
export async function onRequestDelete(context){const env=adaptEnv(context.env),request=context.request,user=await verifyAuth(request,env);if(!user)return json({ok:false,error:"未登录或登录已过期"},401);if(!admins(env,user)||!passOk(env,request))return json({ok:false,error:"仅管理员可删除黄金样本"},403);await ensure(env);const id=clean(new URL(request.url).searchParams.get("id"),120);if(!id)return json({ok:false,error:"缺少样本ID"},400);await env.DB.prepare("DELETE FROM report_golden_runs WHERE sample_id=?").bind(id).run();await env.DB.prepare("DELETE FROM report_golden_samples WHERE id=?").bind(id).run();return json({ok:true});}
