import PptxGenJS from "pptxgenjs";
import JSZip from "jszip";
import { createRequire } from "node:module";
import { buildNativeTemplatePptx, nativeTemplateEligible, resolveNativeTemplatePath } from "./ppt-native-template.js";

const require=createRequire(import.meta.url);
require("../ppt-design-ir.js");
require("../ppt-design-ir-v2.js");
const PptDesignIR=require("../ppt-premium-design.js");
const PptContentDirector=require("../ppt-content-director.js");

const PRESETS={
  "anju-blue":{accent:"2387C7",secondary:"70C5DE",dark:"173F63",bg:"F4F9FD",soft:"DDECF7",muted:"65839A",chartColors:["2387C7","70C5DE","173F63","8EB6D1"]},
  "gov-clean":{accent:"1F4E78",secondary:"A77728",dark:"1E2F3D",bg:"FFFFFF",soft:"E5EEF5",muted:"61778A",chartColors:["1F4E78","6D8FA8","A77728","B9C9D5"]},
  "data-light":{accent:"167D8D",secondary:"E09F3E",dark:"20384B",bg:"F3F8F9",soft:"DCECEE",muted:"668397",chartColors:["167D8D","49A6B1","E09F3E","8BC3C8"]}
  ,"business-blue-160":{accent:"003591",secondary:"5385C5",dark:"383535",bg:"FEFFFF",soft:"BBCEE5",muted:"9EA0A0",chartColors:["003591","5385C5","80AACD","BBCEE5","467886","9EA0A0"]}
};
const safe=(v,n=500)=>String(v==null?"":v).trim().slice(0,n);
const textOf=x=>safe(typeof x==="string"?x:(x&&x.text)||"",260);
const items=s=>Array.isArray(s.content&&s.content.items)?s.content.items:(s.bullets||[]).map((text,i)=>({label:"要点 "+(i+1),text}));
const num=v=>{const n=Number(String(v==null?"":v).replace(/[^\d.-]/g,""));return Number.isFinite(n)?n:0;};
const font=(item,size,min=8)=>Math.max(min,Math.round(size*((item&&item.qa&&item.qa.compact)?.86:1)));
function themeOf(plan){const base=PRESETS[plan.templateId]||PRESETS["anju-blue"],d=plan.designSpec||{};return{...base,accent:safe(d.accent,6)||base.accent,secondary:safe(d.secondary,6)||base.secondary,bg:safe(d.background,6)||base.bg,dark:safe(d.text,6)||base.dark,titleFont:safe(d.titleFont,80)||"Microsoft YaHei",bodyFont:safe(d.bodyFont,80)||"Microsoft YaHei",chartColors:Array.isArray(d.chartColors)&&d.chartColors.length?d.chartColors.slice(0,8):base.chartColors};}
function shadow(){return{type:"outer",color:"29485E",opacity:.12,blur:1.5,angle:45,distance:1};}
function renderDesignIr(slide,scene,pptx){
  if(!scene)return false;slide.background={color:scene.background||"FFFFFF"};
  for(const e of scene.elements||[]){
    if(e.type==="text"){slide.addText(safe(e.text,1200),{x:e.x,y:e.y,w:e.w,h:e.h,fontFace:e.fontFace||"Microsoft YaHei",fontSize:e.fontSize||14,bold:!!e.bold,color:e.color||"24292F",align:e.align||"left",valign:e.valign||"top",margin:0,fit:e.fit||"shrink",charSpacing:e.charSpacing||0,transparency:e.transparency||0});continue;}
    if(e.type==="image"&&String(e.dataUrl||"").startsWith("data:image/")){slide.addImage({data:e.dataUrl,x:e.x,y:e.y,w:e.w,h:e.h,transparency:e.transparency||0});continue;}
    if(e.type==="line"){slide.addShape("line",{x:e.x,y:e.y,w:e.w,h:e.h,line:{color:e.color||"DCE7F5",width:e.width||1,transparency:e.transparency||0}});continue;}
    if(e.type==="chart"){
      const series=(e.series||[]).slice(0,12),labels=series.map(x=>safe(x.label,40)),values=series.map(x=>num(x.value)),isLine=e.chartType==="line";
      if(series.length>=2)slide.addChart(isLine?pptx.ChartType.line:pptx.ChartType.bar,[{name:safe(e.title||"数据",50),labels,values}],{x:e.x,y:e.y,w:e.w,h:e.h,showTitle:false,showLegend:false,showValue:!isLine,dataLabelPosition:isLine?undefined:"outEnd",chartColors:e.colors||["2387C7","70C5DE","173F63"],catAxisLabelFontFace:"Microsoft YaHei",catAxisLabelFontSize:9,catAxisLabelColor:e.labelColor||"61798B",valAxisLabelFontSize:8,valAxisLabelColor:e.labelColor||"61798B",valGridLine:{color:e.gridColor||"DDECF7",size:1},catGridLine:{style:"none"},showCatName:false,showValAxisTitle:false,showCatAxisTitle:false,lineSize:2,showMarker:isLine});
      continue;
    }
    if(e.type==="table"){
      const headers=(e.headers||[]).slice(0,6),rows=(e.rows||[]).slice(0,8).map(r=>r.slice(0,6));
      if(headers.length&&rows.length){const data=[headers.map(x=>({text:safe(x,80),options:{bold:true,color:"FFFFFF",fill:e.headerFill||"2387C7",align:"center"}})),...rows.map((r,i)=>r.map(x=>({text:safe(x,100),options:{fill:i%2?e.alternateFill||"F5F9FC":"FFFFFF"}})))];slide.addTable(data,{x:e.x,y:e.y,w:e.w,h:e.h,border:{type:"solid",color:e.borderColor||"DDECF7",pt:.7},fontFace:"Microsoft YaHei",fontSize:9,color:e.textColor||"183247",margin:.06,rowH:.42,autoFit:false});}
      continue;
    }
    const kind=e.type==="shape"?(e.shape||"rect"):e.type==="ellipse"?"ellipse":e.radius?"roundRect":"rect",line=e.line?{color:e.line,width:e.width||1,transparency:e.lineTransparency||0}:{color:e.fill||scene.background||"FFFFFF",transparency:100};
    slide.addShape(kind,{x:e.x,y:e.y,w:e.w,h:e.h,rotate:e.rotate||0,rectRadius:e.radius||0,line,fill:{color:e.fill||scene.background||"FFFFFF",transparency:e.transparency||0},shadow:e.shadow?shadow():undefined});
  }
  return true;
}
function addFooter(slide,index,total,t,sources){slide.addText("AI办公助手 · AI PPT",{x:.62,y:7.13,w:3,h:.16,fontFace:t.bodyFont,fontSize:8,color:t.muted,margin:0});slide.addText((sources||[]).length+"项来源",{x:3.7,y:7.13,w:1.1,h:.16,fontFace:t.bodyFont,fontSize:8,color:t.accent,margin:0});slide.addText(index+" / "+total,{x:11.7,y:7.12,w:1,h:.16,fontFace:"Arial",fontSize:8,color:t.muted,align:"right",margin:0});}
function addTitle(slide,title,subtitle,t,kicker="PROJECT INSIGHT"){slide.addText(kicker,{x:.72,y:.42,w:3.5,h:.2,fontFace:"Arial",fontSize:8,charSpacing:2.1,color:t.accent,bold:true,margin:0});slide.addText(safe(title,100),{x:.72,y:.72,w:11.8,h:.62,fontFace:t.titleFont,fontSize:28,bold:true,color:t.dark,margin:0,fit:"shrink"});if(subtitle)slide.addText(safe(subtitle,180),{x:.72,y:1.34,w:11.3,h:.3,fontFace:t.bodyFont,fontSize:11,color:t.muted,margin:0,fit:"shrink"});}
function addBulletList(slide,bullets,t,x=.82,y=1.72,w=11.7,h=4.9,item=null){slide.addShape("roundRect",{x,y,w,h,rectRadius:.06,line:{color:t.soft,width:1},fill:{color:"FFFFFF"},shadow:shadow()});const points=(bullets||[]).slice(0,6).map(v=>({text:safe(v,220),options:{bullet:{indent:18},hanging:4,breakLine:true}}));if(points.length)slide.addText(points,{x:x+.45,y:y+.42,w:w-.9,h:h-.75,fontFace:t.bodyFont,fontSize:font(item,18,14),color:t.dark,paraSpaceAfterPt:13,margin:0,valign:"top",fit:"shrink"});}
function renderInsight(slide,item,t){addTitle(slide,item.title,item.subtitle,t,"EXECUTIVE INSIGHT");slide.addShape("roundRect",{x:.78,y:1.72,w:3.75,h:4.82,rectRadius:.07,line:{color:t.accent,transparency:100},fill:{color:t.accent},shadow:shadow()});slide.addText("核心判断",{x:1.08,y:2.05,w:1.6,h:.22,fontFace:t.bodyFont,fontSize:9,bold:true,color:"CFE0F2",margin:0});slide.addText(safe(item.claim||item.takeaway||(item.bullets||[])[0]||"本页结论待确认",180),{x:1.08,y:2.72,w:3.12,h:1.55,fontFace:t.titleFont,fontSize:22,bold:true,color:"FFFFFF",margin:0,fit:"shrink",valign:"mid"});slide.addText(safe(item.subtitle||"由材料证据与项目数据共同支撑",120),{x:1.08,y:5.62,w:3.05,h:.42,fontFace:t.bodyFont,fontSize:9,color:"DCEAF4",margin:0,fit:"shrink"});const rows=(item.bullets||[]).slice(0,6),cols=rows.length>3?2:1,w=cols===2?3.7:7.35;rows.forEach((v,i)=>{const col=i%cols,row=Math.floor(i/cols),x=4.8+col*3.82,y=1.76+row*1.43;slide.addShape("roundRect",{x,y,w:w-.14,h:1.25,rectRadius:.05,line:{color:t.soft,width:.8},fill:{color:"FFFFFF"},shadow:shadow()});slide.addText(String(i+1).padStart(2,"0"),{x:x+.18,y:y+.2,w:.42,h:.22,fontFace:"Arial",fontSize:9,bold:true,color:t.accent,margin:0});slide.addText(safe(v,190),{x:x+.72,y:y+.18,w:w-.98,h:.75,fontFace:t.bodyFont,fontSize:12,color:t.dark,margin:0,fit:"shrink",valign:"mid"});});}
function renderCover(slide,item,plan,t){slide.background={color:t.dark};slide.addShape("ellipse",{x:8.6,y:-1.4,w:6,h:6,line:{color:t.accent,transparency:100},fill:{color:t.accent,transparency:12}});slide.addShape("ellipse",{x:9.6,y:3.7,w:4.5,h:4.5,line:{color:t.secondary,transparency:100},fill:{color:t.secondary,transparency:45}});for(let i=0;i<8;i++)slide.addShape("line",{x:7.5+i*.62,y:0,w:0,h:7.5,line:{color:"FFFFFF",transparency:88,width:.5}});for(let i=0;i<6;i++)slide.addShape("line",{x:7.5,y:.5+i*.75,w:5.8,h:0,line:{color:"FFFFFF",transparency:88,width:.5}});slide.addText("SHENZHEN · HOUSING · DIGITAL",{x:.9,y:.82,w:6.5,h:.25,fontFace:"Arial",fontSize:10,charSpacing:3,color:t.secondary,margin:0});slide.addText(safe(plan.title||item.title,120),{x:.9,y:1.72,w:7.3,h:1.65,fontFace:t.titleFont,fontSize:40,bold:true,color:"FFFFFF",margin:0,fit:"shrink",valign:"mid"});slide.addText(safe(item.subtitle||plan.purpose,180),{x:.92,y:3.72,w:6.7,h:.75,fontFace:t.bodyFont,fontSize:17,color:"DCEAF4",margin:0,fit:"shrink"});slide.addText(safe((plan.designSpec&&plan.designSpec.brandName)||"深圳市安居集团",80),{x:.92,y:6.25,w:4,h:.3,fontFace:t.bodyFont,fontSize:11,color:"FFFFFF",margin:0});slide.addText(new Date().toLocaleDateString("zh-CN"),{x:.92,y:6.68,w:2.5,h:.22,fontFace:"Arial",fontSize:9,color:"AFC9DB",margin:0});}
function renderStatement(slide,item,t,section=false){slide.background={color:section?t.accent:t.dark};slide.addText(section?"SECTION":"KEY TAKEAWAY",{x:1.05,y:1.05,w:3.6,h:.25,fontFace:"Arial",fontSize:10,charSpacing:2.8,color:section?"FFFFFF":t.secondary,margin:0});slide.addText(safe(item.title,120),{x:1.05,y:1.75,w:11.1,h:2.05,fontFace:t.titleFont,fontSize:38,bold:true,color:"FFFFFF",margin:0,fit:"shrink",valign:"mid"});slide.addText(safe(item.subtitle||(item.bullets||[])[0],260),{x:1.05,y:4.35,w:9.8,h:.95,fontFace:t.bodyFont,fontSize:18,color:section?"EAF5FB":"D5E5EF",margin:0,fit:"shrink"});slide.addText(String(item.order||"").padStart(2,"0"),{x:10.7,y:5.6,w:1.3,h:.8,fontFace:"Arial",fontSize:46,bold:true,color:"FFFFFF",transparency:75,margin:0,align:"right"});}
function renderAgenda(slide,item,t){addTitle(slide,item.title,item.subtitle,t,"CONTENTS");items(item).slice(0,6).forEach((v,i)=>{const col=i%2,row=Math.floor(i/2),x=.8+col*6.05,y=1.78+row*1.42;slide.addText(String(i+1).padStart(2,"0"),{x,y,w:.65,h:.34,fontFace:"Arial",fontSize:18,bold:true,color:t.accent,margin:0});slide.addText(textOf(v),{x:x+.82,y:y-.02,w:4.9,h:.65,fontFace:t.bodyFont,fontSize:16,bold:true,color:t.dark,margin:0,fit:"shrink"});});}
function renderMetric(slide,item,t,tower=false){addTitle(slide,item.title,item.subtitle,t,"KEY METRICS");const rows=((item.content&&item.content.metrics)||items(item)).slice(0,4),w=11.75/Math.max(1,rows.length);rows.forEach((m,i)=>{const x=.78+i*w,h=tower?2.2+i%2*.65:2.75,y=tower?5.65-h:1.92;slide.addShape("roundRect",{x,y,w:w-.18,h,rectRadius:.05,line:{color:t.soft,width:1},fill:{color:i===0?t.accent:"FFFFFF",transparency:i===0?0:0},shadow:i===0?undefined:shadow()});slide.addText(safe(m.value||m.text||"—",60),{x:x+.22,y:y+.48,w:w-.62,h:.62,fontFace:"Arial",fontSize:30,bold:true,color:i===0?"FFFFFF":t.accent,margin:0,fit:"shrink"});slide.addText(safe(m.label||"关键指标",80),{x:x+.22,y:y+1.26,w:w-.62,h:.4,fontFace:t.bodyFont,fontSize:13,bold:true,color:i===0?"FFFFFF":t.dark,margin:0,fit:"shrink"});if(m.text&&m.value)slide.addText(safe(m.text,120),{x:x+.22,y:y+1.76,w:w-.62,h:.52,fontFace:t.bodyFont,fontSize:9,color:i===0?"E7F4FA":t.muted,margin:0,fit:"shrink"});});}
function renderColumns(slide,item,t){addTitle(slide,item.title,item.subtitle,t,item.recipeId==="compare-scorecard"?"DECISION OPTIONS":"DECISION COMPARE");const bs=item.bullets||[],structured=item.content&&Array.isArray(item.content.columns);if(item.recipeId==="compare-scorecard"&&!structured){const rows=((item.content&&item.content.items)||bs).slice(0,4),explicit=Number.isInteger(item.content&&item.content.recommendedIndex)?item.content.recommendedIndex:rows.findIndex(x=>/推荐|最优|更适合|更匹配|优先/.test(textOf(x))),w=11.7/Math.max(1,rows.length);rows.forEach((v,i)=>{const chosen=i===explicit,x=.8+i*w,y=chosen?1.78:1.98,h=chosen?3.65:3.25;slide.addShape("roundRect",{x,y,w:w-.18,h,rectRadius:.06,line:{color:chosen?t.accent:t.soft,width:1},fill:{color:chosen?t.accent:"FFFFFF"},shadow:shadow()});slide.addText(String.fromCharCode(65+i),{x:x+.22,y:y+.23,w:.38,h:.32,fontFace:"Arial",fontSize:14,bold:true,color:chosen?"FFFFFF":t.accent,margin:0});slide.addText(safe((v&&v.label)||("方案"+(i+1)),80),{x:x+.22,y:y+.82,w:w-.62,h:.52,fontFace:t.titleFont,fontSize:17,bold:true,color:chosen?"FFFFFF":t.dark,margin:0,fit:"shrink"});slide.addText(textOf(v),{x:x+.22,y:y+1.55,w:w-.62,h:1.0,fontFace:t.bodyFont,fontSize:10,color:chosen?"E4EFF8":t.muted,margin:0,fit:"shrink"});if(chosen)slide.addText("推荐候选",{x:x+.22,y:y+h-.48,w:1.2,h:.22,fontFace:t.bodyFont,fontSize:8,bold:true,color:"FFFFFF",margin:0});});slide.addShape("roundRect",{x:.8,y:5.76,w:11.5,h:.58,rectRadius:.04,line:{color:t.soft,transparency:100},fill:{color:t.soft,transparency:42}});slide.addText(explicit>=0?"建议判断":"比较结论",{x:1.04,y:5.94,w:1,h:.18,fontFace:t.bodyFont,fontSize:9,bold:true,color:t.accent,margin:0});slide.addText(safe(item.claim||item.takeaway||"结合项目阶段、资金节奏和风险承受能力选择",170),{x:2.08,y:5.88,w:9.85,h:.27,fontFace:t.bodyFont,fontSize:10,color:t.dark,margin:0,fit:"shrink"});return;}const cols=structured?item.content.columns:[{title:"方案A",items:bs.slice(0,Math.ceil(bs.length/2))},{title:"方案B",items:bs.slice(Math.ceil(bs.length/2))}];cols.slice(0,2).forEach((c,i)=>{const x=.78+i*6.05;slide.addShape("roundRect",{x,y:1.72,w:5.76,h:4.55,rectRadius:.05,line:{color:t.soft,width:1},fill:{color:"FFFFFF"},shadow:shadow()});slide.addText(String.fromCharCode(65+i),{x:x+.38,y:2.02,w:.45,h:.3,fontFace:"Arial",fontSize:13,bold:true,color:t.accent,margin:0});slide.addText(safe(c.title||("方案"+(i+1)),80),{x:x+.38,y:2.5,w:5,h:.46,fontFace:t.titleFont,fontSize:21,bold:true,color:t.dark,margin:0,fit:"shrink"});const pts=(c.items||[]).slice(0,5).map(v=>({text:textOf(v),options:{bullet:{indent:16},breakLine:true}}));if(pts.length)slide.addText(pts,{x:x+.4,y:3.16,w:4.9,h:2.52,fontFace:t.bodyFont,fontSize:14,color:t.dark,paraSpaceAfterPt:11,margin:0,fit:"shrink"});});if(item.claim)slide.addText(safe(item.claim,180),{x:3.05,y:6.05,w:7.2,h:.25,fontFace:t.bodyFont,fontSize:10,bold:true,color:t.accent,align:"center",margin:0,fit:"shrink"});}
function renderCards(slide,item,t,count=4){addTitle(slide,item.title,item.subtitle,t,"INSIGHT");const rows=items(item).slice(0,count),cols=count===3?3:2;rows.forEach((v,i)=>{const x=.8+(i%cols)*(11.75/cols),y=1.78+Math.floor(i/cols)*(count===3?3.8:2.25),w=11.45/cols,h=count===3?3.65:2.02;slide.addShape("roundRect",{x,y,w,h,rectRadius:.05,line:{color:t.soft,width:1},fill:{color:i===0?t.bg:"FFFFFF"},shadow:shadow()});slide.addText(String(i+1).padStart(2,"0"),{x:x+.25,y:y+.22,w:.55,h:.28,fontFace:"Arial",fontSize:12,bold:true,color:t.accent,margin:0});slide.addText(safe(v.label||v.title||("重点 "+(i+1)),70),{x:x+.25,y:y+.68,w:w-.5,h:.38,fontFace:t.titleFont,fontSize:16,bold:true,color:t.dark,margin:0,fit:"shrink"});slide.addText(textOf(v),{x:x+.25,y:y+1.18,w:w-.5,h:h-1.42,fontFace:t.bodyFont,fontSize:12,color:t.muted,margin:0,fit:"shrink"});});}
function renderSteps(slide,item,t){addTitle(slide,item.title,item.subtitle,t,item.layoutId==="process"?"EXECUTION PATH":"MILESTONE ROADMAP");const steps=((item.content&&item.content.steps)||items(item)).slice(0,6),w=11.55/Math.max(1,steps.length);slide.addShape("line",{x:1.05,y:2.28,w:11.1,h:0,line:{color:t.soft,width:2}});steps.forEach((s,i)=>{const x=.86+i*w,y=item.layoutId==="process"&&i%2?2.38:2.16;slide.addShape("roundRect",{x,y,w:w-.16,h:3.12,rectRadius:.05,line:{color:t.soft,width:.8},fill:{color:"FFFFFF"},shadow:shadow()});slide.addShape("ellipse",{x:x+.18,y:y-.25,w:.52,h:.52,line:{color:t.accent,width:1},fill:{color:t.accent}});slide.addText(String(i+1).padStart(2,"0"),{x:x+.18,y:y-.08,w:.52,h:.12,fontFace:"Arial",fontSize:7,bold:true,color:"FFFFFF",align:"center",margin:0});slide.addText(safe(s.label||s.title||("步骤"+(i+1)),60),{x:x+.18,y:y+.68,w:w-.55,h:.62,fontFace:t.titleFont,fontSize:13,bold:true,color:t.dark,margin:0,fit:"shrink"});slide.addText(safe(s.text||s.detail||"",120),{x:x+.18,y:y+1.48,w:w-.55,h:1.05,fontFace:t.bodyFont,fontSize:9,color:t.muted,margin:0,fit:"shrink"});});}
function renderRisk(slide,item,t){addTitle(slide,item.title,item.subtitle,t,"RISK CONTROL");const rows=items(item).slice(0,4);rows.forEach((v,i)=>{const col=i%2,row=Math.floor(i/2),x=.8+col*6.0,y=1.75+row*2.22;slide.addShape("roundRect",{x,y,w:5.72,h:1.94,rectRadius:.05,line:{color:t.soft,width:.8},fill:{color:"FFFFFF"},shadow:shadow()});slide.addText("R"+String(i+1).padStart(2,"0"),{x:x+.22,y:y+.24,w:.55,h:.22,fontFace:"Arial",fontSize:9,bold:true,color:t.accent,margin:0});slide.addText(safe(v.label||("风险"+(i+1)),70),{x:x+.9,y:y+.2,w:4.5,h:.34,fontFace:t.titleFont,fontSize:15,bold:true,color:t.dark,margin:0,fit:"shrink"});slide.addText(textOf(v),{x:x+.9,y:y+.72,w:4.45,h:.65,fontFace:t.bodyFont,fontSize:10,color:t.muted,margin:0,fit:"shrink"});slide.addText("影响评估 · 应对动作",{x:x+.9,y:y+1.48,w:2.3,h:.18,fontFace:t.bodyFont,fontSize:8,bold:true,color:t.accent,margin:0});});}
function renderSystem(slide,item,t){addTitle(slide,item.title,item.subtitle,t,"SYSTEM MAP");const rows=items(item).slice(0,6),cx=6.65,cy=3.8;slide.addShape("ellipse",{x:5.35,y:2.7,w:2.6,h:2.05,line:{color:t.accent,width:1.5},fill:{color:t.accent}});slide.addText(safe(item.claim||item.takeaway||"核心目标",70),{x:5.7,y:3.42,w:1.9,h:.45,fontFace:t.titleFont,fontSize:17,bold:true,color:"FFFFFF",align:"center",margin:0,fit:"shrink"});rows.forEach((r,i)=>{const angle=Math.PI*2*i/Math.max(1,rows.length)-Math.PI/2,x=cx+Math.cos(angle)*4.25-.85,y=cy+Math.sin(angle)*2.1-.38;slide.addShape("line",{x:cx,y:cy,w:x+.85-cx,h:y+.38-cy,line:{color:t.soft,width:1.5}});slide.addShape("roundRect",{x,y,w:1.7,h:.76,rectRadius:.04,line:{color:t.soft,width:1},fill:{color:"FFFFFF"},shadow:shadow()});slide.addText(safe(r.label||r.text||r,45),{x:x+.12,y:y+.19,w:1.46,h:.32,fontFace:t.bodyFont,fontSize:11,bold:true,color:t.dark,align:"center",margin:0,fit:"shrink"});});}
function renderChart(slide,item,t,pptx,line=false){addTitle(slide,item.title,item.subtitle,t,"DATA EVIDENCE");const series=((item.content&&item.content.series)||[]).slice(0,12),labels=series.map(x=>safe(x.label,30)),values=series.map(x=>num(x.value));if(series.length>=2&&values.some(x=>x!==0)){slide.addShape("roundRect",{x:.78,y:1.62,w:8.35,h:4.88,rectRadius:.05,line:{color:t.soft,width:.8},fill:{color:"FFFFFF"},shadow:shadow()});slide.addChart(line?pptx.ChartType.line:pptx.ChartType.bar,[{name:safe(item.claim||"数据",40),labels,values}],{x:1.02,y:1.92,w:7.84,h:4.28,catAxisLabelFontFace:t.bodyFont,catAxisLabelFontSize:10,catAxisLabelColor:t.muted,valAxisLabelFontSize:9,valAxisLabelColor:t.muted,valGridLine:{color:t.soft,size:1},catGridLine:{style:"none"},showLegend:false,showTitle:false,showValue:!line,dataLabelPosition:line?"t":"outEnd",chartColors:t.chartColors,showCatName:false,showValAxisTitle:false,showCatAxisTitle:false});slide.addShape("roundRect",{x:9.4,y:1.62,w:3.1,h:4.88,rectRadius:.05,line:{color:t.accent,transparency:100},fill:{color:t.accent},shadow:shadow()});slide.addText("SO WHAT",{x:9.72,y:2.05,w:1.5,h:.2,fontFace:"Arial",fontSize:8,bold:true,charSpacing:1.8,color:"CFE0F2",margin:0});slide.addText(safe(item.claim||item.takeaway||"数据变化支持本页判断",160),{x:9.72,y:2.75,w:2.45,h:1.45,fontFace:t.titleFont,fontSize:20,bold:true,color:"FFFFFF",margin:0,fit:"shrink",valign:"mid"});slide.addText(safe((item.bullets||[]).slice(0,2).join("；"),180),{x:9.72,y:4.72,w:2.42,h:.9,fontFace:t.bodyFont,fontSize:9,color:"E1EDF5",margin:0,fit:"shrink"});}else renderInsight(slide,item,t);}
function renderTable(slide,item,t){addTitle(slide,item.title,item.subtitle,t,"DATA TABLE");const c=item.content||{},headers=(c.headers||[]).slice(0,6),rows=(c.rows||[]).slice(0,8).map(r=>r.slice(0,6));if(headers.length&&rows.length){const data=[headers.map(x=>({text:safe(x,80),options:{bold:true,color:"FFFFFF",fill:t.accent,align:"center"}})),...rows.map(r=>r.map(x=>safe(x,100)))];slide.addTable(data,{x:.72,y:1.58,w:11.9,h:4.85,border:{type:"solid",color:"C9D8E4",pt:1},fontFace:t.bodyFont,fontSize:font(item,11,9),color:t.dark,fill:"FFFFFF",margin:.07,rowH:.48,autoFit:false});}else addBulletList(slide,item.bullets,t,.82,1.72,11.7,4.9,item);}
function renderImageHero(slide,item,t){const c=item.content||{},hasImage=typeof c.image==="string"&&c.image.startsWith("data:image/");addTitle(slide,item.title,item.subtitle,t,"VISUAL EVIDENCE");slide.addShape("roundRect",{x:.78,y:1.72,w:7.35,h:4.82,rectRadius:.04,line:{color:t.soft,width:1},fill:{color:t.soft}});if(hasImage)slide.addImage({data:c.image,x:.82,y:1.76,w:7.27,h:4.74});else slide.addText("核心图片槽位 · 16:10",{x:2.2,y:3.78,w:4.5,h:.35,fontFace:t.bodyFont,fontSize:15,color:t.muted,align:"center",margin:0});slide.addText(safe(item.claim||item.takeaway||(item.bullets||[])[0],220),{x:8.62,y:2.15,w:3.7,h:2.4,fontFace:t.titleFont,fontSize:23,bold:true,color:t.dark,margin:0,fit:"shrink",valign:"mid"});}
function renderConclusion(slide,item,t){slide.background={color:t.dark};slide.addText("DECISION & ACTION",{x:.9,y:.82,w:3.5,h:.25,fontFace:"Arial",fontSize:10,charSpacing:2.4,color:t.secondary,margin:0});slide.addText(safe(item.title,120),{x:.9,y:1.42,w:11.2,h:1.2,fontFace:t.titleFont,fontSize:34,bold:true,color:"FFFFFF",margin:0,fit:"shrink"});const pts=(item.bullets||[]).slice(0,5).map((v,i)=>({text:String(i+1).padStart(2,"0")+"  "+safe(v,220),options:{breakLine:true,bold:i===0}}));slide.addText(pts,{x:.92,y:3.05,w:10.7,h:2.45,fontFace:t.bodyFont,fontSize:19,color:"D9E8F1",paraSpaceAfterPt:15,margin:0,fit:"shrink"});}
function renderSlide(slide,item,plan,t,pptx,index=0){const scene=PptDesignIR.buildScene(item,plan,index);if(scene&&renderDesignIr(slide,scene,pptx))return true;const id=item.layoutId||(item.type==="cover"?"cover":item.type==="section"?"section":item.type==="conclusion"?"conclusion":"bullets");if(id==="cover")renderCover(slide,item,plan,t);else if(id==="section"||id==="statement")renderStatement(slide,item,t,id==="section");else if(id==="agenda")renderAgenda(slide,item,t);else if(id==="metric"||id==="kpi-tower")renderMetric(slide,item,t,id==="kpi-tower");else if(id==="comparison"||id==="two-column")renderColumns(slide,item,t);else if(id==="three-cards")renderCards(slide,item,t,3);else if(id==="timeline"||id==="process")renderSteps(slide,item,t);else if(id==="risk")renderRisk(slide,item,t);else if(id==="matrix")renderCards(slide,item,t,4);else if(id==="system-map")renderSystem(slide,item,t);else if(id==="chart-bar"||id==="chart-line")renderChart(slide,item,t,pptx,id==="chart-line");else if(id==="table")renderTable(slide,item,t);else if(id==="image-hero")renderImageHero(slide,item,t);else if(id==="conclusion")renderConclusion(slide,item,t);else if(id==="bullets")renderInsight(slide,item,t);else{addTitle(slide,item.title,item.subtitle,t);addBulletList(slide,item.bullets,t,.82,1.72,11.7,4.9,item);}return false;}

export async function buildPptxBuffer(plan){
  plan=PptContentDirector.applyToDeck(plan||{},{mutate:false});
  if(nativeTemplateEligible(plan)&&resolveNativeTemplatePath())return buildNativeTemplatePptx(plan);
  const pptx=new PptxGenJS(),t=themeOf(plan),slides=Array.isArray(plan.slides)?plan.slides:[];pptx.layout="LAYOUT_WIDE";pptx.author="AI可研报告生成系统";pptx.subject=safe(plan.purpose,200);pptx.title=safe(plan.title,120);pptx.company="深圳市安居集团";pptx.lang="zh-CN";pptx.theme={headFontFace:t.titleFont,bodyFontFace:t.bodyFont,lang:"zh-CN"};
  slides.forEach((item,i)=>{const slide=pptx.addSlide();slide.background={color:t.bg};const usedIr=renderSlide(slide,item,plan,t,pptx,i);if(!usedIr&&!["cover","section","statement","conclusion"].includes(item.layoutId||item.type))addFooter(slide,i+1,slides.length,t,item.sources);const refs=(item.sources||[]).map(x=>typeof x==="string"?x:(x.label||x.ref||JSON.stringify(x))).filter(Boolean);slide.addNotes("[Sources]\n"+(refs.length?refs.join("\n"):"本页内容由用户材料或项目数据库生成，未引用外部来源。"));});
  const out=await pptx.write({outputType:"nodebuffer",compression:true});return Buffer.from(out);
}

export async function validatePptxBuffer(buffer,plan={}){
  const errors=[],warnings=[];
  if(!Buffer.isBuffer(buffer)||buffer.length<1000)return{ok:false,errors:["PPTX文件为空或体积异常"],warnings,slideCount:0,mediaCount:0,chartCount:0};
  let zip;
  try{zip=await JSZip.loadAsync(buffer);}catch(e){return{ok:false,errors:["PPTX压缩包结构无法读取："+(e.message||e)],warnings,slideCount:0,mediaCount:0,chartCount:0};}
  const names=Object.keys(zip.files),slideNames=names.filter(x=>/^ppt\/slides\/slide\d+\.xml$/.test(x)),expected=Array.isArray(plan.slides)?plan.slides.length:0;
  const presentationXml=zip.file("ppt/presentation.xml")?await zip.file("ppt/presentation.xml").async("string"):"";
  const visibleSlideCount=(presentationXml.match(/<p:sldId\b/g)||[]).length||slideNames.length;
  if(expected&&visibleSlideCount!==expected)errors.push("导出页数与工程计划不一致：应为"+expected+"页，实际"+visibleSlideCount+"页");
  for(const name of slideNames){const xml=await zip.file(name).async("string");if(/<a:t>(?:undefined|NaN)<\/a:t>/i.test(xml))errors.push(name+"包含无效文本 undefined/NaN");}
  const slideMetrics=[];for(const name of slideNames){const xml=await zip.file(name).async("string"),texts=[...xml.matchAll(/<a:t>([\s\S]*?)<\/a:t>/g)].map(x=>x[1].replace(/<[^>]+>/g,"").trim()).filter(Boolean),shapeCount=(xml.match(/<p:sp>/g)||[]).length,pictureCount=(xml.match(/<p:pic>/g)||[]).length,tableCount=(xml.match(/<a:tbl>/g)||[]).length,graphicCount=(xml.match(/<p:graphicFrame>/g)||[]).length,substantiveChars=texts.slice(1,-2).join("").length;slideMetrics.push({slide:Number((name.match(/slide(\d+)/)||[])[1]),shapeCount,pictureCount,tableCount,graphicCount,textCount:texts.length,substantiveChars});if(texts.length<3||substantiveChars<12)warnings.push(name+"实质内容偏少，建议检查是否为空页");}
  const mediaCount=names.filter(x=>x.startsWith("ppt/media/")&&!x.endsWith("/")).length,chartCount=names.filter(x=>/^ppt\/charts\/chart\d+\.xml$/.test(x)).length;
  const needsImage=(plan.slides||[]).some(x=>x&&x.layoutId==="image-hero"&&x.content&&x.content.image);if(needsImage&&!mediaCount)errors.push("工程包含图片页，但PPTX没有写入任何媒体文件");
  const needsChart=(plan.slides||[]).some(x=>x&&["chart-bar","chart-line"].includes(x.layoutId)&&x.content&&Array.isArray(x.content.series)&&x.content.series.length>=2);if(needsChart&&!chartCount)warnings.push("工程包含图表页，但没有生成原生图表；请检查数据是否均为0");
  if(!names.includes("ppt/presentation.xml"))errors.push("缺少ppt/presentation.xml");
  const visualPages=slideMetrics.filter(x=>x.pictureCount||x.tableCount||x.graphicCount||x.shapeCount>=10).length,emptyPages=slideMetrics.filter(x=>x.textCount<3||x.substantiveChars<12).map(x=>x.slide);
  return{ok:errors.length===0,errors,warnings,slideCount:visibleSlideCount,mediaCount,chartCount,visualPages,emptyPages,slideMetrics,nativeTemplate:visibleSlideCount<slideNames.length};
}
