import PptxGenJS from "pptxgenjs";

const PRESETS={
  "anju-blue":{accent:"2F75B5",dark:"173F63",bg:"F5F9FD",soft:"DDECF7",muted:"6C8395"},
  "gov-clean":{accent:"1F4E78",dark:"17324A",bg:"FFFFFF",soft:"E5EEF5",muted:"61778A"},
  "data-light":{accent:"3C8DBC",dark:"20384B",bg:"F2F8FC",soft:"DDF0F8",muted:"668397"},
};
const safe=(v,n=500)=>String(v==null?"":v).trim().slice(0,n);
const textOf=x=>safe(typeof x==="string"?x:(x&&x.text)||"",260);
const items=s=>Array.isArray(s.content&&s.content.items)?s.content.items:(s.bullets||[]).map((text,i)=>({label:"要点 "+(i+1),text}));
const num=v=>{const n=Number(String(v==null?"":v).replace(/[,，%亿元万元元㎡人户套个公里km年月季度\s]/gi,""));return Number.isFinite(n)?n:0;};
function addFooter(slide,index,total,theme,sources){slide.addShape("line",{x:.55,y:7.08,w:12.22,h:0,line:{color:theme.soft,width:1}});slide.addText("AI办公助手 · AI PPT",{x:.58,y:7.12,w:3.2,h:.16,fontFace:"Microsoft YaHei",fontSize:8,color:theme.muted,margin:0});slide.addText((sources||[]).length+"项来源",{x:3.4,y:7.12,w:1.2,h:.16,fontFace:"Microsoft YaHei",fontSize:8,color:theme.accent,margin:0});slide.addText(index+" / "+total,{x:11.65,y:7.1,w:1.1,h:.18,fontFace:"Arial",fontSize:8,color:theme.muted,align:"right",margin:0});}
function addTitle(slide,title,subtitle,theme){slide.addShape("line",{x:.65,y:.58,w:.38,h:0,line:{color:theme.accent,width:2.5}});slide.addText(safe(title,100),{x:1.12,y:.31,w:11.2,h:.58,fontFace:"Microsoft YaHei",fontSize:27,bold:true,color:theme.dark,margin:0,fit:"shrink"});if(subtitle)slide.addText(safe(subtitle,180),{x:1.12,y:.96,w:10.8,h:.28,fontFace:"Microsoft YaHei",fontSize:11,color:theme.muted,margin:0,fit:"shrink"});}
function addBulletList(slide,bullets,theme,x=.95,y=1.48,w=11.35,h=4.95){const points=(bullets||[]).slice(0,6).map(v=>({text:safe(v,240),options:{bullet:{indent:19},hanging:4,breakLine:true}}));slide.addShape("roundRect",{x,y,w,h,rectRadius:.04,line:{color:theme.soft,width:1},fill:{color:"FFFFFF",transparency:4}});if(points.length)slide.addText(points,{x:x+.34,y:y+.3,w:w-.68,h:h-.55,fontFace:"Microsoft YaHei",fontSize:18,color:"27445A",paraSpaceAfterPt:12,margin:.04,valign:"top",fit:"shrink"});}
function renderCover(slide,item,plan,t){slide.addShape("rect",{x:0,y:0,w:4.2,h:7.5,line:{color:t.accent,transparency:100},fill:{color:t.accent}});slide.addText("SHENZHEN · HOUSING · DIGITAL",{x:4.82,y:1.2,w:6.8,h:.25,fontFace:"Arial",fontSize:10,charSpacing:3,color:t.accent,margin:0});slide.addText(safe(plan.title||item.title,120),{x:4.82,y:1.95,w:7.55,h:1.45,fontFace:"Microsoft YaHei",fontSize:34,bold:true,color:t.dark,margin:0,fit:"shrink",valign:"mid"});slide.addShape("line",{x:4.85,y:3.55,w:5.9,h:0,line:{color:t.soft,width:1.5}});slide.addText(safe(item.subtitle||plan.purpose,180),{x:4.85,y:3.82,w:6.8,h:.7,fontFace:"Microsoft YaHei",fontSize:16,color:t.muted,margin:0,fit:"shrink"});slide.addText(new Date().toLocaleDateString("zh-CN"),{x:4.85,y:6.45,w:2.5,h:.3,fontFace:"Arial",fontSize:10,color:t.muted,margin:0});}
function renderStatement(slide,item,t,section=false){slide.addText(section?"SECTION":"KEY TAKEAWAY",{x:1.25,y:1.55,w:3,h:.25,fontFace:"Arial",fontSize:10,charSpacing:2.5,color:t.accent,margin:0});slide.addText(safe(item.title,120),{x:1.25,y:2.05,w:10.7,h:1.5,fontFace:"Microsoft YaHei",fontSize:32,bold:true,color:t.dark,margin:0,fit:"shrink",valign:"mid"});slide.addShape("line",{x:1.25,y:3.85,w:2.2,h:0,line:{color:t.accent,width:3}});slide.addText(safe(item.subtitle||(item.bullets||[])[0],260),{x:1.25,y:4.2,w:9.5,h:.8,fontFace:"Microsoft YaHei",fontSize:17,color:t.muted,margin:0,fit:"shrink"});}
function renderMetric(slide,item,t){addTitle(slide,item.title,item.subtitle,t);const metrics=(item.content&&item.content.metrics)||items(item);const rows=metrics.slice(0,4),w=11.6/Math.max(1,rows.length);rows.forEach((m,i)=>{const x=.85+i*w;slide.addShape("rect",{x,y:1.75,w:w-.16,h:2.45,line:{color:t.soft,width:1},fill:{color:"FFFFFF"}});slide.addShape("rect",{x,y:1.75,w:w-.16,h:.08,line:{color:t.accent,transparency:100},fill:{color:t.accent}});slide.addText(safe(m.value||m.text||"—",60),{x:x+.18,y:2.18,w:w-.52,h:.62,fontFace:"Arial",fontSize:27,bold:true,color:t.accent,margin:0,fit:"shrink"});slide.addText(safe(m.label||"关键指标",80),{x:x+.18,y:3,w:w-.52,h:.38,fontFace:"Microsoft YaHei",fontSize:13,bold:true,color:t.dark,margin:0,fit:"shrink"});if(m.text&&m.value)slide.addText(safe(m.text,120),{x:x+.18,y:3.42,w:w-.52,h:.5,fontFace:"Microsoft YaHei",fontSize:9,color:t.muted,margin:0,fit:"shrink"});});}
function renderColumns(slide,item,t){addTitle(slide,item.title,item.subtitle,t);const bs=item.bullets||[],cols=(item.content&&item.content.columns)||[{title:"要点一",items:bs.slice(0,Math.ceil(bs.length/2))},{title:"要点二",items:bs.slice(Math.ceil(bs.length/2))}];cols.slice(0,2).forEach((c,i)=>{const x=.85+i*6.03;slide.addShape("rect",{x,y:1.52,w:5.72,h:4.9,line:{color:t.soft,width:1},fill:{color:"FFFFFF"}});slide.addShape("rect",{x,y:1.52,w:5.72,h:.1,line:{color:t.accent,transparency:100},fill:{color:t.accent}});slide.addText(safe(c.title||("部分"+(i+1)),80),{x:x+.3,y:1.88,w:5.1,h:.42,fontFace:"Microsoft YaHei",fontSize:18,bold:true,color:t.dark,margin:0,fit:"shrink"});const pts=(c.items||[]).slice(0,5).map(v=>({text:textOf(v),options:{bullet:{indent:16},breakLine:true}}));if(pts.length)slide.addText(pts,{x:x+.35,y:2.48,w:5,h:3.4,fontFace:"Microsoft YaHei",fontSize:15,color:"2F4A5E",paraSpaceAfterPt:10,margin:0,fit:"shrink"});});}
function renderSteps(slide,item,t){addTitle(slide,item.title,item.subtitle,t);const steps=((item.content&&item.content.steps)||items(item)).slice(0,6),w=11.65/Math.max(1,steps.length);slide.addShape("line",{x:.85,y:3.02,w:11.65,h:0,line:{color:t.soft,width:3}});steps.forEach((s,i)=>{const x=.86+i*w;slide.addShape("ellipse",{x:x+.08,y:2.72,w:.58,h:.58,line:{color:t.accent,width:1.5},fill:{color:t.accent}});slide.addText(String(i+1).padStart(2,"0"),{x:x+.08,y:2.86,w:.58,h:.14,fontFace:"Arial",fontSize:8,bold:true,color:"FFFFFF",align:"center",margin:0});slide.addText(safe(s.label||s.title||("步骤"+(i+1)),60),{x,y:3.54,w:w-.12,h:.38,fontFace:"Microsoft YaHei",fontSize:13,bold:true,color:t.dark,margin:0,fit:"shrink"});slide.addText(safe(s.text||s.detail||"",120),{x,y:4.03,w:w-.18,h:1.05,fontFace:"Microsoft YaHei",fontSize:10,color:t.muted,margin:0,fit:"shrink"});});}
function renderGrid(slide,item,t){addTitle(slide,item.title,item.subtitle,t);items(item).slice(0,4).forEach((v,i)=>{const x=.85+(i%2)*6.02,y=1.45+Math.floor(i/2)*2.45;slide.addShape("rect",{x,y,w:5.72,h:2.15,line:{color:t.soft,width:1},fill:{color:"FFFFFF"}});slide.addShape("rect",{x,y,w:.08,h:2.15,line:{color:t.accent,transparency:100},fill:{color:t.accent}});slide.addText(safe(v.label||("重点 "+(i+1)),60),{x:x+.3,y:y+.28,w:4.95,h:.34,fontFace:"Microsoft YaHei",fontSize:15,bold:true,color:t.dark,margin:0});slide.addText(textOf(v),{x:x+.3,y:y+.78,w:4.98,h:.9,fontFace:"Microsoft YaHei",fontSize:12,color:t.muted,margin:0,fit:"shrink"});});}
function renderChart(slide,item,t,pptx,line=false){addTitle(slide,item.title,item.subtitle,t);const series=((item.content&&item.content.series)||[]).slice(0,10),labels=series.map(x=>safe(x.label,30)),values=series.map(x=>num(x.value));if(series.length>=2&&values.some(x=>x!==0)){slide.addChart(line?pptx.ChartType.line:pptx.ChartType.bar,[{name:safe(item.claim||"数值",40),labels,values}],{x:.9,y:1.45,w:11.5,h:4.75,catAxisLabelFontFace:"Microsoft YaHei",catAxisLabelFontSize:10,valAxisLabelFontSize:9,showLegend:false,showTitle:false,showValue:!line,chartColors:[t.accent],showCatName:false,showValAxisTitle:false,showCatAxisTitle:false,showGridLines:true});}else addBulletList(slide,item.bullets,t);}
function renderTable(slide,item,t){addTitle(slide,item.title,item.subtitle,t);const c=item.content||{},headers=(c.headers||[]).slice(0,6),rows=(c.rows||[]).slice(0,8).map(r=>r.slice(0,6));if(headers.length&&rows.length){const data=[headers.map(x=>({text:safe(x,80),options:{bold:true,color:"FFFFFF",fill:t.accent,align:"center"}})),...rows.map(r=>r.map(x=>safe(x,100)))];slide.addTable(data,{x:.72,y:1.4,w:11.9,h:4.9,border:{type:"solid",color:"C9D8E4",pt:1},fontFace:"Microsoft YaHei",fontSize:11,color:"28465C",fill:"FFFFFF",margin:.07,rowH:.48,autoFit:false});}else addBulletList(slide,item.bullets,t);}
function renderConclusion(slide,item,t){addTitle(slide,item.title,item.subtitle,t);slide.addShape("rect",{x:.9,y:1.5,w:11.5,h:4.7,line:{color:t.soft,width:1},fill:{color:"FFFFFF"}});slide.addShape("rect",{x:.9,y:1.5,w:.13,h:4.7,line:{color:t.accent,transparency:100},fill:{color:t.accent}});slide.addText("DECISION & ACTION",{x:1.35,y:1.9,w:3.2,h:.25,fontFace:"Arial",fontSize:10,charSpacing:2,color:t.accent,margin:0});const pts=(item.bullets||[]).slice(0,5).map(v=>({text:safe(v,240),options:{bullet:{indent:18},breakLine:true}}));slide.addText(pts,{x:1.35,y:2.45,w:10.2,h:2.9,fontFace:"Microsoft YaHei",fontSize:19,color:t.dark,paraSpaceAfterPt:14,margin:0,fit:"shrink"});}
function renderSlide(slide,item,plan,t,pptx){const id=item.layoutId||(item.type==="cover"?"cover":item.type==="section"?"section":item.type==="conclusion"?"conclusion":"bullets");if(id==="cover")return renderCover(slide,item,plan,t);if(id==="section"||id==="statement")return renderStatement(slide,item,t,id==="section");if(id==="metric")return renderMetric(slide,item,t);if(id==="comparison"||id==="two-column")return renderColumns(slide,item,t);if(id==="timeline"||id==="process")return renderSteps(slide,item,t);if(id==="risk"||id==="matrix")return renderGrid(slide,item,t);if(id==="chart-bar"||id==="chart-line")return renderChart(slide,item,t,pptx,id==="chart-line");if(id==="table")return renderTable(slide,item,t);if(id==="conclusion")return renderConclusion(slide,item,t);addTitle(slide,item.title,item.subtitle,t);addBulletList(slide,item.bullets,t);}

export async function buildPptxBuffer(plan){
  const pptx=new PptxGenJS(),theme=PRESETS[plan.templateId]||PRESETS["anju-blue"],slides=Array.isArray(plan.slides)?plan.slides:[];pptx.layout="LAYOUT_WIDE";pptx.author="AI可研报告生成系统";pptx.subject=safe(plan.purpose,200);pptx.title=safe(plan.title,120);pptx.company="深圳市安居集团";pptx.lang="zh-CN";pptx.theme={headFontFace:"Microsoft YaHei",bodyFontFace:"Microsoft YaHei",lang:"zh-CN"};
  slides.forEach((item,i)=>{const slide=pptx.addSlide();slide.background={color:theme.bg};renderSlide(slide,item,plan,theme,pptx);if((item.layoutId||item.type)!=="cover")addFooter(slide,i+1,slides.length,theme,item.sources);const refs=(item.sources||[]).map(x=>typeof x==="string"?x:(x.label||x.ref||JSON.stringify(x))).filter(Boolean);slide.addNotes("[Sources]\n"+(refs.length?refs.join("\n"):"本页基于用户提供资料或系统内项目数据生成；未引用外部来源。"));});
  const out=await pptx.write({outputType:"nodebuffer",compression:true});return Buffer.from(out);
}
